// Code generated by scripts/ci/gen_reason_codes.py from protocols/json-schemas/reason-codes/reason-codes-v1.json. DO NOT EDIT.

// Package reasoncodes names the codes in the HELM reason-code registry.
//
// A reason code is an open string on the wire. These constants name the
// registered codes; a code missing from this list is still a valid value, not
// an error.
package reasoncodes

// PolicyViolation DENY: Effect violates an active policy rule
const PolicyViolation = "POLICY_VIOLATION"

// NoPolicyDefined DENY: No policy covers this effect type
const NoPolicyDefined = "NO_POLICY_DEFINED"

// PolicyNotReady DENY: No verified EffectivePolicySnapshot is installed for the
// requested scope
const PolicyNotReady = "POLICY_NOT_READY"

// PolicyHashMismatch DENY: Policy source bytes did not match the published
// canonical policy hash
const PolicyHashMismatch = "POLICY_HASH_MISMATCH"

// PolicySignatureInvalid DENY: Policy source signature or provenance
// verification failed
const PolicySignatureInvalid = "POLICY_SIGNATURE_INVALID"

// PolicyEpochChanged DENY: The active policy epoch changed before the effect
// could be issued
const PolicyEpochChanged = "POLICY_EPOCH_CHANGED"

// PrgEvaluationError DENY: Policy Requirement Graph evaluation failed
const PrgEvaluationError = "PRG_EVALUATION_ERROR"

// SchemaViolation DENY: Request does not conform to schema
const SchemaViolation = "SCHEMA_VIOLATION"

// PdpDeny DENY: External PDP returned deny
const PdpDeny = "PDP_DENY"

// PdpError DENY: PDP unavailable or returned error (fail-closed)
const PdpError = "PDP_ERROR"

// MissingRequirement DENY: Required precondition not satisfied
const MissingRequirement = "MISSING_REQUIREMENT"

// BudgetExceeded DENY: Operation exceeds allocated budget
const BudgetExceeded = "BUDGET_EXCEEDED"

// BudgetError DENY: Budget system unavailable (fail-closed)
const BudgetError = "BUDGET_ERROR"

// TemporalIntervention ESCALATE: Time-based intervention triggered
const TemporalIntervention = "TEMPORAL_INTERVENTION"

// TemporalThrottle ESCALATE: Rate limit or cooldown active
const TemporalThrottle = "TEMPORAL_THROTTLE"

// SessionRiskMemoryDeny DENY: Session trajectory risk exceeded the
// deterministic authorization threshold
const SessionRiskMemoryDeny = "SESSION_RISK_MEMORY_DENY"

// EnvelopeInvalid DENY: Effect envelope failed validation
const EnvelopeInvalid = "ENVELOPE_INVALID"

// ProvenanceFailure DENY: Provenance chain broken or unverifiable
const ProvenanceFailure = "PROVENANCE_FAILURE"

// VerificationFailure DENY: Cryptographic verification failed
const VerificationFailure = "VERIFICATION_FAILURE"

// SandboxViolation DENY: Effect exceeds sandbox boundary
const SandboxViolation = "SANDBOX_VIOLATION"

// TenantIsolation DENY: Cross-tenant access violation
const TenantIsolation = "TENANT_ISOLATION"

// JurisdictionViolation DENY: Effect violates jurisdictional constraint
const JurisdictionViolation = "JURISDICTION_VIOLATION"

// SystemFrozen DENY: System is in global freeze state — all actions denied
const SystemFrozen = "SYSTEM_FROZEN"

// EmergencyStopScopeRequired DENY: A governed dispatch omitted the
// authoritative tenant/workspace scope required while emergency-stop fencing is
// enabled
const EmergencyStopScopeRequired = "EMERGENCY_STOP_SCOPE_REQUIRED"

// EmergencyStopUnverified DENY: Emergency-stop fence status could not be
// verified, so the governed dispatch was denied fail-closed
const EmergencyStopUnverified = "EMERGENCY_STOP_UNVERIFIED"

// EmergencyStopFenced DENY: A durable tenant/workspace emergency-stop fence is
// active for newly governed dispatches
const EmergencyStopFenced = "EMERGENCY_STOP_FENCED"

// ContextMismatch DENY: Environment fingerprint does not match boot-time
// snapshot
const ContextMismatch = "CONTEXT_MISMATCH"

// DataEgressBlocked DENY: Data transmission to unauthorized external endpoint
// blocked
const DataEgressBlocked = "DATA_EGRESS_BLOCKED"

// ErrHostEgressWithoutIntent DENY: Host-observed egress has no corresponding
// HELM intent or authority receipt
const ErrHostEgressWithoutIntent = "ERR_HOST_EGRESS_WITHOUT_INTENT"

// ErrHostEgressAfterDeny DENY: Host-observed egress occurred after HELM denied
// the corresponding action
const ErrHostEgressAfterDeny = "ERR_HOST_EGRESS_AFTER_DENY"

// ErrHostReceiptMissing DENY: A HELM network-authority receipt has no matching
// host evidence receipt
const ErrHostReceiptMissing = "ERR_HOST_RECEIPT_MISSING"

// ErrHostDestinationMismatch DENY: Host-observed egress destination differs
// from HELM authority metadata
const ErrHostDestinationMismatch = "ERR_HOST_DESTINATION_MISMATCH"

// ErrHostVolumeExceeded DENY: Host-observed egress byte volume exceeds the HELM
// authority ceiling
const ErrHostVolumeExceeded = "ERR_HOST_VOLUME_EXCEEDED"

// ErrHostProcessUnbound DENY: Host receipt process identity cannot be bound to
// a HELM workload identity
const ErrHostProcessUnbound = "ERR_HOST_PROCESS_UNBOUND"

// ErrPolicyDeniedButHostObservedEgress DENY: Host evidence contradicts a HELM
// policy denial for network egress
const ErrPolicyDeniedButHostObservedEgress = "ERR_POLICY_DENIED_BUT_HOST_OBSERVED_EGRESS"

// IdentityIsolationViolation DENY: Agent credential reuse or impersonation
// detected
const IdentityIsolationViolation = "IDENTITY_ISOLATION_VIOLATION"

// InsufficientPrivilege DENY: Agent privilege tier insufficient for requested
// effect type
const InsufficientPrivilege = "INSUFFICIENT_PRIVILEGE"

// ApprovalRequired ESCALATE: High-risk effect requires human approval before
// execution
const ApprovalRequired = "APPROVAL_REQUIRED"

// ApprovalTimeout DENY: Human approval not received within timeout — action
// denied
const ApprovalTimeout = "APPROVAL_TIMEOUT"

// ActivationTrustUnavailable DENY: No pinned control-plane activation
// verification key is configured
const ActivationTrustUnavailable = "ACTIVATION_TRUST_UNAVAILABLE"

// ActivationRecordInvalid DENY: The company activation record failed schema,
// integrity, signature, or lifetime validation
const ActivationRecordInvalid = "ACTIVATION_RECORD_INVALID"

// ActivationBindingMismatch DENY: The company activation record does not match
// the authenticated tenant, company domain, workspace, or configured
// environment
const ActivationBindingMismatch = "ACTIVATION_BINDING_MISMATCH"

// ActivationCeilingExceeded DENY: The signed or requested effect, autonomy, or
// exposure limit exceeds the current company activation ceiling
const ActivationCeilingExceeded = "ACTIVATION_CEILING_EXCEEDED"

// DelegationInvalid DENY: Delegation session is invalid, expired, revoked, or
// has a binding mismatch
const DelegationInvalid = "DELEGATION_INVALID"

// DelegationScopeViolation DENY: Delegate attempted an action outside the
// session's granted capabilities
const DelegationScopeViolation = "DELEGATION_SCOPE_VIOLATION"

// DelegationPrincipalMismatch DENY: Requesting principal does not match the
// delegation session's bound delegate principal
const DelegationPrincipalMismatch = "DELEGATION_PRINCIPAL_MISMATCH"

// AgentKilled DENY: Agent has been terminated via per-agent kill switch
const AgentKilled = "AGENT_KILLED"

// TaintedInputHighRiskDeny DENY: High-risk effect denied due to
// tainted/untrusted input source
const TaintedInputHighRiskDeny = "TAINTED_INPUT_HIGH_RISK_DENY"

// PromptInjectionDetected DENY: Prompt injection pattern detected in untrusted
// input
const PromptInjectionDetected = "PROMPT_INJECTION_DETECTED"

// UnicodeObfuscationDetected DENY: Unicode obfuscation (zero-width chars,
// homoglyphs) detected
const UnicodeObfuscationDetected = "UNICODE_OBFUSCATION_DETECTED"

// TaintedCredentialAccessDeny DENY: Credential or token access attempted from
// tainted source
const TaintedCredentialAccessDeny = "TAINTED_CREDENTIAL_ACCESS_DENY"

// TaintedSoftwarePublishDeny DENY: Software publish or release attempted from
// tainted source
const TaintedSoftwarePublishDeny = "TAINTED_SOFTWARE_PUBLISH_DENY"

// TaintedPrivilegedInvokeDeny DENY: Privileged agent invocation attempted from
// tainted source
const TaintedPrivilegedInvokeDeny = "TAINTED_PRIVILEGED_INVOKE_DENY"

// TaintedDataEgressDeny DENY: Data egress or exfiltration attempted from
// tainted source
const TaintedDataEgressDeny = "TAINTED_DATA_EGRESS_DENY"

// TaintedHighRiskEscalate ESCALATE: High-risk effect from tainted source
// requires human approval
const TaintedHighRiskEscalate = "TAINTED_HIGH_RISK_ESCALATE"

// SemanticThreatReviewRequired ESCALATE: Configured deterministic semantic
// advisory requires human review
const SemanticThreatReviewRequired = "SEMANTIC_THREAT_REVIEW_REQUIRED"

// ErrTonActonUnknownCommand DENY: Requested Acton action is not one of the
// typed HELM TON Acton actions
const ErrTonActonUnknownCommand = "ERR_TON_ACTON_UNKNOWN_COMMAND"

// ErrTonActonUnsupportedVersion DENY: Observed Acton version is outside the
// connector contract
const ErrTonActonUnsupportedVersion = "ERR_TON_ACTON_UNSUPPORTED_VERSION"

// ErrTonTolkCompilerUnpinned DENY: A Tolk compiler version pin is required for
// bytecode-sensitive TON work
const ErrTonTolkCompilerUnpinned = "ERR_TON_TOLK_COMPILER_UNPINNED"

// ErrTonTolkCompilerMismatch DENY: Observed Tolk compiler version does not
// match policy or connector contract
const ErrTonTolkCompilerMismatch = "ERR_TON_TOLK_COMPILER_MISMATCH"

// ErrTonActonArgvRejected DENY: Acton argv failed typed connector validation
const ErrTonActonArgvRejected = "ERR_TON_ACTON_ARGV_REJECTED"

// ErrTonActonRawShellForbidden DENY: Raw shell or raw command execution was
// requested for Acton
const ErrTonActonRawShellForbidden = "ERR_TON_ACTON_RAW_SHELL_FORBIDDEN"

// ErrTonActonGenericMainnetScriptDenied DENY: Generic Acton mainnet script
// execution is denied by default
const ErrTonActonGenericMainnetScriptDenied = "ERR_TON_ACTON_GENERIC_MAINNET_SCRIPT_DENIED"

// ErrTonScriptManifestRequired DENY: Networked Acton script is missing the
// required HELM sidecar manifest
const ErrTonScriptManifestRequired = "ERR_TON_SCRIPT_MANIFEST_REQUIRED"

// ErrTonScriptManifestHashMismatch DENY: Acton script hash does not match the
// HELM sidecar manifest
const ErrTonScriptManifestHashMismatch = "ERR_TON_SCRIPT_MANIFEST_HASH_MISMATCH"

// ErrTonExpectedEffectMismatch DENY/ESCALATE: Declared TON expected effects are
// missing or do not match the action envelope
const ErrTonExpectedEffectMismatch = "ERR_TON_EXPECTED_EFFECT_MISMATCH"

// ErrTonSpendCeilingExceeded DENY: TON spend exceeds action or daily policy
// ceilings
const ErrTonSpendCeilingExceeded = "ERR_TON_SPEND_CEILING_EXCEEDED"

// ErrTonMainnetRequiresApproval ESCALATE: TON mainnet action requires policy
// approval before dispatch
const ErrTonMainnetRequiresApproval = "ERR_TON_MAINNET_REQUIRES_APPROVAL"

// ErrTonApprovalCeremonyRequired ESCALATE: TON T3 action requires approval
// ceremony evidence
const ErrTonApprovalCeremonyRequired = "ERR_TON_APPROVAL_CEREMONY_REQUIRED"

// ErrTonWalletRefRequired DENY: TON action requires an opaque wallet reference
const ErrTonWalletRefRequired = "ERR_TON_WALLET_REF_REQUIRED"

// ErrTonPlaintextMnemonicForbidden DENY: Plaintext wallet mnemonic or private
// key material is forbidden
const ErrTonPlaintextMnemonicForbidden = "ERR_TON_PLAINTEXT_MNEMONIC_FORBIDDEN"

// ErrTonNetworkGrantRequired DENY: TON networked action requires an explicit
// sandbox network grant
const ErrTonNetworkGrantRequired = "ERR_TON_NETWORK_GRANT_REQUIRED"

// ErrTonSandboxGrantRequired DENY: Acton execution requires a valid HELM
// sandbox grant
const ErrTonSandboxGrantRequired = "ERR_TON_SANDBOX_GRANT_REQUIRED"

// ErrTonSourceVerificationRequired DENY: TON source verification evidence is
// required before the action can dispatch
const ErrTonSourceVerificationRequired = "ERR_TON_SOURCE_VERIFICATION_REQUIRED"

// ErrTonVerifyDryRunRequired DENY: TON verifier dry-run evidence is required
// before final verification or deployment
const ErrTonVerifyDryRunRequired = "ERR_TON_VERIFY_DRY_RUN_REQUIRED"

// ErrTonVerifyBytecodeMismatch DENY: TON verifier bytecode comparison failed
const ErrTonVerifyBytecodeMismatch = "ERR_TON_VERIFY_BYTECODE_MISMATCH"

// ErrTonCoverageThresholdFailed DENY/ESCALATE: Acton coverage result is below
// policy threshold
const ErrTonCoverageThresholdFailed = "ERR_TON_COVERAGE_THRESHOLD_FAILED"

// ErrTonMutationThresholdFailed DENY/ESCALATE: Acton mutation score is below
// policy threshold
const ErrTonMutationThresholdFailed = "ERR_TON_MUTATION_THRESHOLD_FAILED"

// ErrTonLibraryMainnetRequiresApproval ESCALATE: Mainnet TON library publish or
// top-up requires approval
const ErrTonLibraryMainnetRequiresApproval = "ERR_TON_LIBRARY_MAINNET_REQUIRES_APPROVAL"

// ErrTonLibrarySpendCeilingExceeded DENY: TON library publish or top-up exceeds
// spend ceilings
const ErrTonLibrarySpendCeilingExceeded = "ERR_TON_LIBRARY_SPEND_CEILING_EXCEEDED"

// ErrConnectorContractDrift DENY: Connector observed output shape drift and
// failed closed
const ErrConnectorContractDrift = "ERR_CONNECTOR_CONTRACT_DRIFT"

// ErrComputeGasExhausted DENY: Sandboxed execution exhausted configured compute
// or gas budget
const ErrComputeGasExhausted = "ERR_COMPUTE_GAS_EXHAUSTED"

// ErrComputeTimeExhausted DENY: Sandboxed execution exceeded the configured
// wall-clock time budget
const ErrComputeTimeExhausted = "ERR_COMPUTE_TIME_EXHAUSTED"

// ErrHarnessTraceRequired DENY: Side-effectful execution is missing a hash-
// linked HarnessTrace
const ErrHarnessTraceRequired = "ERR_HARNESS_TRACE_REQUIRED"

// ErrPlanTransactionRequired DENY: Multi-artifact or write-bearing execution is
// missing a PlanTransaction
const ErrPlanTransactionRequired = "ERR_PLAN_TRANSACTION_REQUIRED"

// ErrPlanTransactionConflict DENY/ESCALATE: PlanTransaction read/write sets
// conflict with another open transaction
const ErrPlanTransactionConflict = "ERR_PLAN_TRANSACTION_CONFLICT"

// ErrAssumptionStale DENY/ESCALATE: A declared plan assumption or dependency is
// stale before side-effect dispatch
const ErrAssumptionStale = "ERR_ASSUMPTION_STALE"

// ErrHarnessMutationRequiresApproval ESCALATE: Mutation of connector, tool,
// sandbox, policy, verifier, evidence, or routing state requires explicit
// approval
const ErrHarnessMutationRequiresApproval = "ERR_HARNESS_MUTATION_REQUIRES_APPROVAL"

// ErrGreenTestScopeMissing DENY: Passing tests were submitted without a
// declared verification scope
const ErrGreenTestScopeMissing = "ERR_GREEN_TEST_SCOPE_MISSING"

// ErrGroundedActionRefRequired DENY: GUI or computer-use action is missing
// grounded screenshot and DOM/accessibility evidence
const ErrGroundedActionRefRequired = "ERR_GROUNDED_ACTION_REF_REQUIRED"

// ErrGuiPostconditionUnverified DENY: GUI or computer-use action postcondition
// was not verified
const ErrGuiPostconditionUnverified = "ERR_GUI_POSTCONDITION_UNVERIFIED"

// SafedepTerminalFreeze DENY: Safe Deprecation classified the hazard as
// terminal freeze
const SafedepTerminalFreeze = "SAFEDEP_TERMINAL_FREEZE"

// SafedepDegradedNarrowing ESCALATE: Safe Deprecation classified the hazard as
// recoverable degraded narrowing
const SafedepDegradedNarrowing = "SAFEDEP_DEGRADED_NARROWING"

// SafedepDeprecatedReadonly DENY: Safe Deprecation classified the hazard as
// read-only deprecation
const SafedepDeprecatedReadonly = "SAFEDEP_DEPRECATED_READONLY"

// ErrContinuityStale DENY: Safe Deprecation continuity checkpoint is stale,
// replayed, expired, or rollbacked
const ErrContinuityStale = "ERR_CONTINUITY_STALE"

// ErrEmergencyCapsuleInvalid DENY: Emergency capsule failed binding, expiry,
// subset-proof, or delegation validation
const ErrEmergencyCapsuleInvalid = "ERR_EMERGENCY_CAPSULE_INVALID"

// ErrHardwareQuorumUnbound DENY: Hardware-bound emergency quorum is missing,
// duplicated, unauthorized, or revoked
const ErrHardwareQuorumUnbound = "ERR_HARDWARE_QUORUM_UNBOUND"

// ErrAttestationResultRequired DENY: Signed verifier-issued attestation result
// is required for emergency authorization
const ErrAttestationResultRequired = "ERR_ATTESTATION_RESULT_REQUIRED"

// ErrDevFallbackPresent DENY: Dev, audit, mock, software-key, env-fallback, or
// unsigned overlay path is enabled
const ErrDevFallbackPresent = "ERR_DEV_FALLBACK_PRESENT"

// CapabilityUnknown ESCALATE: Dispatched capability_id is not registered and is
// quarantined for review
const CapabilityUnknown = "CAPABILITY_UNKNOWN"

// CapabilityManifestDrift DENY: Caller-pinned capability manifest hash does not
// match the registry revision
const CapabilityManifestDrift = "CAPABILITY_MANIFEST_DRIFT"

// CapabilityTokenInvalid DENY: Task capability token is malformed, expired,
// revoked, exhausted, out of scope, or fails signature/binding verification
const CapabilityTokenInvalid = "CAPABILITY_TOKEN_INVALID"

// CapabilityRollbackPlanInvalid DENY: Reversible non-read-only capability lacks
// a loadable, matching, valid rollback plan
const CapabilityRollbackPlanInvalid = "CAPABILITY_ROLLBACK_PLAN_INVALID"

// CapabilityIrreversible DENY: Irreversible effect class cannot dispatch
// without an authoritative approval integration
const CapabilityIrreversible = "CAPABILITY_IRREVERSIBLE"

var all = [...]string{
	PolicyViolation,
	NoPolicyDefined,
	PolicyNotReady,
	PolicyHashMismatch,
	PolicySignatureInvalid,
	PolicyEpochChanged,
	PrgEvaluationError,
	SchemaViolation,
	PdpDeny,
	PdpError,
	MissingRequirement,
	BudgetExceeded,
	BudgetError,
	TemporalIntervention,
	TemporalThrottle,
	SessionRiskMemoryDeny,
	EnvelopeInvalid,
	ProvenanceFailure,
	VerificationFailure,
	SandboxViolation,
	TenantIsolation,
	JurisdictionViolation,
	SystemFrozen,
	EmergencyStopScopeRequired,
	EmergencyStopUnverified,
	EmergencyStopFenced,
	ContextMismatch,
	DataEgressBlocked,
	ErrHostEgressWithoutIntent,
	ErrHostEgressAfterDeny,
	ErrHostReceiptMissing,
	ErrHostDestinationMismatch,
	ErrHostVolumeExceeded,
	ErrHostProcessUnbound,
	ErrPolicyDeniedButHostObservedEgress,
	IdentityIsolationViolation,
	InsufficientPrivilege,
	ApprovalRequired,
	ApprovalTimeout,
	ActivationTrustUnavailable,
	ActivationRecordInvalid,
	ActivationBindingMismatch,
	ActivationCeilingExceeded,
	DelegationInvalid,
	DelegationScopeViolation,
	DelegationPrincipalMismatch,
	AgentKilled,
	TaintedInputHighRiskDeny,
	PromptInjectionDetected,
	UnicodeObfuscationDetected,
	TaintedCredentialAccessDeny,
	TaintedSoftwarePublishDeny,
	TaintedPrivilegedInvokeDeny,
	TaintedDataEgressDeny,
	TaintedHighRiskEscalate,
	SemanticThreatReviewRequired,
	ErrTonActonUnknownCommand,
	ErrTonActonUnsupportedVersion,
	ErrTonTolkCompilerUnpinned,
	ErrTonTolkCompilerMismatch,
	ErrTonActonArgvRejected,
	ErrTonActonRawShellForbidden,
	ErrTonActonGenericMainnetScriptDenied,
	ErrTonScriptManifestRequired,
	ErrTonScriptManifestHashMismatch,
	ErrTonExpectedEffectMismatch,
	ErrTonSpendCeilingExceeded,
	ErrTonMainnetRequiresApproval,
	ErrTonApprovalCeremonyRequired,
	ErrTonWalletRefRequired,
	ErrTonPlaintextMnemonicForbidden,
	ErrTonNetworkGrantRequired,
	ErrTonSandboxGrantRequired,
	ErrTonSourceVerificationRequired,
	ErrTonVerifyDryRunRequired,
	ErrTonVerifyBytecodeMismatch,
	ErrTonCoverageThresholdFailed,
	ErrTonMutationThresholdFailed,
	ErrTonLibraryMainnetRequiresApproval,
	ErrTonLibrarySpendCeilingExceeded,
	ErrConnectorContractDrift,
	ErrComputeGasExhausted,
	ErrComputeTimeExhausted,
	ErrHarnessTraceRequired,
	ErrPlanTransactionRequired,
	ErrPlanTransactionConflict,
	ErrAssumptionStale,
	ErrHarnessMutationRequiresApproval,
	ErrGreenTestScopeMissing,
	ErrGroundedActionRefRequired,
	ErrGuiPostconditionUnverified,
	SafedepTerminalFreeze,
	SafedepDegradedNarrowing,
	SafedepDeprecatedReadonly,
	ErrContinuityStale,
	ErrEmergencyCapsuleInvalid,
	ErrHardwareQuorumUnbound,
	ErrAttestationResultRequired,
	ErrDevFallbackPresent,
	CapabilityUnknown,
	CapabilityManifestDrift,
	CapabilityTokenInvalid,
	CapabilityRollbackPlanInvalid,
	CapabilityIrreversible,
}

// All returns every registered reason code, in registry order.
func All() []string {
	return append([]string(nil), all[:]...)
}

// IsRegistered reports whether code is in the registry.
func IsRegistered(code string) bool {
	for _, registered := range all {
		if registered == code {
			return true
		}
	}
	return false
}
