// Code generated by scripts/ci/gen_reason_codes.py from protocols/json-schemas/reason-codes/reason-codes-v1.json. DO NOT EDIT.

/**
 * A reason code is an open string on the wire. These constants name the
 * registered codes; a code missing from this list is still a valid value, not
 * an error.
 */
export const ReasonCodes = {
  /** DENY: Effect violates an active policy rule */
  POLICY_VIOLATION: "POLICY_VIOLATION",
  /** DENY: No policy covers this effect type */
  NO_POLICY_DEFINED: "NO_POLICY_DEFINED",
  /** DENY: No verified EffectivePolicySnapshot is installed for the requested scope */
  POLICY_NOT_READY: "POLICY_NOT_READY",
  /** DENY: Policy source bytes did not match the published canonical policy hash */
  POLICY_HASH_MISMATCH: "POLICY_HASH_MISMATCH",
  /** DENY: Policy source signature or provenance verification failed */
  POLICY_SIGNATURE_INVALID: "POLICY_SIGNATURE_INVALID",
  /** DENY: The active policy epoch changed before the effect could be issued */
  POLICY_EPOCH_CHANGED: "POLICY_EPOCH_CHANGED",
  /** DENY: Policy Requirement Graph evaluation failed */
  PRG_EVALUATION_ERROR: "PRG_EVALUATION_ERROR",
  /** DENY: Request does not conform to schema */
  SCHEMA_VIOLATION: "SCHEMA_VIOLATION",
  /** DENY: External PDP returned deny */
  PDP_DENY: "PDP_DENY",
  /** DENY: PDP unavailable or returned error (fail-closed) */
  PDP_ERROR: "PDP_ERROR",
  /** DENY: Required precondition not satisfied */
  MISSING_REQUIREMENT: "MISSING_REQUIREMENT",
  /** DENY: Operation exceeds allocated budget */
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  /** DENY: Budget system unavailable (fail-closed) */
  BUDGET_ERROR: "BUDGET_ERROR",
  /** ESCALATE: Time-based intervention triggered */
  TEMPORAL_INTERVENTION: "TEMPORAL_INTERVENTION",
  /** ESCALATE: Rate limit or cooldown active */
  TEMPORAL_THROTTLE: "TEMPORAL_THROTTLE",
  /** DENY: Session trajectory risk exceeded the deterministic authorization threshold */
  SESSION_RISK_MEMORY_DENY: "SESSION_RISK_MEMORY_DENY",
  /** DENY: Effect envelope failed validation */
  ENVELOPE_INVALID: "ENVELOPE_INVALID",
  /** DENY: Provenance chain broken or unverifiable */
  PROVENANCE_FAILURE: "PROVENANCE_FAILURE",
  /** DENY: Cryptographic verification failed */
  VERIFICATION_FAILURE: "VERIFICATION_FAILURE",
  /** DENY: Effect exceeds sandbox boundary */
  SANDBOX_VIOLATION: "SANDBOX_VIOLATION",
  /** DENY: Cross-tenant access violation */
  TENANT_ISOLATION: "TENANT_ISOLATION",
  /** DENY: Effect violates jurisdictional constraint */
  JURISDICTION_VIOLATION: "JURISDICTION_VIOLATION",
  /** DENY: System is in global freeze state — all actions denied */
  SYSTEM_FROZEN: "SYSTEM_FROZEN",
  /** DENY: A governed dispatch omitted the authoritative tenant/workspace scope required while
  /** emergency-stop fencing is enabled */
  EMERGENCY_STOP_SCOPE_REQUIRED: "EMERGENCY_STOP_SCOPE_REQUIRED",
  /** DENY: Emergency-stop fence status could not be verified, so the governed dispatch was denied
  /** fail-closed */
  EMERGENCY_STOP_UNVERIFIED: "EMERGENCY_STOP_UNVERIFIED",
  /** DENY: A durable tenant/workspace emergency-stop fence is active for newly governed dispatches */
  EMERGENCY_STOP_FENCED: "EMERGENCY_STOP_FENCED",
  /** DENY: Environment fingerprint does not match boot-time snapshot */
  CONTEXT_MISMATCH: "CONTEXT_MISMATCH",
  /** DENY: Data transmission to unauthorized external endpoint blocked */
  DATA_EGRESS_BLOCKED: "DATA_EGRESS_BLOCKED",
  /** DENY: Host-observed egress has no corresponding HELM intent or authority receipt */
  ERR_HOST_EGRESS_WITHOUT_INTENT: "ERR_HOST_EGRESS_WITHOUT_INTENT",
  /** DENY: Host-observed egress occurred after HELM denied the corresponding action */
  ERR_HOST_EGRESS_AFTER_DENY: "ERR_HOST_EGRESS_AFTER_DENY",
  /** DENY: A HELM network-authority receipt has no matching host evidence receipt */
  ERR_HOST_RECEIPT_MISSING: "ERR_HOST_RECEIPT_MISSING",
  /** DENY: Host-observed egress destination differs from HELM authority metadata */
  ERR_HOST_DESTINATION_MISMATCH: "ERR_HOST_DESTINATION_MISMATCH",
  /** DENY: Host-observed egress byte volume exceeds the HELM authority ceiling */
  ERR_HOST_VOLUME_EXCEEDED: "ERR_HOST_VOLUME_EXCEEDED",
  /** DENY: Host receipt process identity cannot be bound to a HELM workload identity */
  ERR_HOST_PROCESS_UNBOUND: "ERR_HOST_PROCESS_UNBOUND",
  /** DENY: Host evidence contradicts a HELM policy denial for network egress */
  ERR_POLICY_DENIED_BUT_HOST_OBSERVED_EGRESS: "ERR_POLICY_DENIED_BUT_HOST_OBSERVED_EGRESS",
  /** DENY: Agent credential reuse or impersonation detected */
  IDENTITY_ISOLATION_VIOLATION: "IDENTITY_ISOLATION_VIOLATION",
  /** DENY: Agent privilege tier insufficient for requested effect type */
  INSUFFICIENT_PRIVILEGE: "INSUFFICIENT_PRIVILEGE",
  /** ESCALATE: High-risk effect requires human approval before execution */
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  /** DENY: Human approval not received within timeout — action denied */
  APPROVAL_TIMEOUT: "APPROVAL_TIMEOUT",
  /** DENY: No pinned control-plane activation verification key is configured */
  ACTIVATION_TRUST_UNAVAILABLE: "ACTIVATION_TRUST_UNAVAILABLE",
  /** DENY: The company activation record failed schema, integrity, signature, or lifetime
  /** validation */
  ACTIVATION_RECORD_INVALID: "ACTIVATION_RECORD_INVALID",
  /** DENY: The company activation record does not match the authenticated tenant, company domain,
  /** workspace, or configured environment */
  ACTIVATION_BINDING_MISMATCH: "ACTIVATION_BINDING_MISMATCH",
  /** DENY: The signed or requested effect, autonomy, or exposure limit exceeds the current company
  /** activation ceiling */
  ACTIVATION_CEILING_EXCEEDED: "ACTIVATION_CEILING_EXCEEDED",
  /** DENY: Delegation session is invalid, expired, revoked, or has a binding mismatch */
  DELEGATION_INVALID: "DELEGATION_INVALID",
  /** DENY: Delegate attempted an action outside the session's granted capabilities */
  DELEGATION_SCOPE_VIOLATION: "DELEGATION_SCOPE_VIOLATION",
  /** DENY: Requesting principal does not match the delegation session's bound delegate principal */
  DELEGATION_PRINCIPAL_MISMATCH: "DELEGATION_PRINCIPAL_MISMATCH",
  /** DENY: Agent has been terminated via per-agent kill switch */
  AGENT_KILLED: "AGENT_KILLED",
  /** DENY: High-risk effect denied due to tainted/untrusted input source */
  TAINTED_INPUT_HIGH_RISK_DENY: "TAINTED_INPUT_HIGH_RISK_DENY",
  /** DENY: Prompt injection pattern detected in untrusted input */
  PROMPT_INJECTION_DETECTED: "PROMPT_INJECTION_DETECTED",
  /** DENY: Unicode obfuscation (zero-width chars, homoglyphs) detected */
  UNICODE_OBFUSCATION_DETECTED: "UNICODE_OBFUSCATION_DETECTED",
  /** DENY: Credential or token access attempted from tainted source */
  TAINTED_CREDENTIAL_ACCESS_DENY: "TAINTED_CREDENTIAL_ACCESS_DENY",
  /** DENY: Software publish or release attempted from tainted source */
  TAINTED_SOFTWARE_PUBLISH_DENY: "TAINTED_SOFTWARE_PUBLISH_DENY",
  /** DENY: Privileged agent invocation attempted from tainted source */
  TAINTED_PRIVILEGED_INVOKE_DENY: "TAINTED_PRIVILEGED_INVOKE_DENY",
  /** DENY: Data egress or exfiltration attempted from tainted source */
  TAINTED_DATA_EGRESS_DENY: "TAINTED_DATA_EGRESS_DENY",
  /** ESCALATE: High-risk effect from tainted source requires human approval */
  TAINTED_HIGH_RISK_ESCALATE: "TAINTED_HIGH_RISK_ESCALATE",
  /** ESCALATE: Configured deterministic semantic advisory requires human review */
  SEMANTIC_THREAT_REVIEW_REQUIRED: "SEMANTIC_THREAT_REVIEW_REQUIRED",
  /** DENY: Requested Acton action is not one of the typed HELM TON Acton actions */
  ERR_TON_ACTON_UNKNOWN_COMMAND: "ERR_TON_ACTON_UNKNOWN_COMMAND",
  /** DENY: Observed Acton version is outside the connector contract */
  ERR_TON_ACTON_UNSUPPORTED_VERSION: "ERR_TON_ACTON_UNSUPPORTED_VERSION",
  /** DENY: A Tolk compiler version pin is required for bytecode-sensitive TON work */
  ERR_TON_TOLK_COMPILER_UNPINNED: "ERR_TON_TOLK_COMPILER_UNPINNED",
  /** DENY: Observed Tolk compiler version does not match policy or connector contract */
  ERR_TON_TOLK_COMPILER_MISMATCH: "ERR_TON_TOLK_COMPILER_MISMATCH",
  /** DENY: Acton argv failed typed connector validation */
  ERR_TON_ACTON_ARGV_REJECTED: "ERR_TON_ACTON_ARGV_REJECTED",
  /** DENY: Raw shell or raw command execution was requested for Acton */
  ERR_TON_ACTON_RAW_SHELL_FORBIDDEN: "ERR_TON_ACTON_RAW_SHELL_FORBIDDEN",
  /** DENY: Generic Acton mainnet script execution is denied by default */
  ERR_TON_ACTON_GENERIC_MAINNET_SCRIPT_DENIED: "ERR_TON_ACTON_GENERIC_MAINNET_SCRIPT_DENIED",
  /** DENY: Networked Acton script is missing the required HELM sidecar manifest */
  ERR_TON_SCRIPT_MANIFEST_REQUIRED: "ERR_TON_SCRIPT_MANIFEST_REQUIRED",
  /** DENY: Acton script hash does not match the HELM sidecar manifest */
  ERR_TON_SCRIPT_MANIFEST_HASH_MISMATCH: "ERR_TON_SCRIPT_MANIFEST_HASH_MISMATCH",
  /** DENY/ESCALATE: Declared TON expected effects are missing or do not match the action envelope */
  ERR_TON_EXPECTED_EFFECT_MISMATCH: "ERR_TON_EXPECTED_EFFECT_MISMATCH",
  /** DENY: TON spend exceeds action or daily policy ceilings */
  ERR_TON_SPEND_CEILING_EXCEEDED: "ERR_TON_SPEND_CEILING_EXCEEDED",
  /** ESCALATE: TON mainnet action requires policy approval before dispatch */
  ERR_TON_MAINNET_REQUIRES_APPROVAL: "ERR_TON_MAINNET_REQUIRES_APPROVAL",
  /** ESCALATE: TON T3 action requires approval ceremony evidence */
  ERR_TON_APPROVAL_CEREMONY_REQUIRED: "ERR_TON_APPROVAL_CEREMONY_REQUIRED",
  /** DENY: TON action requires an opaque wallet reference */
  ERR_TON_WALLET_REF_REQUIRED: "ERR_TON_WALLET_REF_REQUIRED",
  /** DENY: Plaintext wallet mnemonic or private key material is forbidden */
  ERR_TON_PLAINTEXT_MNEMONIC_FORBIDDEN: "ERR_TON_PLAINTEXT_MNEMONIC_FORBIDDEN",
  /** DENY: TON networked action requires an explicit sandbox network grant */
  ERR_TON_NETWORK_GRANT_REQUIRED: "ERR_TON_NETWORK_GRANT_REQUIRED",
  /** DENY: Acton execution requires a valid HELM sandbox grant */
  ERR_TON_SANDBOX_GRANT_REQUIRED: "ERR_TON_SANDBOX_GRANT_REQUIRED",
  /** DENY: TON source verification evidence is required before the action can dispatch */
  ERR_TON_SOURCE_VERIFICATION_REQUIRED: "ERR_TON_SOURCE_VERIFICATION_REQUIRED",
  /** DENY: TON verifier dry-run evidence is required before final verification or deployment */
  ERR_TON_VERIFY_DRY_RUN_REQUIRED: "ERR_TON_VERIFY_DRY_RUN_REQUIRED",
  /** DENY: TON verifier bytecode comparison failed */
  ERR_TON_VERIFY_BYTECODE_MISMATCH: "ERR_TON_VERIFY_BYTECODE_MISMATCH",
  /** DENY/ESCALATE: Acton coverage result is below policy threshold */
  ERR_TON_COVERAGE_THRESHOLD_FAILED: "ERR_TON_COVERAGE_THRESHOLD_FAILED",
  /** DENY/ESCALATE: Acton mutation score is below policy threshold */
  ERR_TON_MUTATION_THRESHOLD_FAILED: "ERR_TON_MUTATION_THRESHOLD_FAILED",
  /** ESCALATE: Mainnet TON library publish or top-up requires approval */
  ERR_TON_LIBRARY_MAINNET_REQUIRES_APPROVAL: "ERR_TON_LIBRARY_MAINNET_REQUIRES_APPROVAL",
  /** DENY: TON library publish or top-up exceeds spend ceilings */
  ERR_TON_LIBRARY_SPEND_CEILING_EXCEEDED: "ERR_TON_LIBRARY_SPEND_CEILING_EXCEEDED",
  /** DENY: Connector observed output shape drift and failed closed */
  ERR_CONNECTOR_CONTRACT_DRIFT: "ERR_CONNECTOR_CONTRACT_DRIFT",
  /** DENY: Sandboxed execution exhausted configured compute or gas budget */
  ERR_COMPUTE_GAS_EXHAUSTED: "ERR_COMPUTE_GAS_EXHAUSTED",
  /** DENY: Sandboxed execution exceeded the configured wall-clock time budget */
  ERR_COMPUTE_TIME_EXHAUSTED: "ERR_COMPUTE_TIME_EXHAUSTED",
  /** DENY: Side-effectful execution is missing a hash-linked HarnessTrace */
  ERR_HARNESS_TRACE_REQUIRED: "ERR_HARNESS_TRACE_REQUIRED",
  /** DENY: Multi-artifact or write-bearing execution is missing a PlanTransaction */
  ERR_PLAN_TRANSACTION_REQUIRED: "ERR_PLAN_TRANSACTION_REQUIRED",
  /** DENY/ESCALATE: PlanTransaction read/write sets conflict with another open transaction */
  ERR_PLAN_TRANSACTION_CONFLICT: "ERR_PLAN_TRANSACTION_CONFLICT",
  /** DENY/ESCALATE: A declared plan assumption or dependency is stale before side-effect dispatch */
  ERR_ASSUMPTION_STALE: "ERR_ASSUMPTION_STALE",
  /** ESCALATE: Mutation of connector, tool, sandbox, policy, verifier, evidence, or routing state
  /** requires explicit approval */
  ERR_HARNESS_MUTATION_REQUIRES_APPROVAL: "ERR_HARNESS_MUTATION_REQUIRES_APPROVAL",
  /** DENY: Passing tests were submitted without a declared verification scope */
  ERR_GREEN_TEST_SCOPE_MISSING: "ERR_GREEN_TEST_SCOPE_MISSING",
  /** DENY: GUI or computer-use action is missing grounded screenshot and DOM/accessibility evidence */
  ERR_GROUNDED_ACTION_REF_REQUIRED: "ERR_GROUNDED_ACTION_REF_REQUIRED",
  /** DENY: GUI or computer-use action postcondition was not verified */
  ERR_GUI_POSTCONDITION_UNVERIFIED: "ERR_GUI_POSTCONDITION_UNVERIFIED",
  /** DENY: Safe Deprecation classified the hazard as terminal freeze */
  SAFEDEP_TERMINAL_FREEZE: "SAFEDEP_TERMINAL_FREEZE",
  /** ESCALATE: Safe Deprecation classified the hazard as recoverable degraded narrowing */
  SAFEDEP_DEGRADED_NARROWING: "SAFEDEP_DEGRADED_NARROWING",
  /** DENY: Safe Deprecation classified the hazard as read-only deprecation */
  SAFEDEP_DEPRECATED_READONLY: "SAFEDEP_DEPRECATED_READONLY",
  /** DENY: Safe Deprecation continuity checkpoint is stale, replayed, expired, or rollbacked */
  ERR_CONTINUITY_STALE: "ERR_CONTINUITY_STALE",
  /** DENY: Emergency capsule failed binding, expiry, subset-proof, or delegation validation */
  ERR_EMERGENCY_CAPSULE_INVALID: "ERR_EMERGENCY_CAPSULE_INVALID",
  /** DENY: Hardware-bound emergency quorum is missing, duplicated, unauthorized, or revoked */
  ERR_HARDWARE_QUORUM_UNBOUND: "ERR_HARDWARE_QUORUM_UNBOUND",
  /** DENY: Signed verifier-issued attestation result is required for emergency authorization */
  ERR_ATTESTATION_RESULT_REQUIRED: "ERR_ATTESTATION_RESULT_REQUIRED",
  /** DENY: Dev, audit, mock, software-key, env-fallback, or unsigned overlay path is enabled */
  ERR_DEV_FALLBACK_PRESENT: "ERR_DEV_FALLBACK_PRESENT",
  /** ESCALATE: Dispatched capability_id is not registered and is quarantined for review */
  CAPABILITY_UNKNOWN: "CAPABILITY_UNKNOWN",
  /** DENY: Caller-pinned capability manifest hash does not match the registry revision */
  CAPABILITY_MANIFEST_DRIFT: "CAPABILITY_MANIFEST_DRIFT",
  /** DENY: Task capability token is malformed, expired, revoked, exhausted, out of scope, or fails
  /** signature/binding verification */
  CAPABILITY_TOKEN_INVALID: "CAPABILITY_TOKEN_INVALID",
  /** DENY: Reversible non-read-only capability lacks a loadable, matching, valid rollback plan */
  CAPABILITY_ROLLBACK_PLAN_INVALID: "CAPABILITY_ROLLBACK_PLAN_INVALID",
  /** DENY: Irreversible effect class cannot dispatch without an authoritative approval integration */
  CAPABILITY_IRREVERSIBLE: "CAPABILITY_IRREVERSIBLE",
} as const;

export type RegisteredReasonCode = (typeof ReasonCodes)[keyof typeof ReasonCodes];

const registered: ReadonlySet<string> = new Set(Object.values(ReasonCodes));

/** Whether `code` is in the registry. */
export function isRegisteredReasonCode(code: string): code is RegisteredReasonCode {
  return registered.has(code);
}
