// AUTO-GENERATED from api/openapi/helm.openapi.yaml — DO NOT EDIT
// Regenerate: bash scripts/sdk/gen.sh

const mapValues = <T, R>(data: { [key: string]: T }, fn: (item: T) => R): { [key: string]: R } =>
    Object.keys(data).reduce((acc, key) => ({ ...acc, [key]: fn(data[key]) }), {} as { [key: string]: R });

const stringFromJSONTyped = (json: any, _ignoreDiscriminator: boolean): string => json;
const stringToJSON = (value: string): any => value;
const instanceOfstring = (value: any): value is string => typeof value === 'string';
const numberFromJSONTyped = (json: any, _ignoreDiscriminator: boolean): number => json;
const numberToJSON = (value: number): any => value;
const instanceOfnumber = (value: any): value is number => typeof value === 'number';

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddTrustKey200Response
 */
export interface AddTrustKey200Response {
    /**
     *
     * @type {string}
     * @memberof AddTrustKey200Response
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof AddTrustKey200Response
     */
    tenant_id?: string;
    /**
     *
     * @type {string}
     * @memberof AddTrustKey200Response
     */
    key_id?: string;
}

/**
 * Check if a given object implements the AddTrustKey200Response interface.
 */
export function instanceOfAddTrustKey200Response(value: object): boolean {
    return true;
}

export function AddTrustKey200ResponseFromJSON(json: any): AddTrustKey200Response {
    return AddTrustKey200ResponseFromJSONTyped(json, false);
}

export function AddTrustKey200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTrustKey200Response {
    if (json == null) {
        return json;
    }
    return {

        'status': json['status'] == null ? undefined : json['status'],
        'tenant_id': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'key_id': json['key_id'] == null ? undefined : json['key_id'],
    };
}

export function AddTrustKey200ResponseToJSON(value?: AddTrustKey200Response | null): any {
    if (value == null) {
        return value;
    }
    return {

        'status': value['status'],
        'tenant_id': value['tenant_id'],
        'key_id': value['key_id'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddTrustKeyRequest
 */
export interface AddTrustKeyRequest {
    /**
     *
     * @type {string}
     * @memberof AddTrustKeyRequest
     */
    tenant_id: string;
    /**
     *
     * @type {string}
     * @memberof AddTrustKeyRequest
     */
    key_id: string;
    /**
     * Hex-encoded Ed25519 public key
     * @type {string}
     * @memberof AddTrustKeyRequest
     */
    public_key: string;
}

/**
 * Check if a given object implements the AddTrustKeyRequest interface.
 */
export function instanceOfAddTrustKeyRequest(value: object): boolean {
    if (!('tenant_id' in value)) return false;
    if (!('key_id' in value)) return false;
    if (!('public_key' in value)) return false;
    return true;
}

export function AddTrustKeyRequestFromJSON(json: any): AddTrustKeyRequest {
    return AddTrustKeyRequestFromJSONTyped(json, false);
}

export function AddTrustKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTrustKeyRequest {
    if (json == null) {
        return json;
    }
    return {

        'tenant_id': json['tenant_id'],
        'key_id': json['key_id'],
        'public_key': json['public_key'],
    };
}

export function AddTrustKeyRequestToJSON(value?: AddTrustKeyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'tenant_id': value['tenant_id'],
        'key_id': value['key_id'],
        'public_key': value['public_key'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApprovalRequest
 */
export interface ApprovalRequest {
    /**
     * SHA-256 hash of the intent to approve
     * @type {string}
     * @memberof ApprovalRequest
     */
    intent_hash: string;
    /**
     * Base64-encoded Ed25519 signature
     * @type {string}
     * @memberof ApprovalRequest
     */
    signature_b64: string;
    /**
     * Base64-encoded Ed25519 public key
     * @type {string}
     * @memberof ApprovalRequest
     */
    public_key_b64: string;
    /**
     * Optional challenge/response for ceremony
     * @type {string}
     * @memberof ApprovalRequest
     */
    challenge_response?: string;
}

/**
 * Check if a given object implements the ApprovalRequest interface.
 */
export function instanceOfApprovalRequest(value: object): boolean {
    if (!('intent_hash' in value)) return false;
    if (!('signature_b64' in value)) return false;
    if (!('public_key_b64' in value)) return false;
    return true;
}

export function ApprovalRequestFromJSON(json: any): ApprovalRequest {
    return ApprovalRequestFromJSONTyped(json, false);
}

export function ApprovalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalRequest {
    if (json == null) {
        return json;
    }
    return {

        'intent_hash': json['intent_hash'],
        'signature_b64': json['signature_b64'],
        'public_key_b64': json['public_key_b64'],
        'challenge_response': json['challenge_response'] == null ? undefined : json['challenge_response'],
    };
}

export function ApprovalRequestToJSON(value?: ApprovalRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'intent_hash': value['intent_hash'],
        'signature_b64': value['signature_b64'],
        'public_key_b64': value['public_key_b64'],
        'challenge_response': value['challenge_response'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ChatCompletionRequest
 */
export interface ChatCompletionRequest {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionRequest
     */
    model: string;
    /**
     *
     * @type {Array<ChatCompletionRequestMessagesInner>}
     * @memberof ChatCompletionRequest
     */
    messages: Array<ChatCompletionRequestMessagesInner>;
    /**
     *
     * @type {Array<ChatCompletionRequestToolsInner>}
     * @memberof ChatCompletionRequest
     */
    tools?: Array<ChatCompletionRequestToolsInner>;
    /**
     *
     * @type {number}
     * @memberof ChatCompletionRequest
     */
    temperature?: number;
    /**
     *
     * @type {number}
     * @memberof ChatCompletionRequest
     */
    max_tokens?: number;
    /**
     *
     * @type {boolean}
     * @memberof ChatCompletionRequest
     */
    stream?: boolean;
}

/**
 * Check if a given object implements the ChatCompletionRequest interface.
 */
export function instanceOfChatCompletionRequest(value: object): boolean {
    if (!('model' in value)) return false;
    if (!('messages' in value)) return false;
    return true;
}

export function ChatCompletionRequestFromJSON(json: any): ChatCompletionRequest {
    return ChatCompletionRequestFromJSONTyped(json, false);
}

export function ChatCompletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequest {
    if (json == null) {
        return json;
    }
    return {

        'model': json['model'],
        'messages': ((json['messages'] as Array<any>).map(ChatCompletionRequestMessagesInnerFromJSON)),
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(ChatCompletionRequestToolsInnerFromJSON)),
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'max_tokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function ChatCompletionRequestToJSON(value?: ChatCompletionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'model': value['model'],
        'messages': ((value['messages'] as Array<any>).map(ChatCompletionRequestMessagesInnerToJSON)),
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(ChatCompletionRequestToolsInnerToJSON)),
        'temperature': value['temperature'],
        'max_tokens': value['max_tokens'],
        'stream': value['stream'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatCompletionRequestMessagesInner
 */
export interface ChatCompletionRequestMessagesInner {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionRequestMessagesInner
     */
    role: ChatCompletionRequestMessagesInnerRoleEnum;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionRequestMessagesInner
     */
    content: string;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionRequestMessagesInner
     */
    tool_call_id?: string;
}


/**
 * @export
 */
export const ChatCompletionRequestMessagesInnerRoleEnum = {
    System: 'system',
    User: 'user',
    Assistant: 'assistant',
    Tool: 'tool'
} as const;
export type ChatCompletionRequestMessagesInnerRoleEnum = typeof ChatCompletionRequestMessagesInnerRoleEnum[keyof typeof ChatCompletionRequestMessagesInnerRoleEnum];


/**
 * Check if a given object implements the ChatCompletionRequestMessagesInner interface.
 */
export function instanceOfChatCompletionRequestMessagesInner(value: object): boolean {
    if (!('role' in value)) return false;
    if (!('content' in value)) return false;
    return true;
}

export function ChatCompletionRequestMessagesInnerFromJSON(json: any): ChatCompletionRequestMessagesInner {
    return ChatCompletionRequestMessagesInnerFromJSONTyped(json, false);
}

export function ChatCompletionRequestMessagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestMessagesInner {
    if (json == null) {
        return json;
    }
    return {

        'role': json['role'],
        'content': json['content'],
        'tool_call_id': json['tool_call_id'] == null ? undefined : json['tool_call_id'],
    };
}

export function ChatCompletionRequestMessagesInnerToJSON(value?: ChatCompletionRequestMessagesInner | null): any {
    if (value == null) {
        return value;
    }
    return {

        'role': value['role'],
        'content': value['content'],
        'tool_call_id': value['tool_call_id'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ChatCompletionRequestToolsInner
 */
export interface ChatCompletionRequestToolsInner {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionRequestToolsInner
     */
    type?: ChatCompletionRequestToolsInnerTypeEnum;
    /**
     *
     * @type {ChatCompletionRequestToolsInnerFunction}
     * @memberof ChatCompletionRequestToolsInner
     */
    _function?: ChatCompletionRequestToolsInnerFunction;
}


/**
 * @export
 */
export const ChatCompletionRequestToolsInnerTypeEnum = {
    Function: 'function'
} as const;
export type ChatCompletionRequestToolsInnerTypeEnum = typeof ChatCompletionRequestToolsInnerTypeEnum[keyof typeof ChatCompletionRequestToolsInnerTypeEnum];


/**
 * Check if a given object implements the ChatCompletionRequestToolsInner interface.
 */
export function instanceOfChatCompletionRequestToolsInner(value: object): boolean {
    return true;
}

export function ChatCompletionRequestToolsInnerFromJSON(json: any): ChatCompletionRequestToolsInner {
    return ChatCompletionRequestToolsInnerFromJSONTyped(json, false);
}

export function ChatCompletionRequestToolsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestToolsInner {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'] == null ? undefined : json['type'],
        '_function': json['function'] == null ? undefined : ChatCompletionRequestToolsInnerFunctionFromJSON(json['function']),
    };
}

export function ChatCompletionRequestToolsInnerToJSON(value?: ChatCompletionRequestToolsInner | null): any {
    if (value == null) {
        return value;
    }
    return {

        'type': value['type'],
        'function': ChatCompletionRequestToolsInnerFunctionToJSON(value['_function']),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatCompletionRequestToolsInnerFunction
 */
export interface ChatCompletionRequestToolsInnerFunction {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionRequestToolsInnerFunction
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionRequestToolsInnerFunction
     */
    description?: string;
    /**
     *
     * @type {object}
     * @memberof ChatCompletionRequestToolsInnerFunction
     */
    parameters?: object;
}

/**
 * Check if a given object implements the ChatCompletionRequestToolsInnerFunction interface.
 */
export function instanceOfChatCompletionRequestToolsInnerFunction(value: object): boolean {
    return true;
}

export function ChatCompletionRequestToolsInnerFunctionFromJSON(json: any): ChatCompletionRequestToolsInnerFunction {
    return ChatCompletionRequestToolsInnerFunctionFromJSONTyped(json, false);
}

export function ChatCompletionRequestToolsInnerFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionRequestToolsInnerFunction {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function ChatCompletionRequestToolsInnerFunctionToJSON(value?: ChatCompletionRequestToolsInnerFunction | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ChatCompletionResponse
 */
export interface ChatCompletionResponse {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    object?: string;
    /**
     *
     * @type {number}
     * @memberof ChatCompletionResponse
     */
    created?: number;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    model?: string;
    /**
     *
     * @type {Array<ChatCompletionResponseChoicesInner>}
     * @memberof ChatCompletionResponse
     */
    choices?: Array<ChatCompletionResponseChoicesInner>;
    /**
     *
     * @type {ChatCompletionResponseUsage}
     * @memberof ChatCompletionResponse
     */
    usage?: ChatCompletionResponseUsage;
}

/**
 * Check if a given object implements the ChatCompletionResponse interface.
 */
export function instanceOfChatCompletionResponse(value: object): boolean {
    return true;
}

export function ChatCompletionResponseFromJSON(json: any): ChatCompletionResponse {
    return ChatCompletionResponseFromJSONTyped(json, false);
}

export function ChatCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'object': json['object'] == null ? undefined : json['object'],
        'created': json['created'] == null ? undefined : json['created'],
        'model': json['model'] == null ? undefined : json['model'],
        'choices': json['choices'] == null ? undefined : ((json['choices'] as Array<any>).map(ChatCompletionResponseChoicesInnerFromJSON)),
        'usage': json['usage'] == null ? undefined : ChatCompletionResponseUsageFromJSON(json['usage']),
    };
}

export function ChatCompletionResponseToJSON(value?: ChatCompletionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'model': value['model'],
        'choices': value['choices'] == null ? undefined : ((value['choices'] as Array<any>).map(ChatCompletionResponseChoicesInnerToJSON)),
        'usage': ChatCompletionResponseUsageToJSON(value['usage']),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ChatCompletionResponseChoicesInner
 */
export interface ChatCompletionResponseChoicesInner {
    /**
     *
     * @type {number}
     * @memberof ChatCompletionResponseChoicesInner
     */
    index?: number;
    /**
     *
     * @type {ChatCompletionResponseChoicesInnerMessage}
     * @memberof ChatCompletionResponseChoicesInner
     */
    message?: ChatCompletionResponseChoicesInnerMessage;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInner
     */
    finish_reason?: string;
}

/**
 * Check if a given object implements the ChatCompletionResponseChoicesInner interface.
 */
export function instanceOfChatCompletionResponseChoicesInner(value: object): boolean {
    return true;
}

export function ChatCompletionResponseChoicesInnerFromJSON(json: any): ChatCompletionResponseChoicesInner {
    return ChatCompletionResponseChoicesInnerFromJSONTyped(json, false);
}

export function ChatCompletionResponseChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseChoicesInner {
    if (json == null) {
        return json;
    }
    return {

        'index': json['index'] == null ? undefined : json['index'],
        'message': json['message'] == null ? undefined : ChatCompletionResponseChoicesInnerMessageFromJSON(json['message']),
        'finish_reason': json['finish_reason'] == null ? undefined : json['finish_reason'],
    };
}

export function ChatCompletionResponseChoicesInnerToJSON(value?: ChatCompletionResponseChoicesInner | null): any {
    if (value == null) {
        return value;
    }
    return {

        'index': value['index'],
        'message': ChatCompletionResponseChoicesInnerMessageToJSON(value['message']),
        'finish_reason': value['finish_reason'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ChatCompletionResponseChoicesInnerMessage
 */
export interface ChatCompletionResponseChoicesInnerMessage {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInnerMessage
     */
    role?: string;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInnerMessage
     */
    content?: string;
    /**
     *
     * @type {Array<ChatCompletionResponseChoicesInnerMessageToolCallsInner>}
     * @memberof ChatCompletionResponseChoicesInnerMessage
     */
    tool_calls?: Array<ChatCompletionResponseChoicesInnerMessageToolCallsInner>;
}

/**
 * Check if a given object implements the ChatCompletionResponseChoicesInnerMessage interface.
 */
export function instanceOfChatCompletionResponseChoicesInnerMessage(value: object): boolean {
    return true;
}

export function ChatCompletionResponseChoicesInnerMessageFromJSON(json: any): ChatCompletionResponseChoicesInnerMessage {
    return ChatCompletionResponseChoicesInnerMessageFromJSONTyped(json, false);
}

export function ChatCompletionResponseChoicesInnerMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseChoicesInnerMessage {
    if (json == null) {
        return json;
    }
    return {

        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'tool_calls': json['tool_calls'] == null ? undefined : ((json['tool_calls'] as Array<any>).map(ChatCompletionResponseChoicesInnerMessageToolCallsInnerFromJSON)),
    };
}

export function ChatCompletionResponseChoicesInnerMessageToJSON(value?: ChatCompletionResponseChoicesInnerMessage | null): any {
    if (value == null) {
        return value;
    }
    return {

        'role': value['role'],
        'content': value['content'],
        'tool_calls': value['tool_calls'] == null ? undefined : ((value['tool_calls'] as Array<any>).map(ChatCompletionResponseChoicesInnerMessageToolCallsInnerToJSON)),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface ChatCompletionResponseChoicesInnerMessageToolCallsInner
 */
export interface ChatCompletionResponseChoicesInnerMessageToolCallsInner {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInnerMessageToolCallsInner
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInnerMessageToolCallsInner
     */
    type?: string;
    /**
     *
     * @type {ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction}
     * @memberof ChatCompletionResponseChoicesInnerMessageToolCallsInner
     */
    _function?: ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction;
}

/**
 * Check if a given object implements the ChatCompletionResponseChoicesInnerMessageToolCallsInner interface.
 */
export function instanceOfChatCompletionResponseChoicesInnerMessageToolCallsInner(value: object): boolean {
    return true;
}

export function ChatCompletionResponseChoicesInnerMessageToolCallsInnerFromJSON(json: any): ChatCompletionResponseChoicesInnerMessageToolCallsInner {
    return ChatCompletionResponseChoicesInnerMessageToolCallsInnerFromJSONTyped(json, false);
}

export function ChatCompletionResponseChoicesInnerMessageToolCallsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseChoicesInnerMessageToolCallsInner {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        '_function': json['function'] == null ? undefined : ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunctionFromJSON(json['function']),
    };
}

export function ChatCompletionResponseChoicesInnerMessageToolCallsInnerToJSON(value?: ChatCompletionResponseChoicesInnerMessageToolCallsInner | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'type': value['type'],
        'function': ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunctionToJSON(value['_function']),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction
 */
export interface ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction {
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction
     */
    arguments?: string;
}

/**
 * Check if a given object implements the ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction interface.
 */
export function instanceOfChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction(value: object): boolean {
    return true;
}

export function ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunctionFromJSON(json: any): ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction {
    return ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunctionFromJSONTyped(json, false);
}

export function ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'] == null ? undefined : json['name'],
        'arguments': json['arguments'] == null ? undefined : json['arguments'],
    };
}

export function ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunctionToJSON(value?: ChatCompletionResponseChoicesInnerMessageToolCallsInnerFunction | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'arguments': value['arguments'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatCompletionResponseUsage
 */
export interface ChatCompletionResponseUsage {
    /**
     *
     * @type {number}
     * @memberof ChatCompletionResponseUsage
     */
    prompt_tokens?: number;
    /**
     *
     * @type {number}
     * @memberof ChatCompletionResponseUsage
     */
    completion_tokens?: number;
    /**
     *
     * @type {number}
     * @memberof ChatCompletionResponseUsage
     */
    total_tokens?: number;
}

/**
 * Check if a given object implements the ChatCompletionResponseUsage interface.
 */
export function instanceOfChatCompletionResponseUsage(value: object): boolean {
    return true;
}

export function ChatCompletionResponseUsageFromJSON(json: any): ChatCompletionResponseUsage {
    return ChatCompletionResponseUsageFromJSONTyped(json, false);
}

export function ChatCompletionResponseUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseUsage {
    if (json == null) {
        return json;
    }
    return {

        'prompt_tokens': json['prompt_tokens'] == null ? undefined : json['prompt_tokens'],
        'completion_tokens': json['completion_tokens'] == null ? undefined : json['completion_tokens'],
        'total_tokens': json['total_tokens'] == null ? undefined : json['total_tokens'],
    };
}

export function ChatCompletionResponseUsageToJSON(value?: ChatCompletionResponseUsage | null): any {
    if (value == null) {
        return value;
    }
    return {

        'prompt_tokens': value['prompt_tokens'],
        'completion_tokens': value['completion_tokens'],
        'total_tokens': value['total_tokens'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConformanceRequest
 */
export interface ConformanceRequest {
    /**
     *
     * @type {string}
     * @memberof ConformanceRequest
     */
    level: ConformanceRequestLevelEnum;
    /**
     *
     * @type {string}
     * @memberof ConformanceRequest
     */
    profile?: string;
}


/**
 * @export
 */
export const ConformanceRequestLevelEnum = {
    L1: 'L1',
    L2: 'L2'
} as const;
export type ConformanceRequestLevelEnum = typeof ConformanceRequestLevelEnum[keyof typeof ConformanceRequestLevelEnum];


/**
 * Check if a given object implements the ConformanceRequest interface.
 */
export function instanceOfConformanceRequest(value: object): boolean {
    if (!('level' in value)) return false;
    return true;
}

export function ConformanceRequestFromJSON(json: any): ConformanceRequest {
    return ConformanceRequestFromJSONTyped(json, false);
}

export function ConformanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConformanceRequest {
    if (json == null) {
        return json;
    }
    return {

        'level': json['level'],
        'profile': json['profile'] == null ? undefined : json['profile'],
    };
}

export function ConformanceRequestToJSON(value?: ConformanceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'level': value['level'],
        'profile': value['profile'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConformanceResult
 */
export interface ConformanceResult {
    /**
     *
     * @type {string}
     * @memberof ConformanceResult
     */
    report_id?: string;
    /**
     *
     * @type {string}
     * @memberof ConformanceResult
     */
    level?: string;
    /**
     *
     * @type {string}
     * @memberof ConformanceResult
     */
    verdict?: ConformanceResultVerdictEnum;
    /**
     *
     * @type {number}
     * @memberof ConformanceResult
     */
    gates?: number;
    /**
     *
     * @type {number}
     * @memberof ConformanceResult
     */
    failed?: number;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ConformanceResult
     */
    details?: { [key: string]: string; };
}


/**
 * @export
 */
export const ConformanceResultVerdictEnum = {
    Pass: 'PASS',
    Fail: 'FAIL'
} as const;
export type ConformanceResultVerdictEnum = typeof ConformanceResultVerdictEnum[keyof typeof ConformanceResultVerdictEnum];


/**
 * Check if a given object implements the ConformanceResult interface.
 */
export function instanceOfConformanceResult(value: object): boolean {
    return true;
}

export function ConformanceResultFromJSON(json: any): ConformanceResult {
    return ConformanceResultFromJSONTyped(json, false);
}

export function ConformanceResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConformanceResult {
    if (json == null) {
        return json;
    }
    return {

        'report_id': json['report_id'] == null ? undefined : json['report_id'],
        'level': json['level'] == null ? undefined : json['level'],
        'verdict': json['verdict'] == null ? undefined : json['verdict'],
        'gates': json['gates'] == null ? undefined : json['gates'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ConformanceResultToJSON(value?: ConformanceResult | null): any {
    if (value == null) {
        return value;
    }
    return {

        'report_id': value['report_id'],
        'level': value['level'],
        'verdict': value['verdict'],
        'gates': value['gates'],
        'failed': value['failed'],
        'details': value['details'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An effect submitted for governance evaluation
 * @export
 * @interface Effect
 */
export interface Effect {
    /**
     * Category of the effect (file_read, api_call, exec, etc.)
     * @type {string}
     * @memberof Effect
     */
    effect_type: string;
    /**
     * Unique identifier for this effect instance
     * @type {string}
     * @memberof Effect
     */
    effect_id: string;
    /**
     * Effect-specific parameters
     * @type {{ [key: string]: any; }}
     * @memberof Effect
     */
    params: { [key: string]: any; };
    /**
     * Optional budget to charge against
     * @type {string}
     * @memberof Effect
     */
    budget_id?: string;
}

/**
 * Check if a given object implements the Effect interface.
 */
export function instanceOfEffect(value: object): boolean {
    if (!('effect_type' in value)) return false;
    if (!('effect_id' in value)) return false;
    if (!('params' in value)) return false;
    return true;
}

export function EffectFromJSON(json: any): Effect {
    return EffectFromJSONTyped(json, false);
}

export function EffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Effect {
    if (json == null) {
        return json;
    }
    return {

        'effect_type': json['effect_type'],
        'effect_id': json['effect_id'],
        'params': json['params'],
        'budget_id': json['budget_id'] == null ? undefined : json['budget_id'],
    };
}

export function EffectToJSON(value?: Effect | null): any {
    if (value == null) {
        return value;
    }
    return {

        'effect_type': value['effect_type'],
        'effect_id': value['effect_id'],
        'params': value['params'],
        'budget_id': value['budget_id'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The boundary contract for submitting effects to the kernel
 * @export
 * @interface EffectBoundary
 */
export interface EffectBoundary {
    /**
     *
     * @type {Effect}
     * @memberof EffectBoundary
     */
    effect: Effect;
    /**
     * Agent/user identity (e.g. agent:analyst)
     * @type {string}
     * @memberof EffectBoundary
     */
    principal: string;
    /**
     * Additional context (jurisdiction, industry, budget state)
     * @type {{ [key: string]: any; }}
     * @memberof EffectBoundary
     */
    context?: { [key: string]: any; };
}

/**
 * Check if a given object implements the EffectBoundary interface.
 */
export function instanceOfEffectBoundary(value: object): boolean {
    if (!('effect' in value)) return false;
    if (!('principal' in value)) return false;
    return true;
}

export function EffectBoundaryFromJSON(json: any): EffectBoundary {
    return EffectBoundaryFromJSONTyped(json, false);
}

export function EffectBoundaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectBoundary {
    if (json == null) {
        return json;
    }
    return {

        'effect': EffectFromJSON(json['effect']),
        'principal': json['principal'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function EffectBoundaryToJSON(value?: EffectBoundary | null): any {
    if (value == null) {
        return value;
    }
    return {

        'effect': EffectToJSON(value['effect']),
        'principal': value['principal'],
        'context': value['context'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ExportRequest
 */
export interface ExportRequest {
    /**
     * Session to export (omit for all)
     * @type {string}
     * @memberof ExportRequest
     */
    session_id?: string;
    /**
     *
     * @type {string}
     * @memberof ExportRequest
     */
    format?: ExportRequestFormatEnum;
}


/**
 * @export
 */
export const ExportRequestFormatEnum = {
    TarGz: 'tar.gz'
} as const;
export type ExportRequestFormatEnum = typeof ExportRequestFormatEnum[keyof typeof ExportRequestFormatEnum];


/**
 * Check if a given object implements the ExportRequest interface.
 */
export function instanceOfExportRequest(value: object): boolean {
    return true;
}

export function ExportRequestFromJSON(json: any): ExportRequest {
    return ExportRequestFromJSONTyped(json, false);
}

export function ExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportRequest {
    if (json == null) {
        return json;
    }
    return {

        'session_id': json['session_id'] == null ? undefined : json['session_id'],
        'format': json['format'] == null ? undefined : json['format'],
    };
}

export function ExportRequestToJSON(value?: ExportRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'session_id': value['session_id'],
        'format': value['format'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PDP decision for an effect
 * @export
 * @interface GovernanceDecision
 */
export interface GovernanceDecision {
    /**
     *
     * @type {string}
     * @memberof GovernanceDecision
     */
    decision_id: string;
    /**
     *
     * @type {string}
     * @memberof GovernanceDecision
     */
    effect_id: string;
    /**
     *
     * @type {string}
     * @memberof GovernanceDecision
     */
    verdict: GovernanceDecisionVerdictEnum;
    /**
     * Null for ALLOW. Registered code from reason-codes-v1.json for DENY/ESCALATE.
     * @type {string}
     * @memberof GovernanceDecision
     */
    reason_code?: string;
    /**
     *
     * @type {Receipt}
     * @memberof GovernanceDecision
     */
    receipt?: Receipt;
    /**
     * Names of policy bundles active during evaluation
     * @type {Array<string>}
     * @memberof GovernanceDecision
     */
    active_packs?: Array<string>;
}


/**
 * @export
 */
export const GovernanceDecisionVerdictEnum = {
    Allow: 'ALLOW',
    Deny: 'DENY',
    Escalate: 'ESCALATE'
} as const;
export type GovernanceDecisionVerdictEnum = typeof GovernanceDecisionVerdictEnum[keyof typeof GovernanceDecisionVerdictEnum];


/**
 * Check if a given object implements the GovernanceDecision interface.
 */
export function instanceOfGovernanceDecision(value: object): boolean {
    if (!('decision_id' in value)) return false;
    if (!('effect_id' in value)) return false;
    if (!('verdict' in value)) return false;
    return true;
}

export function GovernanceDecisionFromJSON(json: any): GovernanceDecision {
    return GovernanceDecisionFromJSONTyped(json, false);
}

export function GovernanceDecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GovernanceDecision {
    if (json == null) {
        return json;
    }
    return {

        'decision_id': json['decision_id'],
        'effect_id': json['effect_id'],
        'verdict': json['verdict'],
        'reason_code': json['reason_code'] == null ? undefined : json['reason_code'],
        'receipt': json['receipt'] == null ? undefined : ReceiptFromJSON(json['receipt']),
        'active_packs': json['active_packs'] == null ? undefined : json['active_packs'],
    };
}

export function GovernanceDecisionToJSON(value?: GovernanceDecision | null): any {
    if (value == null) {
        return value;
    }
    return {

        'decision_id': value['decision_id'],
        'effect_id': value['effect_id'],
        'verdict': value['verdict'],
        'reason_code': value['reason_code'],
        'receipt': ReceiptToJSON(value['receipt']),
        'active_packs': value['active_packs'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface HealthCheck200Response
 */
export interface HealthCheck200Response {
    /**
     *
     * @type {string}
     * @memberof HealthCheck200Response
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof HealthCheck200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the HealthCheck200Response interface.
 */
export function instanceOfHealthCheck200Response(value: object): boolean {
    return true;
}

export function HealthCheck200ResponseFromJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseFromJSONTyped(json, false);
}

export function HealthCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck200Response {
    if (json == null) {
        return json;
    }
    return {

        'status': json['status'] == null ? undefined : json['status'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function HealthCheck200ResponseToJSON(value?: HealthCheck200Response | null): any {
    if (value == null) {
        return value;
    }
    return {

        'status': value['status'],
        'version': value['version'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface HelmError
 */
export interface HelmError {
    /**
     *
     * @type {HelmErrorError}
     * @memberof HelmError
     */
    error: HelmErrorError;
}

/**
 * Check if a given object implements the HelmError interface.
 */
export function instanceOfHelmError(value: object): boolean {
    if (!('error' in value)) return false;
    return true;
}

export function HelmErrorFromJSON(json: any): HelmError {
    return HelmErrorFromJSONTyped(json, false);
}

export function HelmErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelmError {
    if (json == null) {
        return json;
    }
    return {

        'error': HelmErrorErrorFromJSON(json['error']),
    };
}

export function HelmErrorToJSON(value?: HelmError | null): any {
    if (value == null) {
        return value;
    }
    return {

        'error': HelmErrorErrorToJSON(value['error']),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface HelmErrorError
 */
export interface HelmErrorError {
    /**
     * Human-readable error message
     * @type {string}
     * @memberof HelmErrorError
     */
    message: string;
    /**
     *
     * @type {string}
     * @memberof HelmErrorError
     */
    type: HelmErrorErrorTypeEnum;
    /**
     * Machine-readable error code
     * @type {string}
     * @memberof HelmErrorError
     */
    code: string;
    /**
     * HELM-specific reason code
     * @type {string}
     * @memberof HelmErrorError
     */
    reason_code: HelmErrorErrorReasonCodeEnum;
    /**
     * Additional error context
     * @type {{ [key: string]: any; }}
     * @memberof HelmErrorError
     */
    details?: { [key: string]: any; };
}


/**
 * @export
 */
export const HelmErrorErrorTypeEnum = {
    InvalidRequest: 'invalid_request',
    AuthenticationError: 'authentication_error',
    PermissionDenied: 'permission_denied',
    NotFound: 'not_found',
    InternalError: 'internal_error'
} as const;
export type HelmErrorErrorTypeEnum = typeof HelmErrorErrorTypeEnum[keyof typeof HelmErrorErrorTypeEnum];

/**
 * @export
 */
export const HelmErrorErrorReasonCodeEnum = {
    DenyToolNotFound: 'DENY_TOOL_NOT_FOUND',
    DenySchemaMismatch: 'DENY_SCHEMA_MISMATCH',
    DenyOutputDrift: 'DENY_OUTPUT_DRIFT',
    DenyBudgetExceeded: 'DENY_BUDGET_EXCEEDED',
    DenyApprovalRequired: 'DENY_APPROVAL_REQUIRED',
    DenyApprovalTimeout: 'DENY_APPROVAL_TIMEOUT',
    DenySandboxTrap: 'DENY_SANDBOX_TRAP',
    DenyGasExhaustion: 'DENY_GAS_EXHAUSTION',
    DenyTimeLimit: 'DENY_TIME_LIMIT',
    DenyMemoryLimit: 'DENY_MEMORY_LIMIT',
    DenyPolicyViolation: 'DENY_POLICY_VIOLATION',
    DenyTrustKeyRevoked: 'DENY_TRUST_KEY_REVOKED',
    DenyIdempotencyDuplicate: 'DENY_IDEMPOTENCY_DUPLICATE',
    ErrorInternal: 'ERROR_INTERNAL'
} as const;
export type HelmErrorErrorReasonCodeEnum = typeof HelmErrorErrorReasonCodeEnum[keyof typeof HelmErrorErrorReasonCodeEnum];


/**
 * Check if a given object implements the HelmErrorError interface.
 */
export function instanceOfHelmErrorError(value: object): boolean {
    if (!('message' in value)) return false;
    if (!('type' in value)) return false;
    if (!('code' in value)) return false;
    if (!('reason_code' in value)) return false;
    return true;
}

export function HelmErrorErrorFromJSON(json: any): HelmErrorError {
    return HelmErrorErrorFromJSONTyped(json, false);
}

export function HelmErrorErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelmErrorError {
    if (json == null) {
        return json;
    }
    return {

        'message': json['message'],
        'type': json['type'],
        'code': json['code'],
        'reason_code': json['reason_code'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function HelmErrorErrorToJSON(value?: HelmErrorError | null): any {
    if (value == null) {
        return value;
    }
    return {

        'message': value['message'],
        'type': value['type'],
        'code': value['code'],
        'reason_code': value['reason_code'],
        'details': value['details'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MCPCapabilityManifest
 */
export interface MCPCapabilityManifest {
    /**
     *
     * @type {string}
     * @memberof MCPCapabilityManifest
     */
    server_name?: string;
    /**
     *
     * @type {string}
     * @memberof MCPCapabilityManifest
     */
    version?: string;
    /**
     *
     * @type {string}
     * @memberof MCPCapabilityManifest
     */
    governance?: string;
    /**
     *
     * @type {Array<MCPToolRef>}
     * @memberof MCPCapabilityManifest
     */
    tools?: Array<MCPToolRef>;
}

/**
 * Check if a given object implements the MCPCapabilityManifest interface.
 */
export function instanceOfMCPCapabilityManifest(value: object): boolean {
    return true;
}

export function MCPCapabilityManifestFromJSON(json: any): MCPCapabilityManifest {
    return MCPCapabilityManifestFromJSONTyped(json, false);
}

export function MCPCapabilityManifestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPCapabilityManifest {
    if (json == null) {
        return json;
    }
    return {

        'server_name': json['server_name'] == null ? undefined : json['server_name'],
        'version': json['version'] == null ? undefined : json['version'],
        'governance': json['governance'] == null ? undefined : json['governance'],
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(MCPToolRefFromJSON)),
    };
}

export function MCPCapabilityManifestToJSON(value?: MCPCapabilityManifest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'server_name': value['server_name'],
        'version': value['version'],
        'governance': value['governance'],
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(MCPToolRefToJSON)),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MCPJSONRPCError
 */
export interface MCPJSONRPCError {
    /**
     *
     * @type {number}
     * @memberof MCPJSONRPCError
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof MCPJSONRPCError
     */
    message?: string;
}

/**
 * Check if a given object implements the MCPJSONRPCError interface.
 */
export function instanceOfMCPJSONRPCError(value: object): boolean {
    return true;
}

export function MCPJSONRPCErrorFromJSON(json: any): MCPJSONRPCError {
    return MCPJSONRPCErrorFromJSONTyped(json, false);
}

export function MCPJSONRPCErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPJSONRPCError {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function MCPJSONRPCErrorToJSON(value?: MCPJSONRPCError | null): any {
    if (value == null) {
        return value;
    }
    return {

        'code': value['code'],
        'message': value['message'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MCPJSONRPCRequest
 */
export interface MCPJSONRPCRequest {
    /**
     *
     * @type {string}
     * @memberof MCPJSONRPCRequest
     */
    jsonrpc: MCPJSONRPCRequestJsonrpcEnum;
    /**
     *
     * @type {MCPJSONRPCRequestId}
     * @memberof MCPJSONRPCRequest
     */
    id?: MCPJSONRPCRequestId;
    /**
     *
     * @type {string}
     * @memberof MCPJSONRPCRequest
     */
    method: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof MCPJSONRPCRequest
     */
    params?: { [key: string]: any; };
}


/**
 * @export
 */
export const MCPJSONRPCRequestJsonrpcEnum = {
    _20: '2.0'
} as const;
export type MCPJSONRPCRequestJsonrpcEnum = typeof MCPJSONRPCRequestJsonrpcEnum[keyof typeof MCPJSONRPCRequestJsonrpcEnum];


/**
 * Check if a given object implements the MCPJSONRPCRequest interface.
 */
export function instanceOfMCPJSONRPCRequest(value: object): boolean {
    if (!('jsonrpc' in value)) return false;
    if (!('method' in value)) return false;
    return true;
}

export function MCPJSONRPCRequestFromJSON(json: any): MCPJSONRPCRequest {
    return MCPJSONRPCRequestFromJSONTyped(json, false);
}

export function MCPJSONRPCRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPJSONRPCRequest {
    if (json == null) {
        return json;
    }
    return {

        'jsonrpc': json['jsonrpc'],
        'id': json['id'] == null ? undefined : MCPJSONRPCRequestIdFromJSON(json['id']),
        'method': json['method'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function MCPJSONRPCRequestToJSON(value?: MCPJSONRPCRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'jsonrpc': value['jsonrpc'],
        'id': MCPJSONRPCRequestIdToJSON(value['id']),
        'method': value['method'],
        'params': value['params'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type MCPJSONRPCRequestId
 * Request identifier. Omit for notifications.
 * @export
 */
export type MCPJSONRPCRequestId = number | string;

export function MCPJSONRPCRequestIdFromJSON(json: any): MCPJSONRPCRequestId {
    return MCPJSONRPCRequestIdFromJSONTyped(json, false);
}

export function MCPJSONRPCRequestIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPJSONRPCRequestId {
    if (json == null) {
        return json;
    }
    return json;
}

export function MCPJSONRPCRequestIdToJSON(value?: MCPJSONRPCRequestId | null): any {
    if (value == null) {
        return value;
    }

    return value;
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MCPJSONRPCResponse
 */
export interface MCPJSONRPCResponse {
    /**
     *
     * @type {string}
     * @memberof MCPJSONRPCResponse
     */
    jsonrpc?: MCPJSONRPCResponseJsonrpcEnum;
    /**
     *
     * @type {MCPJSONRPCResponseId}
     * @memberof MCPJSONRPCResponse
     */
    id?: MCPJSONRPCResponseId;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof MCPJSONRPCResponse
     */
    result?: { [key: string]: any; };
    /**
     *
     * @type {MCPJSONRPCError}
     * @memberof MCPJSONRPCResponse
     */
    error?: MCPJSONRPCError;
}


/**
 * @export
 */
export const MCPJSONRPCResponseJsonrpcEnum = {
    _20: '2.0'
} as const;
export type MCPJSONRPCResponseJsonrpcEnum = typeof MCPJSONRPCResponseJsonrpcEnum[keyof typeof MCPJSONRPCResponseJsonrpcEnum];


/**
 * Check if a given object implements the MCPJSONRPCResponse interface.
 */
export function instanceOfMCPJSONRPCResponse(value: object): boolean {
    return true;
}

export function MCPJSONRPCResponseFromJSON(json: any): MCPJSONRPCResponse {
    return MCPJSONRPCResponseFromJSONTyped(json, false);
}

export function MCPJSONRPCResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPJSONRPCResponse {
    if (json == null) {
        return json;
    }
    return {

        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : MCPJSONRPCResponseIdFromJSON(json['id']),
        'result': json['result'] == null ? undefined : json['result'],
        'error': json['error'] == null ? undefined : MCPJSONRPCErrorFromJSON(json['error']),
    };
}

export function MCPJSONRPCResponseToJSON(value?: MCPJSONRPCResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'jsonrpc': value['jsonrpc'],
        'id': MCPJSONRPCResponseIdToJSON(value['id']),
        'result': value['result'],
        'error': MCPJSONRPCErrorToJSON(value['error']),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type MCPJSONRPCResponseId
 *
 * @export
 */
export type MCPJSONRPCResponseId = number | string;

export function MCPJSONRPCResponseIdFromJSON(json: any): MCPJSONRPCResponseId {
    return MCPJSONRPCResponseIdFromJSONTyped(json, false);
}

export function MCPJSONRPCResponseIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPJSONRPCResponseId {
    if (json == null) {
        return json;
    }
    return json;
}

export function MCPJSONRPCResponseIdToJSON(value?: MCPJSONRPCResponseId | null): any {
    if (value == null) {
        return value;
    }

    return value;
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MCPProtectedResourceMetadata
 */
export interface MCPProtectedResourceMetadata {
    /**
     *
     * @type {string}
     * @memberof MCPProtectedResourceMetadata
     */
    resource?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof MCPProtectedResourceMetadata
     */
    authorization_servers?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof MCPProtectedResourceMetadata
     */
    scopes_supported?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof MCPProtectedResourceMetadata
     */
    bearer_methods_supported?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof MCPProtectedResourceMetadata
     */
    resource_documentation?: string;
}

/**
 * Check if a given object implements the MCPProtectedResourceMetadata interface.
 */
export function instanceOfMCPProtectedResourceMetadata(value: object): boolean {
    return true;
}

export function MCPProtectedResourceMetadataFromJSON(json: any): MCPProtectedResourceMetadata {
    return MCPProtectedResourceMetadataFromJSONTyped(json, false);
}

export function MCPProtectedResourceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPProtectedResourceMetadata {
    if (json == null) {
        return json;
    }
    return {

        'resource': json['resource'] == null ? undefined : json['resource'],
        'authorization_servers': json['authorization_servers'] == null ? undefined : json['authorization_servers'],
        'scopes_supported': json['scopes_supported'] == null ? undefined : json['scopes_supported'],
        'bearer_methods_supported': json['bearer_methods_supported'] == null ? undefined : json['bearer_methods_supported'],
        'resource_documentation': json['resource_documentation'] == null ? undefined : json['resource_documentation'],
    };
}

export function MCPProtectedResourceMetadataToJSON(value?: MCPProtectedResourceMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {

        'resource': value['resource'],
        'authorization_servers': value['authorization_servers'],
        'scopes_supported': value['scopes_supported'],
        'bearer_methods_supported': value['bearer_methods_supported'],
        'resource_documentation': value['resource_documentation'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MCPRemoteDiscovery
 */
export interface MCPRemoteDiscovery {
    /**
     *
     * @type {string}
     * @memberof MCPRemoteDiscovery
     */
    server_name?: string;
    /**
     *
     * @type {string}
     * @memberof MCPRemoteDiscovery
     */
    version?: string;
    /**
     *
     * @type {string}
     * @memberof MCPRemoteDiscovery
     */
    capabilities_url?: string;
    /**
     *
     * @type {string}
     * @memberof MCPRemoteDiscovery
     */
    execute_url?: string;
    /**
     *
     * @type {string}
     * @memberof MCPRemoteDiscovery
     */
    mcp_endpoint?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof MCPRemoteDiscovery
     */
    supported_protocol_versions?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof MCPRemoteDiscovery
     */
    auth_mode?: string;
    /**
     *
     * @type {string}
     * @memberof MCPRemoteDiscovery
     */
    governance?: string;
}

/**
 * Check if a given object implements the MCPRemoteDiscovery interface.
 */
export function instanceOfMCPRemoteDiscovery(value: object): boolean {
    return true;
}

export function MCPRemoteDiscoveryFromJSON(json: any): MCPRemoteDiscovery {
    return MCPRemoteDiscoveryFromJSONTyped(json, false);
}

export function MCPRemoteDiscoveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPRemoteDiscovery {
    if (json == null) {
        return json;
    }
    return {

        'server_name': json['server_name'] == null ? undefined : json['server_name'],
        'version': json['version'] == null ? undefined : json['version'],
        'capabilities_url': json['capabilities_url'] == null ? undefined : json['capabilities_url'],
        'execute_url': json['execute_url'] == null ? undefined : json['execute_url'],
        'mcp_endpoint': json['mcp_endpoint'] == null ? undefined : json['mcp_endpoint'],
        'supported_protocol_versions': json['supported_protocol_versions'] == null ? undefined : json['supported_protocol_versions'],
        'auth_mode': json['auth_mode'] == null ? undefined : json['auth_mode'],
        'governance': json['governance'] == null ? undefined : json['governance'],
    };
}

export function MCPRemoteDiscoveryToJSON(value?: MCPRemoteDiscovery | null): any {
    if (value == null) {
        return value;
    }
    return {

        'server_name': value['server_name'],
        'version': value['version'],
        'capabilities_url': value['capabilities_url'],
        'execute_url': value['execute_url'],
        'mcp_endpoint': value['mcp_endpoint'],
        'supported_protocol_versions': value['supported_protocol_versions'],
        'auth_mode': value['auth_mode'],
        'governance': value['governance'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MCPToolCallRequest
 */
export interface MCPToolCallRequest {
    /**
     *
     * @type {string}
     * @memberof MCPToolCallRequest
     */
    method: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof MCPToolCallRequest
     */
    params?: { [key: string]: any; };
}

/**
 * Check if a given object implements the MCPToolCallRequest interface.
 */
export function instanceOfMCPToolCallRequest(value: object): boolean {
    if (!('method' in value)) return false;
    return true;
}

export function MCPToolCallRequestFromJSON(json: any): MCPToolCallRequest {
    return MCPToolCallRequestFromJSONTyped(json, false);
}

export function MCPToolCallRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPToolCallRequest {
    if (json == null) {
        return json;
    }
    return {

        'method': json['method'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function MCPToolCallRequestToJSON(value?: MCPToolCallRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'method': value['method'],
        'params': value['params'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MCPToolCallResponse
 */
export interface MCPToolCallResponse {
    /**
     *
     * @type {MCPToolCallResponseResult}
     * @memberof MCPToolCallResponse
     */
    result?: MCPToolCallResponseResult;
    /**
     *
     * @type {string}
     * @memberof MCPToolCallResponse
     */
    error?: string;
    /**
     *
     * @type {string}
     * @memberof MCPToolCallResponse
     */
    reason_code?: string;
    /**
     *
     * @type {string}
     * @memberof MCPToolCallResponse
     */
    args_hash?: string;
    /**
     *
     * @type {string}
     * @memberof MCPToolCallResponse
     */
    proofgraph_node?: string;
    /**
     *
     * @type {string}
     * @memberof MCPToolCallResponse
     */
    receipt_id?: string;
}

/**
 * Check if a given object implements the MCPToolCallResponse interface.
 */
export function instanceOfMCPToolCallResponse(value: object): boolean {
    return true;
}

export function MCPToolCallResponseFromJSON(json: any): MCPToolCallResponse {
    return MCPToolCallResponseFromJSONTyped(json, false);
}

export function MCPToolCallResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPToolCallResponse {
    if (json == null) {
        return json;
    }
    return {

        'result': json['result'] == null ? undefined : MCPToolCallResponseResultFromJSON(json['result']),
        'error': json['error'] == null ? undefined : json['error'],
        'reason_code': json['reason_code'] == null ? undefined : json['reason_code'],
        'args_hash': json['args_hash'] == null ? undefined : json['args_hash'],
        'proofgraph_node': json['proofgraph_node'] == null ? undefined : json['proofgraph_node'],
        'receipt_id': json['receipt_id'] == null ? undefined : json['receipt_id'],
    };
}

export function MCPToolCallResponseToJSON(value?: MCPToolCallResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'result': MCPToolCallResponseResultToJSON(value['result']),
        'error': value['error'],
        'reason_code': value['reason_code'],
        'args_hash': value['args_hash'],
        'proofgraph_node': value['proofgraph_node'],
        'receipt_id': value['receipt_id'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type MCPToolCallResponseResult
 * Tool output payload
 * @export
 */
export type MCPToolCallResponseResult = string | { [key: string]: any; };

export function MCPToolCallResponseResultFromJSON(json: any): MCPToolCallResponseResult {
    return MCPToolCallResponseResultFromJSONTyped(json, false);
}

export function MCPToolCallResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPToolCallResponseResult {
    if (json == null) {
        return json;
    }
    return json;
}

export function MCPToolCallResponseResultToJSON(value?: MCPToolCallResponseResult | null): any {
    if (value == null) {
        return value;
    }

    return value;
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MCPToolRef
 */
export interface MCPToolRef {
    /**
     *
     * @type {string}
     * @memberof MCPToolRef
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof MCPToolRef
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof MCPToolRef
     */
    server_id?: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof MCPToolRef
     */
    schema?: { [key: string]: any; };
}

/**
 * Check if a given object implements the MCPToolRef interface.
 */
export function instanceOfMCPToolRef(value: object): boolean {
    return true;
}

export function MCPToolRefFromJSON(json: any): MCPToolRef {
    return MCPToolRefFromJSONTyped(json, false);
}

export function MCPToolRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPToolRef {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'server_id': json['server_id'] == null ? undefined : json['server_id'],
        'schema': json['schema'] == null ? undefined : json['schema'],
    };
}

export function MCPToolRefToJSON(value?: MCPToolRef | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'description': value['description'],
        'server_id': value['server_id'],
        'schema': value['schema'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to the Policy Decision Point
 * @export
 * @interface PDPRequest
 */
export interface PDPRequest {
    /**
     *
     * @type {EffectBoundary}
     * @memberof PDPRequest
     */
    boundary: EffectBoundary;
}

/**
 * Check if a given object implements the PDPRequest interface.
 */
export function instanceOfPDPRequest(value: object): boolean {
    if (!('boundary' in value)) return false;
    return true;
}

export function PDPRequestFromJSON(json: any): PDPRequest {
    return PDPRequestFromJSONTyped(json, false);
}

export function PDPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PDPRequest {
    if (json == null) {
        return json;
    }
    return {

        'boundary': EffectBoundaryFromJSON(json['boundary']),
    };
}

export function PDPRequestToJSON(value?: PDPRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'boundary': EffectBoundaryToJSON(value['boundary']),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response from the Policy Decision Point
 * @export
 * @interface PDPResponse
 */
export interface PDPResponse {
    /**
     *
     * @type {GovernanceDecision}
     * @memberof PDPResponse
     */
    decision: GovernanceDecision;
}

/**
 * Check if a given object implements the PDPResponse interface.
 */
export function instanceOfPDPResponse(value: object): boolean {
    if (!('decision' in value)) return false;
    return true;
}

export function PDPResponseFromJSON(json: any): PDPResponse {
    return PDPResponseFromJSONTyped(json, false);
}

export function PDPResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PDPResponse {
    if (json == null) {
        return json;
    }
    return {

        'decision': GovernanceDecisionFromJSON(json['decision']),
    };
}

export function PDPResponseToJSON(value?: PDPResponse | null): any {
    if (value == null) {
        return value;
    }
    return {

        'decision': GovernanceDecisionToJSON(value['decision']),
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A loaded policy bundle (jurisdiction, industry, or business pack)
 * @export
 * @interface PolicyBundle
 */
export interface PolicyBundle {
    /**
     *
     * @type {string}
     * @memberof PolicyBundle
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof PolicyBundle
     */
    version: string;
    /**
     * SHA-256 of the bundle contents
     * @type {string}
     * @memberof PolicyBundle
     */
    content_hash: string;
    /**
     * Ed25519 signature over content_hash
     * @type {string}
     * @memberof PolicyBundle
     */
    signature?: string;
    /**
     *
     * @type {string}
     * @memberof PolicyBundle
     */
    pack_type?: PolicyBundlePackTypeEnum;
}


/**
 * @export
 */
export const PolicyBundlePackTypeEnum = {
    Jurisdiction: 'jurisdiction',
    Industry: 'industry',
    Business: 'business',
    Custom: 'custom'
} as const;
export type PolicyBundlePackTypeEnum = typeof PolicyBundlePackTypeEnum[keyof typeof PolicyBundlePackTypeEnum];


/**
 * Check if a given object implements the PolicyBundle interface.
 */
export function instanceOfPolicyBundle(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('version' in value)) return false;
    if (!('content_hash' in value)) return false;
    return true;
}

export function PolicyBundleFromJSON(json: any): PolicyBundle {
    return PolicyBundleFromJSONTyped(json, false);
}

export function PolicyBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyBundle {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'version': json['version'],
        'content_hash': json['content_hash'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'pack_type': json['pack_type'] == null ? undefined : json['pack_type'],
    };
}

export function PolicyBundleToJSON(value?: PolicyBundle | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'version': value['version'],
        'content_hash': value['content_hash'],
        'signature': value['signature'],
        'pack_type': value['pack_type'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Receipt
 */
export interface Receipt {
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    receipt_id?: string;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    decision_id?: string;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    effect_id?: string;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    status?: ReceiptStatusEnum;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    reason_code?: string;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    output_hash?: string;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    blob_hash?: string;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    prev_hash?: string;
    /**
     *
     * @type {number}
     * @memberof Receipt
     */
    lamport_clock?: number;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    signature?: string;
    /**
     *
     * @type {Date}
     * @memberof Receipt
     */
    timestamp?: Date;
    /**
     *
     * @type {string}
     * @memberof Receipt
     */
    principal?: string;
}


/**
 * @export
 */
export const ReceiptStatusEnum = {
    Approved: 'APPROVED',
    Denied: 'DENIED',
    Pending: 'PENDING'
} as const;
export type ReceiptStatusEnum = typeof ReceiptStatusEnum[keyof typeof ReceiptStatusEnum];


/**
 * Check if a given object implements the Receipt interface.
 */
export function instanceOfReceipt(value: object): boolean {
    return true;
}

export function ReceiptFromJSON(json: any): Receipt {
    return ReceiptFromJSONTyped(json, false);
}

export function ReceiptFromJSONTyped(json: any, ignoreDiscriminator: boolean): Receipt {
    if (json == null) {
        return json;
    }
    return {

        'receipt_id': json['receipt_id'] == null ? undefined : json['receipt_id'],
        'decision_id': json['decision_id'] == null ? undefined : json['decision_id'],
        'effect_id': json['effect_id'] == null ? undefined : json['effect_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'reason_code': json['reason_code'] == null ? undefined : json['reason_code'],
        'output_hash': json['output_hash'] == null ? undefined : json['output_hash'],
        'blob_hash': json['blob_hash'] == null ? undefined : json['blob_hash'],
        'prev_hash': json['prev_hash'] == null ? undefined : json['prev_hash'],
        'lamport_clock': json['lamport_clock'] == null ? undefined : json['lamport_clock'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'principal': json['principal'] == null ? undefined : json['principal'],
    };
}

export function ReceiptToJSON(value?: Receipt | null): any {
    if (value == null) {
        return value;
    }
    return {

        'receipt_id': value['receipt_id'],
        'decision_id': value['decision_id'],
        'effect_id': value['effect_id'],
        'status': value['status'],
        'reason_code': value['reason_code'],
        'output_hash': value['output_hash'],
        'blob_hash': value['blob_hash'],
        'prev_hash': value['prev_hash'],
        'lamport_clock': value['lamport_clock'],
        'signature': value['signature'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'principal': value['principal'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RevokeTrustKeyRequest
 */
export interface RevokeTrustKeyRequest {
    /**
     *
     * @type {string}
     * @memberof RevokeTrustKeyRequest
     */
    tenant_id: string;
    /**
     *
     * @type {string}
     * @memberof RevokeTrustKeyRequest
     */
    key_id: string;
}

/**
 * Check if a given object implements the RevokeTrustKeyRequest interface.
 */
export function instanceOfRevokeTrustKeyRequest(value: object): boolean {
    if (!('tenant_id' in value)) return false;
    if (!('key_id' in value)) return false;
    return true;
}

export function RevokeTrustKeyRequestFromJSON(json: any): RevokeTrustKeyRequest {
    return RevokeTrustKeyRequestFromJSONTyped(json, false);
}

export function RevokeTrustKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeTrustKeyRequest {
    if (json == null) {
        return json;
    }
    return {

        'tenant_id': json['tenant_id'],
        'key_id': json['key_id'],
    };
}

export function RevokeTrustKeyRequestToJSON(value?: RevokeTrustKeyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {

        'tenant_id': value['tenant_id'],
        'key_id': value['key_id'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Session
 */
export interface Session {
    /**
     *
     * @type {string}
     * @memberof Session
     */
    session_id?: string;
    /**
     *
     * @type {Date}
     * @memberof Session
     */
    created_at?: Date;
    /**
     *
     * @type {number}
     * @memberof Session
     */
    receipt_count?: number;
    /**
     *
     * @type {number}
     * @memberof Session
     */
    last_lamport_clock?: number;
}

/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): boolean {
    return true;
}

export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if (json == null) {
        return json;
    }
    return {

        'session_id': json['session_id'] == null ? undefined : json['session_id'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'receipt_count': json['receipt_count'] == null ? undefined : json['receipt_count'],
        'last_lamport_clock': json['last_lamport_clock'] == null ? undefined : json['last_lamport_clock'],
    };
}

export function SessionToJSON(value?: Session | null): any {
    if (value == null) {
        return value;
    }
    return {

        'session_id': value['session_id'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'receipt_count': value['receipt_count'],
        'last_lamport_clock': value['last_lamport_clock'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface VerificationResult
 */
export interface VerificationResult {
    /**
     *
     * @type {string}
     * @memberof VerificationResult
     */
    verdict?: VerificationResultVerdictEnum;
    /**
     *
     * @type {VerificationResultChecks}
     * @memberof VerificationResult
     */
    checks?: VerificationResultChecks;
    /**
     *
     * @type {VerificationResultRoots}
     * @memberof VerificationResult
     */
    roots?: VerificationResultRoots;
    /**
     *
     * @type {Array<string>}
     * @memberof VerificationResult
     */
    errors?: Array<string>;
}


/**
 * @export
 */
export const VerificationResultVerdictEnum = {
    Pass: 'PASS',
    Fail: 'FAIL'
} as const;
export type VerificationResultVerdictEnum = typeof VerificationResultVerdictEnum[keyof typeof VerificationResultVerdictEnum];


/**
 * Check if a given object implements the VerificationResult interface.
 */
export function instanceOfVerificationResult(value: object): boolean {
    return true;
}

export function VerificationResultFromJSON(json: any): VerificationResult {
    return VerificationResultFromJSONTyped(json, false);
}

export function VerificationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationResult {
    if (json == null) {
        return json;
    }
    return {

        'verdict': json['verdict'] == null ? undefined : json['verdict'],
        'checks': json['checks'] == null ? undefined : VerificationResultChecksFromJSON(json['checks']),
        'roots': json['roots'] == null ? undefined : VerificationResultRootsFromJSON(json['roots']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function VerificationResultToJSON(value?: VerificationResult | null): any {
    if (value == null) {
        return value;
    }
    return {

        'verdict': value['verdict'],
        'checks': VerificationResultChecksToJSON(value['checks']),
        'roots': VerificationResultRootsToJSON(value['roots']),
        'errors': value['errors'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VerificationResultChecks
 */
export interface VerificationResultChecks {
    /**
     *
     * @type {string}
     * @memberof VerificationResultChecks
     */
    signatures?: VerificationResultChecksSignaturesEnum;
    /**
     *
     * @type {string}
     * @memberof VerificationResultChecks
     */
    causal_chain?: VerificationResultChecksCausalChainEnum;
    /**
     *
     * @type {string}
     * @memberof VerificationResultChecks
     */
    policy_compliance?: VerificationResultChecksPolicyComplianceEnum;
}


/**
 * @export
 */
export const VerificationResultChecksSignaturesEnum = {
    Pass: 'PASS',
    Fail: 'FAIL'
} as const;
export type VerificationResultChecksSignaturesEnum = typeof VerificationResultChecksSignaturesEnum[keyof typeof VerificationResultChecksSignaturesEnum];

/**
 * @export
 */
export const VerificationResultChecksCausalChainEnum = {
    Pass: 'PASS',
    Fail: 'FAIL'
} as const;
export type VerificationResultChecksCausalChainEnum = typeof VerificationResultChecksCausalChainEnum[keyof typeof VerificationResultChecksCausalChainEnum];

/**
 * @export
 */
export const VerificationResultChecksPolicyComplianceEnum = {
    Pass: 'PASS',
    Fail: 'FAIL'
} as const;
export type VerificationResultChecksPolicyComplianceEnum = typeof VerificationResultChecksPolicyComplianceEnum[keyof typeof VerificationResultChecksPolicyComplianceEnum];


/**
 * Check if a given object implements the VerificationResultChecks interface.
 */
export function instanceOfVerificationResultChecks(value: object): boolean {
    return true;
}

export function VerificationResultChecksFromJSON(json: any): VerificationResultChecks {
    return VerificationResultChecksFromJSONTyped(json, false);
}

export function VerificationResultChecksFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationResultChecks {
    if (json == null) {
        return json;
    }
    return {

        'signatures': json['signatures'] == null ? undefined : json['signatures'],
        'causal_chain': json['causal_chain'] == null ? undefined : json['causal_chain'],
        'policy_compliance': json['policy_compliance'] == null ? undefined : json['policy_compliance'],
    };
}

export function VerificationResultChecksToJSON(value?: VerificationResultChecks | null): any {
    if (value == null) {
        return value;
    }
    return {

        'signatures': value['signatures'],
        'causal_chain': value['causal_chain'],
        'policy_compliance': value['policy_compliance'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VerificationResultRoots
 */
export interface VerificationResultRoots {
    /**
     *
     * @type {string}
     * @memberof VerificationResultRoots
     */
    manifest_root_hash?: string;
    /**
     *
     * @type {string}
     * @memberof VerificationResultRoots
     */
    merkle_root?: string;
    /**
     *
     * @type {number}
     * @memberof VerificationResultRoots
     */
    entry_count?: number;
}

/**
 * Check if a given object implements the VerificationResultRoots interface.
 */
export function instanceOfVerificationResultRoots(value: object): boolean {
    return true;
}

export function VerificationResultRootsFromJSON(json: any): VerificationResultRoots {
    return VerificationResultRootsFromJSONTyped(json, false);
}

export function VerificationResultRootsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationResultRoots {
    if (json == null) {
        return json;
    }
    return {

        'manifest_root_hash': json['manifest_root_hash'] == null ? undefined : json['manifest_root_hash'],
        'merkle_root': json['merkle_root'] == null ? undefined : json['merkle_root'],
        'entry_count': json['entry_count'] == null ? undefined : json['entry_count'],
    };
}

export function VerificationResultRootsToJSON(value?: VerificationResultRoots | null): any {
    if (value == null) {
        return value;
    }
    return {

        'manifest_root_hash': value['manifest_root_hash'],
        'merkle_root': value['merkle_root'],
        'entry_count': value['entry_count'],
    };
}

/* tslint:disable */
/* eslint-disable */
/**
 * HELM Kernel API
 * Deterministic execution kernel for AI tool calls. Drop-in OpenAI proxy + cryptographic receipts + offline-verifiable evidence packs.
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VersionInfo
 */
export interface VersionInfo {
    /**
     *
     * @type {string}
     * @memberof VersionInfo
     */
    version?: string;
    /**
     *
     * @type {string}
     * @memberof VersionInfo
     */
    commit?: string;
    /**
     *
     * @type {string}
     * @memberof VersionInfo
     */
    build_time?: string;
    /**
     *
     * @type {string}
     * @memberof VersionInfo
     */
    go_version?: string;
}

/**
 * Check if a given object implements the VersionInfo interface.
 */
export function instanceOfVersionInfo(value: object): boolean {
    return true;
}

export function VersionInfoFromJSON(json: any): VersionInfo {
    return VersionInfoFromJSONTyped(json, false);
}

export function VersionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionInfo {
    if (json == null) {
        return json;
    }
    return {

        'version': json['version'] == null ? undefined : json['version'],
        'commit': json['commit'] == null ? undefined : json['commit'],
        'build_time': json['build_time'] == null ? undefined : json['build_time'],
        'go_version': json['go_version'] == null ? undefined : json['go_version'],
    };
}

export function VersionInfoToJSON(value?: VersionInfo | null): any {
    if (value == null) {
        return value;
    }
    return {

        'version': value['version'],
        'commit': value['commit'],
        'build_time': value['build_time'],
        'go_version': value['go_version'],
    };
}


export type ReasonCode = HelmErrorErrorReasonCodeEnum;
