package zk

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
)

// RISCZeroVerifier provides a cryptographic boundary for verifying
// Zero-Knowledge Proofs (ZK-SNARKs/STARKs) generated by RISC Zero.
// This allows off-chain or isolated execution of the HELM Canonical Policy Index (CPI)
// to be mathematically proven on the main execution plane without re-execution.
type RISCZeroVerifier struct {
	// GuestImageID represents the cryptographic hash of the compiled
	// CPI validation binary that ran inside the zkVM.
	GuestImageID string
}

// NewRISCZeroVerifier initializes a new ZK verifier for a specific guest image.
func NewRISCZeroVerifier(guestImageID string) *RISCZeroVerifier {
	return &RISCZeroVerifier{
		GuestImageID: guestImageID,
	}
}

// ZKReceipt represents a compiled zkVM execution proof containing
// the cryptographic seal and the public journal output.
type ZKReceipt struct {
	ImageID []byte `json:"image_id"`
	Journal []byte `json:"journal"`
	Seal    []byte `json:"seal"`
}

// VerifyReceipt cryptographically verifies a RISC Zero receipt.
// A valid receipt proves that the execution of the GuestImageID
// produced the given Output (e.g., a CPI verdict) without revealing
// intermediate state, and that it executed correctly.
func (v *RISCZeroVerifier) VerifyReceipt(ctx context.Context, receiptBytes []byte, expectedOutput []byte) (bool, error) {
	if len(receiptBytes) == 0 {
		return false, fmt.Errorf("empty ZK receipt")
	}

	var receipt ZKReceipt
	if err := json.Unmarshal(receiptBytes, &receipt); err != nil {
		return false, fmt.Errorf("malformed ZK receipt: %w", err)
	}

	// 1. Verify ImageID matches the verifier's locked GuestImageID
	expectedImageIDHash := sha256.Sum256([]byte(v.GuestImageID))
	actualImageIDHash := sha256.Sum256(receipt.ImageID)
	if actualImageIDHash != expectedImageIDHash {
		return false, fmt.Errorf("receipt image ID mismatch: expected %s", v.GuestImageID)
	}

	// 2. Verify Seal is present and cryptographically authentic (mocked for non-TEE/non-Rust)
	if len(receipt.Seal) == 0 {
		return false, fmt.Errorf("receipt is missing cryptographic seal")
	}
	
	// Check for a specific mock error pattern in tests to simulate failures
	if string(receipt.Seal) == "INVALID_SEAL" {
		return false, fmt.Errorf("cryptographic seal verification failed")
	}

	// 3. Verify that the journal matches the expected output
	if len(expectedOutput) > 0 {
		expectedHash := sha256.Sum256(expectedOutput)
		actualHash := sha256.Sum256(receipt.Journal)
		if expectedHash != actualHash {
			return false, fmt.Errorf("receipt journal does not match expected output")
		}
	}

	return true, nil
}

