/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible chat completions
         * @description Drop-in replacement for OpenAI /v1/chat/completions.
         *     Tool calls are intercepted, schema-validated, and receipted.
         *     Response includes X-Helm-Receipt-ID, X-Helm-Output-Hash, X-Helm-Lamport-Clock headers.
         */
        post: operations["chatCompletions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kernel/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an approval for a pending intent
         * @description RFC-005 approval ceremony endpoint.
         *     Requires intent_hash, Ed25519 signature, and public key.
         *     Returns an approval receipt with causal chain linkage.
         */
        post: operations["approveIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate a governed intent and emit a receipt */
        post: operations["evaluateDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List durable receipts */
        get: operations["listReceipts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a receipt by ID */
        get: operations["getConsoleReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read HELM OSS Console bootstrap state
         * @description Consolidated read-only platform state used by the OSS Console shell.
         *     Values are derived from kernel services and local configuration.
         */
        get: operations["getConsoleBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/surfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Console surfaces and their backing source contracts */
        get: operations["listConsoleSurfaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/surfaces/{surface_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a wired Console surface state */
        get: operations["getConsoleSurface"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trust/keys/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a trusted signing key */
        post: operations["addTrustKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trust/keys/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a trusted signing key */
        post: operations["revokeTrustKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Open the MCP transport endpoint
         * @description Returns JSON discovery metadata by default.
         *     When `Accept: text/event-stream` is used, responds with an SSE primer event.
         */
        get: operations["getMCPTransport"];
        put?: never;
        /**
         * Send a JSON-RPC request to the MCP transport endpoint
         * @description Supports `initialize`, `notifications/initialized`, `ping`, `tools/list`, and `tools/call`.
         *     Protocol negotiation happens on `initialize`; later requests SHOULD include `MCP-Protocol-Version`.
         */
        post: operations["postMCPJSONRPC"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read protected-resource metadata for the MCP endpoint */
        get: operations["getMCPProtectedResourceMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proofgraph/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ProofGraph sessions */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proofgraph/sessions/{session_id}/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get receipts for a specific session */
        get: operations["getSessionReceipts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proofgraph/receipts/{receipt_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single receipt by hash */
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export an EvidencePack
         * @description Exports a deterministic .tar.gz containing all receipts, ProofGraph nodes, and metadata.
         *     Same content always produces same SHA-256.
         */
        post: operations["exportEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an EvidencePack
         * @description Verifies signatures, causal chain, and policy compliance.
         *     Works offline — no network calls made during verification.
         */
        post: operations["verifyEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replay/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay and verify execution from tapes */
        post: operations["replayVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conformance/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run conformance tests */
        post: operations["runConformance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conformance/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a conformance report by ID */
        get: operations["getConformanceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List governed MCP tools */
        get: operations["listMCPCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/v1/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a governed MCP tool call */
        post: operations["executeMCPTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version information */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HelmError: {
            error: {
                /** @description Human-readable error message */
                message: string;
                /** @enum {string} */
                type: "invalid_request" | "authentication_error" | "permission_denied" | "not_found" | "internal_error";
                /** @description Machine-readable error code */
                code: string;
                /**
                 * @description HELM-specific reason code
                 * @enum {string}
                 */
                reason_code: "DENY_TOOL_NOT_FOUND" | "DENY_SCHEMA_MISMATCH" | "DENY_OUTPUT_DRIFT" | "DENY_BUDGET_EXCEEDED" | "DENY_APPROVAL_REQUIRED" | "DENY_APPROVAL_TIMEOUT" | "DENY_SANDBOX_TRAP" | "DENY_GAS_EXHAUSTION" | "DENY_TIME_LIMIT" | "DENY_MEMORY_LIMIT" | "DENY_POLICY_VIOLATION" | "DENY_TRUST_KEY_REVOKED" | "DENY_IDEMPOTENCY_DUPLICATE" | "ERROR_INTERNAL";
                /** @description Additional error context */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ChatCompletionRequest: {
            model: string;
            messages: {
                /** @enum {string} */
                role: "system" | "user" | "assistant" | "tool";
                content: string;
                tool_call_id?: string;
            }[];
            tools?: {
                /** @enum {string} */
                type?: "function";
                function?: {
                    name?: string;
                    description?: string;
                    parameters?: Record<string, never>;
                };
            }[];
            temperature?: number;
            max_tokens?: number;
            /** @default false */
            stream: boolean;
        };
        ChatCompletionResponse: {
            id?: string;
            /** @default chat.completion */
            object: string;
            created?: number;
            model?: string;
            choices?: {
                index?: number;
                message?: {
                    role?: string;
                    content?: string | null;
                    tool_calls?: {
                        id?: string;
                        type?: string;
                        function?: {
                            name?: string;
                            arguments?: string;
                        };
                    }[];
                };
                finish_reason?: string;
            }[];
            usage?: {
                prompt_tokens?: number;
                completion_tokens?: number;
                total_tokens?: number;
            };
        };
        ApprovalRequest: {
            /** @description SHA-256 hash of the intent to approve */
            intent_hash: string;
            /** @description Base64-encoded Ed25519 signature */
            signature_b64: string;
            /** @description Base64-encoded Ed25519 public key */
            public_key_b64: string;
            /** @description Optional challenge/response for ceremony */
            challenge_response?: string;
        };
        AddTrustKeyRequest: {
            tenant_id: string;
            key_id: string;
            /** @description Hex-encoded Ed25519 public key */
            public_key: string;
        };
        RevokeTrustKeyRequest: {
            tenant_id: string;
            key_id: string;
        };
        Receipt: {
            receipt_id?: string;
            decision_id?: string;
            effect_id?: string;
            status?: string;
            reason_code?: string;
            output_hash?: string;
            blob_hash?: string;
            prev_hash?: string;
            lamport_clock?: number;
            signature?: string;
            /** Format: date-time */
            timestamp?: string;
            principal?: string;
            executor_id?: string;
            args_hash?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        ReceiptListResponse: {
            receipts?: components["schemas"]["Receipt"][];
            count?: number;
        };
        DecisionRequest: {
            principal?: string;
            action: string;
            resource: string;
            context?: {
                [key: string]: unknown;
            };
        };
        DecisionRecord: {
            id?: string;
            action?: string;
            resource?: string;
            verdict?: string;
            reason?: string;
            policy_version?: string;
            policy_decision_hash?: string;
            signature?: string;
        };
        ConsoleBootstrap: {
            version: components["schemas"]["VersionInfo"];
            workspace: {
                organization: string;
                project: string;
                environment: string;
                mode: string;
            };
            health: {
                kernel: string;
                policy: string;
                store: string;
                conformance: string;
            };
            counts: {
                receipts: number;
                pending_approvals: number;
                open_incidents: number;
                mcp_tools: number;
            };
            receipts: components["schemas"]["Receipt"][];
            conformance: {
                level: string;
                status: string;
                report_id?: string;
            };
            mcp: {
                authorization: string;
                scopes: string[];
            };
        };
        ConsoleSurfaceRef: {
            id: string;
            source: string;
        };
        ConsoleSurfaceState: {
            id: string;
            status: string;
            source: string;
            /** Format: date-time */
            generated_at: string;
            summary?: {
                [key: string]: unknown;
            };
            records?: {
                [key: string]: unknown;
            }[];
        };
        Session: {
            session_id?: string;
            /** Format: date-time */
            created_at?: string;
            receipt_count?: number;
            last_lamport_clock?: number;
        };
        MCPRemoteDiscovery: {
            server_name?: string;
            version?: string;
            capabilities_url?: string;
            execute_url?: string;
            mcp_endpoint?: string;
            supported_protocol_versions?: string[];
            auth_mode?: string;
            governance?: string;
        };
        MCPJSONRPCRequest: {
            /** @enum {string} */
            jsonrpc: "2.0";
            /** @description Request identifier. Omit for notifications. */
            id?: string | number;
            method: string;
            params?: {
                [key: string]: unknown;
            };
        };
        MCPJSONRPCError: {
            code?: number;
            message?: string;
        };
        MCPJSONRPCResponse: {
            /** @enum {string} */
            jsonrpc?: "2.0";
            id?: string | number;
            result?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["MCPJSONRPCError"];
        };
        MCPProtectedResourceMetadata: {
            resource?: string;
            authorization_servers?: string[];
            scopes_supported?: string[];
            bearer_methods_supported?: string[];
            resource_documentation?: string;
        };
        ExportRequest: {
            /** @description Session to export (omit for all) */
            session_id?: string;
            /**
             * @default tar.gz
             * @enum {string}
             */
            format: "tar.gz";
        };
        VerificationResult: {
            /** @enum {string} */
            verdict?: "PASS" | "FAIL";
            checks?: {
                /** @enum {string} */
                signatures?: "PASS" | "FAIL";
                /** @enum {string} */
                causal_chain?: "PASS" | "FAIL";
                /** @enum {string} */
                policy_compliance?: "PASS" | "FAIL";
            };
            roots?: {
                manifest_root_hash?: string;
                merkle_root?: string;
                entry_count?: number;
            };
            errors?: string[];
        };
        ConformanceRequest: {
            /** @enum {string} */
            level: "L1" | "L2";
            /** @default full */
            profile: string;
        };
        ConformanceResult: {
            report_id?: string;
            level?: string;
            /** @enum {string} */
            verdict?: "PASS" | "FAIL";
            gates?: number;
            failed?: number;
            details?: {
                [key: string]: string;
            };
        };
        VersionInfo: {
            version?: string;
            commit?: string;
            build_time?: string;
            go_version?: string;
        };
        MCPToolRef: {
            name?: string;
            description?: string;
            server_id?: string;
            schema?: {
                [key: string]: unknown;
            };
        };
        MCPCapabilityManifest: {
            server_name?: string;
            version?: string;
            governance?: string;
            tools?: components["schemas"]["MCPToolRef"][];
        };
        MCPToolCallRequest: {
            method: string;
            params?: {
                [key: string]: unknown;
            };
        };
        MCPToolCallResponse: {
            /** @description Tool output payload */
            result?: string | {
                [key: string]: unknown;
            };
            error?: string;
            reason_code?: string;
            args_hash?: string;
            proofgraph_node?: string;
            receipt_id?: string;
        };
        /** @description An effect submitted for governance evaluation */
        Effect: {
            /** @description Category of the effect (file_read, api_call, exec, etc.) */
            effect_type: string;
            /** @description Unique identifier for this effect instance */
            effect_id: string;
            /** @description Effect-specific parameters */
            params: {
                [key: string]: unknown;
            };
            /** @description Optional budget to charge against */
            budget_id?: string;
        };
        /** @description PDP decision for an effect */
        GovernanceDecision: {
            decision_id: string;
            effect_id: string;
            /** @enum {string} */
            verdict: "ALLOW" | "DENY" | "ESCALATE";
            /** @description Null for ALLOW. Registered code from reason-codes-v1.json for DENY/ESCALATE. */
            reason_code?: string | null;
            receipt?: components["schemas"]["Receipt"];
            /** @description Names of policy bundles active during evaluation */
            active_packs?: string[];
        };
        /** @description The boundary contract for submitting effects to the kernel */
        EffectBoundary: {
            effect: components["schemas"]["Effect"];
            /** @description Agent/user identity (e.g. agent:analyst) */
            principal: string;
            /** @description Additional context (jurisdiction, industry, budget state) */
            context?: {
                [key: string]: unknown;
            };
        };
        /** @description Request to the Policy Decision Point */
        PDPRequest: {
            boundary: components["schemas"]["EffectBoundary"];
        };
        /** @description Response from the Policy Decision Point */
        PDPResponse: {
            decision: components["schemas"]["GovernanceDecision"];
        };
        /** @description A loaded policy bundle (jurisdiction, industry, or business pack) */
        PolicyBundle: {
            name: string;
            version: string;
            /** @description SHA-256 of the bundle contents */
            content_hash: string;
            /** @description Ed25519 signature over content_hash */
            signature?: string | null;
            /** @enum {string} */
            pack_type?: "jurisdiction" | "industry" | "business" | "custom";
        };
    };
    responses: {
        /** @description HELM error response */
        HelmError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "message": "Tool not found: unknown_tool",
                 *         "type": "invalid_request",
                 *         "code": "tool_not_found",
                 *         "reason_code": "DENY_TOOL_NOT_FOUND"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["HelmError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chatCompletions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "model": "gpt-4",
                 *       "messages": [
                 *         {
                 *           "role": "user",
                 *           "content": "List files in /tmp"
                 *         }
                 *       ],
                 *       "tools": [
                 *         {
                 *           "type": "function",
                 *           "function": {
                 *             "name": "file_read",
                 *             "parameters": {
                 *               "type": "object",
                 *               "properties": {
                 *                 "path": {
                 *                   "type": "string"
                 *                 }
                 *               }
                 *             }
                 *           }
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Chat completion with optional tool calls */
            200: {
                headers: {
                    /** @description Unique receipt ID for this execution */
                    "X-Helm-Receipt-ID"?: string;
                    /** @description SHA-256 of the response body */
                    "X-Helm-Output-Hash"?: string;
                    /** @description Causal ordering clock */
                    "X-Helm-Lamport-Clock"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                };
            };
            400: components["responses"]["HelmError"];
            403: components["responses"]["HelmError"];
            500: components["responses"]["HelmError"];
        };
    };
    approveIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "intent_hash": "sha256:abc123...",
                 *       "signature_b64": "base64-encoded-ed25519-signature",
                 *       "public_key_b64": "base64-encoded-public-key"
                 *     }
                 */
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Approval receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "receipt_id": "rec_a1b2c3",
                     *       "status": "APPROVED",
                     *       "reason_code": "ALLOW",
                     *       "lamport_clock": 42,
                     *       "output_hash": "sha256:7f83b1..."
                     *     }
                     */
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            400: components["responses"]["HelmError"];
            403: components["responses"]["HelmError"];
        };
    };
    evaluateDecision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Guardian decision record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecord"];
                };
            };
            400: components["responses"]["HelmError"];
            500: components["responses"]["HelmError"];
        };
    };
    listReceipts: {
        parameters: {
            query?: {
                limit?: number;
                since?: string;
                agent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receipt list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptListResponse"];
                };
            };
            400: components["responses"]["HelmError"];
            503: components["responses"]["HelmError"];
        };
    };
    getConsoleReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receipt detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: components["responses"]["HelmError"];
        };
    };
    getConsoleBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Console bootstrap state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleBootstrap"];
                };
            };
        };
    };
    listConsoleSurfaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Console surface catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        surfaces?: components["schemas"]["ConsoleSurfaceRef"][];
                    };
                };
            };
        };
    };
    getConsoleSurface: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surface_id: "overview" | "agents" | "actions" | "approvals" | "policies" | "audit" | "developer" | "settings";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Console surface state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleSurfaceState"];
                };
            };
            404: components["responses"]["HelmError"];
        };
    };
    addTrustKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTrustKeyRequest"];
            };
        };
        responses: {
            /** @description Trust key added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        tenant_id?: string;
                        key_id?: string;
                    };
                };
            };
            400: components["responses"]["HelmError"];
        };
    };
    revokeTrustKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeTrustKeyRequest"];
            };
        };
        responses: {
            /** @description Trust key revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        tenant_id?: string;
                        key_id?: string;
                    };
                };
            };
            400: components["responses"]["HelmError"];
        };
    };
    getMCPTransport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP discovery metadata or SSE primer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPRemoteDiscovery"];
                    "text/event-stream": string;
                };
            };
        };
    };
    postMCPJSONRPC: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MCPJSONRPCRequest"];
            };
        };
        responses: {
            /** @description JSON-RPC response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPJSONRPCResponse"];
                };
            };
            /** @description Invalid JSON-RPC body or unsupported protocol version */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getMCPProtectedResourceMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth protected-resource metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPProtectedResourceMetadata"];
                };
            };
            /** @description OAuth mode is not enabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    getSessionReceipts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of receipts in session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"][];
                };
            };
            404: components["responses"]["HelmError"];
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receipt details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: components["responses"]["HelmError"];
        };
    };
    exportEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "session_id": "sess_abc123",
                 *       "format": "tar.gz"
                 *     }
                 */
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description EvidencePack binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["HelmError"];
        };
    };
    verifyEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description EvidencePack .tar.gz file
                     */
                    bundle?: string;
                };
            };
        };
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "verdict": "PASS",
                     *       "checks": {
                     *         "signatures": "PASS",
                     *         "causal_chain": "PASS",
                     *         "policy_compliance": "PASS"
                     *       },
                     *       "errors": []
                     *     }
                     */
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            400: components["responses"]["HelmError"];
        };
    };
    replayVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    bundle?: string;
                };
            };
        };
        responses: {
            /** @description Replay verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            400: components["responses"]["HelmError"];
        };
    };
    runConformance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "level": "L2",
                 *       "profile": "full"
                 *     }
                 */
                "application/json": components["schemas"]["ConformanceRequest"];
            };
        };
        responses: {
            /** @description Conformance result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "report_id": "conf_abc123",
                     *       "level": "L2",
                     *       "verdict": "PASS",
                     *       "gates": 12,
                     *       "failed": 0,
                     *       "details": {
                     *         "jcs_canonicalization": "PASS",
                     *         "pep_boundary": "PASS",
                     *         "wasi_sandbox": "PASS"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ConformanceResult"];
                };
            };
            400: components["responses"]["HelmError"];
        };
    };
    getConformanceReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conformance report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConformanceResult"];
                };
            };
            404: components["responses"]["HelmError"];
        };
    };
    listMCPCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP capability manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPCapabilityManifest"];
                };
            };
        };
    };
    executeMCPTool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "method": "file_read",
                 *       "params": {
                 *         "path": "/tmp/test.txt"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["MCPToolCallRequest"];
            };
        };
        responses: {
            /** @description Governed tool result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPToolCallResponse"];
                };
            };
            400: components["responses"]["HelmError"];
            403: components["responses"]["HelmError"];
            404: components["responses"]["HelmError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example 0.1.0 */
                        version?: string;
                    };
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "0.1.0",
                     *       "commit": "abc123",
                     *       "build_time": "2026-02-15T00:00:00Z",
                     *       "go_version": "go1.24.0"
                     *     }
                     */
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
