{{- if .Values.gateway.enabled }}
{{- include "helm-ai-kernel.gatewayValidate" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-ai-kernel.gatewayName" . }}
  labels:
    {{- include "helm-ai-kernel.gatewayLabels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "helm-ai-kernel.gatewaySelectorLabels" . | nindent 4 }}
{{- end }}
