{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-ai-kernel.serviceAccountName" . }}
  labels:
    {{- include "helm-ai-kernel.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ ternary true false (eq .Values.helm.policy.source.kind "crd") }}
{{- end }}
