// Package proofmarket implements decentralized proof markets for HELM ZK governance proofs.
//
// Instead of relying solely on the local HELM kernel to generate ZK proofs,
// proofmarket enables proof generation by decentralized prover networks
// (SPN, Boundless, or custom networks). This makes compliance proofs
// trustworthy even when the HELM operator is untrusted — any third-party
// prover can generate the proof, and verifiers can confirm correctness
// using only the public commitments.
//
// The market client manages task submission, network selection with fallback,
// and result polling. All proof tasks are content-hashed for tamper evidence.
package proofmarket

import "time"

// ProofTask is a request submitted to a decentralized prover network.
// It contains only commitment data (no secrets) so any untrusted prover
// can generate the proof without learning the governed policy or data.
type ProofTask struct {
	// TaskID uniquely identifies this proof task across all networks.
	TaskID string `json:"task_id"`

	// ProofRequest contains commitment data for proof generation.
	// This is the public portion of the proof request — no secrets are included.
	ProofRequest map[string]interface{} `json:"proof_request"`

	// Algorithm identifies the proof scheme. Always "helm-zkgov-v1".
	Algorithm string `json:"algorithm"`

	// CallbackURL is an optional URL for the prover network to POST results to.
	CallbackURL string `json:"callback_url,omitempty"`

	// SubmittedAt is when the task was submitted to the network.
	SubmittedAt time.Time `json:"submitted_at"`

	// Deadline is the latest acceptable time for proof generation.
	// Tasks not completed by the deadline transition to EXPIRED.
	Deadline time.Time `json:"deadline"`

	// Status tracks the current state of the proof task.
	Status TaskStatus `json:"status"`

	// ContentHash is SHA-256 of the canonical task body for tamper evidence.
	ContentHash string `json:"content_hash"`
}

// TaskStatus represents the lifecycle state of a proof task.
type TaskStatus string

const (
	// TaskPending indicates the task has been submitted but not yet picked up.
	TaskPending TaskStatus = "PENDING"

	// TaskProving indicates a prover is actively generating the proof.
	TaskProving TaskStatus = "PROVING"

	// TaskCompleted indicates the proof has been successfully generated.
	TaskCompleted TaskStatus = "COMPLETED"

	// TaskFailed indicates proof generation failed.
	TaskFailed TaskStatus = "FAILED"

	// TaskExpired indicates the task was not completed before the deadline.
	TaskExpired TaskStatus = "EXPIRED"
)

// ProofResult is returned by a prover network after proof generation.
// It contains the serialized proof, the prover's attestation, and metadata
// for auditing which network and node generated the proof.
type ProofResult struct {
	// TaskID links this result back to the original ProofTask.
	TaskID string `json:"task_id"`

	// ProverID identifies which node in the network generated the proof.
	ProverID string `json:"prover_id"`

	// NetworkID identifies which decentralized network generated the proof.
	NetworkID string `json:"network_id"`

	// Proof is the serialized proof data (hex-encoded ZK governance proof).
	Proof string `json:"proof"`

	// Attestation is the prover's cryptographic attestation over the proof.
	Attestation string `json:"attestation"`

	// GeneratedAt is when the proof was generated by the prover.
	GeneratedAt time.Time `json:"generated_at"`

	// AnchorID is the transparency log entry ID, if the proof was anchored.
	AnchorID string `json:"anchor_id,omitempty"`

	// ContentHash is SHA-256 of the canonical result body for tamper evidence.
	ContentHash string `json:"content_hash"`
}

// Network identifies a decentralized prover network.
type Network string

const (
	// NetworkLocal is the HELM kernel's built-in prover (fallback).
	NetworkLocal Network = "LOCAL"

	// NetworkSPN is the Succinct Prover Network.
	NetworkSPN Network = "SPN"

	// NetworkBoundless is the RISC Zero Boundless network.
	NetworkBoundless Network = "BOUNDLESS"

	// NetworkCustom is a user-provided prover network.
	NetworkCustom Network = "CUSTOM"
)
