#!/bin/sh
set -eu

# Generated by scripts/launch/update_model_provider_catalog.py --write.

# Egress can be enforced two ways: honor-based (HTTP(S)_PROXY env, the
# local-container substrate) or transparently (iptables REDIRECT into a
# sidecar, the Kubernetes substrate — see docs/launchpad/K8S_SMOKE.md).
# In the transparent mode the workload carries no proxy env by design, so
# HELM_EGRESS_TRANSPARENT marks it; a genuinely dead egress is still caught
# below when curl returns 000.
if [ -z "${HTTPS_PROXY:-}" ] && [ -z "${HTTP_PROXY:-}" ] && [ -z "${HELM_EGRESS_TRANSPARENT:-}" ]; then
  echo "Launchpad egress proxy missing" >&2
  exit 43
fi

requested_provider="${HELM_MODEL_GATEWAY_PROVIDER:-${HELM_LAUNCHPAD_MODEL_PROVIDER:-}}"
found_key=0
unreachable_provider=""
unreachable_env=""

candidate() {
  provider="$1"
  auth_env="$2"
  url_source="$3"
  shift 3
  if [ -n "$requested_provider" ] && [ "$requested_provider" != "$provider" ]; then
    return 0
  fi
  for required_env in "$@"; do
    eval "required_value=\${$required_env:-}"
    if [ -z "$required_value" ]; then
      return 0
    fi
  done
  found_key=1
  eval "value=\${$auth_env:-}"
  if [ -z "$value" ]; then
    return 0
  fi
  case "$url_source" in
    env:*)
      url_env="${url_source#env:}"
      eval "url=\${$url_env:-}"
      ;;
    *)
      url="$url_source"
      ;;
  esac
  if [ -z "$url" ]; then
    return 0
  fi
  status="$(curl --silent --show-error --connect-timeout 10 --max-time 30 \
    --output /dev/null --write-out "%{http_code}" \
    -H "Authorization: Bearer ${value}" \
    "${url}" || true)"
  # Ready only on a 2xx — the provider is both reachable AND accepted the
  # credential. A 401/403 (bad key), 5xx, or 000 (dead egress) is NOT ready:
  # record the reason and fall through to the next candidate. Gating on 2xx
  # (rather than 'any HTTP status') is what makes the negative smoke with a
  # fake key correctly stay not-ready — see docs/launchpad/K8S_SMOKE.md §138.
  case "$status" in
    2[0-9][0-9])
      echo "Model provider ${provider} reachable and authorized through Launchpad egress proxy using ${auth_env} (HTTP ${status})"
      exit 0
      ;;
    000)
      unreachable_provider="$provider"
      unreachable_env="$auth_env"
      return 0
      ;;
    *)
      unreachable_provider="$provider"
      unreachable_env="$auth_env"
      echo "Model provider ${provider} reachable but rejected credential ${auth_env} (HTTP ${status})" >&2
      return 0
      ;;
  esac
}

candidate "01-ai" "LINGYIWANWU_API_KEY" "https://api.01.ai/v1/models" "LINGYIWANWU_API_KEY"
candidate "01-ai" "YI_API_KEY" "https://api.01.ai/v1/models" "YI_API_KEY"
candidate "aleph-alpha" "ALEPH_ALPHA_API_KEY" "https://api.aleph-alpha.com/models" "ALEPH_ALPHA_API_KEY"
candidate "alibaba-dashscope" "DASHSCOPE_API_KEY" "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/models" "DASHSCOPE_API_KEY"
candidate "amazon-bedrock" "AWS_BEARER_TOKEN_BEDROCK" "https://bedrock-mantle.eu-central-1.api.aws/models" "AWS_BEARER_TOKEN_BEDROCK" "AWS_REGION"
candidate "amazon-bedrock" "AWS_ACCESS_KEY_ID" "https://bedrock-mantle.eu-central-1.api.aws/models" "AWS_ACCESS_KEY_ID" "AWS_REGION" "AWS_SECRET_ACCESS_KEY"
candidate "anthropic" "ANTHROPIC_API_KEY" "https://api.anthropic.com/v1/models" "ANTHROPIC_API_KEY"
candidate "azure-ai-foundry" "AZURE_INFERENCE_CREDENTIAL" "env:AZURE_AI_FOUNDRY_ENDPOINT" "AZURE_AI_FOUNDRY_ENDPOINT" "AZURE_INFERENCE_CREDENTIAL"
candidate "azure-ai-foundry" "AZURE_INFERENCE_CREDENTIAL" "env:AZURE_AI_INFERENCE_ENDPOINT" "AZURE_AI_INFERENCE_ENDPOINT" "AZURE_INFERENCE_CREDENTIAL"
candidate "azure-openai" "AZURE_OPENAI_API_KEY" "env:AZURE_OPENAI_ENDPOINT" "AZURE_OPENAI_API_KEY" "AZURE_OPENAI_ENDPOINT"
candidate "baichuan" "BAICHUAN_API_KEY" "https://api.baichuan-ai.com/v1/models" "BAICHUAN_API_KEY"
candidate "baidu-qianfan" "QIANFAN_API_KEY" "https://qianfan.baidubce.com/v2/models" "QIANFAN_API_KEY"
candidate "cerebras" "CEREBRAS_API_KEY" "https://api.cerebras.ai/v1/models" "CEREBRAS_API_KEY"
candidate "cloudflare-ai-gateway" "CLOUDFLARE_API_TOKEN" "env:CLOUDFLARE_AI_GATEWAY_BASE_URL" "CLOUDFLARE_AI_GATEWAY_BASE_URL" "CLOUDFLARE_API_TOKEN"
candidate "cohere" "COHERE_API_KEY" "https://api.cohere.com/v2/models" "COHERE_API_KEY"
candidate "deepinfra" "DEEPINFRA_API_KEY" "https://api.deepinfra.com/v1/openai/models" "DEEPINFRA_API_KEY"
candidate "deepinfra" "DEEPINFRA_TOKEN" "https://api.deepinfra.com/v1/openai/models" "DEEPINFRA_TOKEN"
candidate "deepseek" "DEEPSEEK_API_KEY" "https://api.deepseek.com/models" "DEEPSEEK_API_KEY"
candidate "fireworks-ai" "FIREWORKS_API_KEY" "https://api.fireworks.ai/inference/v1/models" "FIREWORKS_API_KEY"
candidate "github-models" "GITHUB_MODELS_TOKEN" "https://models.github.ai/catalog/models" "GITHUB_MODELS_TOKEN"
candidate "google-gemini" "GEMINI_API_KEY" "https://generativelanguage.googleapis.com/v1beta/models" "GEMINI_API_KEY"
candidate "google-gemini" "GOOGLE_API_KEY" "https://generativelanguage.googleapis.com/v1beta/models" "GOOGLE_API_KEY"
candidate "google-vertex-ai" "GOOGLE_VERTEX_ACCESS_TOKEN" "env:GOOGLE_VERTEX_BASE_URL" "GOOGLE_VERTEX_ACCESS_TOKEN" "GOOGLE_VERTEX_BASE_URL"
candidate "google-vertex-ai" "GOOGLE_VERTEX_ACCESS_TOKEN" "https://aiplatform.googleapis.com/v1/models" "GOOGLE_VERTEX_ACCESS_TOKEN" "GOOGLE_VERTEX_BASE_URL"
candidate "google-vertex-ai" "GOOGLE_APPLICATION_CREDENTIALS" "https://aiplatform.googleapis.com/v1/models" "GOOGLE_APPLICATION_CREDENTIALS" "GOOGLE_CLOUD_LOCATION" "GOOGLE_CLOUD_PROJECT"
candidate "groq" "GROQ_API_KEY" "https://api.groq.com/openai/v1/models" "GROQ_API_KEY"
candidate "hugging-face" "HF_TOKEN" "https://router.huggingface.co/v1/models" "HF_TOKEN"
candidate "hugging-face" "HUGGINGFACE_API_KEY" "https://router.huggingface.co/v1/models" "HUGGINGFACE_API_KEY"
candidate "ibm-watsonx" "IBM_CLOUD_API_KEY" "https://ca-tor.ml.cloud.ibm.com/models" "IBM_CLOUD_API_KEY" "WATSONX_PROJECT_ID"
candidate "ibm-watsonx" "IBM_CLOUD_API_KEY" "https://ca-tor.ml.cloud.ibm.com/models" "IBM_CLOUD_API_KEY" "WATSONX_SPACE_ID"
candidate "ibm-watsonx" "IBM_WATSONX_ACCESS_TOKEN" "https://ca-tor.ml.cloud.ibm.com/models" "IBM_WATSONX_ACCESS_TOKEN" "WATSONX_PROJECT_ID"
candidate "ibm-watsonx" "IBM_WATSONX_ACCESS_TOKEN" "https://ca-tor.ml.cloud.ibm.com/models" "IBM_WATSONX_ACCESS_TOKEN" "WATSONX_SPACE_ID"
candidate "iflytek-spark" "IFLYTEK_SPARK_API_PASSWORD" "https://maas-coding-api.cn-huabei-1.xf-yun.com/v2/models" "IFLYTEK_SPARK_API_PASSWORD"
candidate "iflytek-spark" "XFYUN_SPARK_API_PASSWORD" "https://maas-coding-api.cn-huabei-1.xf-yun.com/v2/models" "XFYUN_SPARK_API_PASSWORD"
candidate "ionos-ai-model-hub" "IONOS_API_TOKEN" "https://openai.inference.de-txl.ionos.com/v1/models" "IONOS_API_TOKEN"
candidate "minimax" "MINIMAX_API_KEY" "https://api.minimax.io/v1/models" "MINIMAX_API_KEY"
candidate "mistral" "MISTRAL_API_KEY" "https://api.mistral.ai/v1/models" "MISTRAL_API_KEY"
candidate "modelscope" "MODELSCOPE_API_KEY" "https://api-inference.modelscope.cn/v1/models" "MODELSCOPE_API_KEY"
candidate "modelscope" "MODELSCOPE_TOKEN" "https://api-inference.modelscope.cn/v1/models" "MODELSCOPE_TOKEN"
candidate "moonshot" "MOONSHOT_API_KEY" "https://api.moonshot.ai/v1/models" "MOONSHOT_API_KEY"
candidate "nebius" "NEBIUS_API_KEY" "https://api.studio.nebius.ai/v1/models" "NEBIUS_API_KEY"
candidate "nvidia-nim" "NVIDIA_API_KEY" "https://integrate.api.nvidia.com/v1/models" "NVIDIA_API_KEY"
candidate "nvidia-nim" "NVIDIA_NIM_API_KEY" "https://integrate.api.nvidia.com/v1/models" "NVIDIA_NIM_API_KEY"
candidate "openai" "OPENAI_API_KEY" "https://api.openai.com/v1/models" "OPENAI_API_KEY"
candidate "openrouter" "OPENROUTER_API_KEY" "https://openrouter.ai/api/v1/key" "OPENROUTER_API_KEY"
candidate "ovhcloud-ai-endpoints" "AI_ENDPOINT_API_KEY" "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1/models" "AI_ENDPOINT_API_KEY"
candidate "ovhcloud-ai-endpoints" "OVH_AI_ENDPOINTS_ACCESS_TOKEN" "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1/models" "OVH_AI_ENDPOINTS_ACCESS_TOKEN"
candidate "perplexity" "PERPLEXITY_API_KEY" "https://api.perplexity.ai/v1/models" "PERPLEXITY_API_KEY"
candidate "replicate" "REPLICATE_API_TOKEN" "https://api.replicate.com/v1/models" "REPLICATE_API_TOKEN"
candidate "sambanova" "SAMBANOVA_API_KEY" "https://api.sambanova.ai/v1/models" "SAMBANOVA_API_KEY"
candidate "scaleway-generative-apis" "SCALEWAY_API_KEY" "https://api.scaleway.ai/v1/models" "SCALEWAY_API_KEY"
candidate "scaleway-generative-apis" "SCW_SECRET_KEY" "https://api.scaleway.ai/v1/models" "SCW_SECRET_KEY"
candidate "siliconflow" "SILICONFLOW_API_KEY" "https://api.siliconflow.cn/v1/models" "SILICONFLOW_API_KEY"
candidate "stepfun" "STEPFUN_API_KEY" "https://api.stepfun.ai/step_plan/v1/models" "STEPFUN_API_KEY"
candidate "stepfun" "STEP_API_KEY" "https://api.stepfun.ai/step_plan/v1/models" "STEP_API_KEY"
candidate "tencent-hunyuan" "HUNYUAN_API_KEY" "https://api.hunyuan.cloud.tencent.com/v1/models" "HUNYUAN_API_KEY"
candidate "tencent-hunyuan" "TENCENT_HUNYUAN_API_KEY" "https://api.hunyuan.cloud.tencent.com/v1/models" "TENCENT_HUNYUAN_API_KEY"
candidate "together-ai" "TOGETHER_API_KEY" "https://api.together.ai/v1/models" "TOGETHER_API_KEY"
candidate "vercel-ai-gateway" "AI_GATEWAY_API_KEY" "https://ai-gateway.vercel.sh/v1/models" "AI_GATEWAY_API_KEY"
candidate "vercel-ai-gateway" "VERCEL_OIDC_TOKEN" "https://ai-gateway.vercel.sh/v1/models" "VERCEL_OIDC_TOKEN"
candidate "volcengine-ark" "ARK_API_KEY" "https://ark.cn-beijing.volces.com/api/v3/models" "ARK_API_KEY"
candidate "volcengine-ark" "VOLCENGINE_API_KEY" "https://ark.cn-beijing.volces.com/api/v3/models" "VOLCENGINE_API_KEY"
candidate "xai" "XAI_API_KEY" "https://api.x.ai/v1/models" "XAI_API_KEY"
candidate "zhipu-bigmodel" "BIGMODEL_API_KEY" "https://open.bigmodel.cn/api/paas/v4/models" "BIGMODEL_API_KEY"
candidate "zhipu-bigmodel" "ZHIPU_API_KEY" "https://open.bigmodel.cn/api/paas/v4/models" "ZHIPU_API_KEY"

if [ "$found_key" = "0" ]; then
  if [ -n "$requested_provider" ]; then
    echo "No API key found for requested model provider ${requested_provider}" >&2
  else
    echo "No supported BYO model provider API key found" >&2
  fi
  exit 42
fi

echo "No configured BYO model provider was reachable AND authorized through Launchpad egress proxy; last failing provider ${unreachable_provider} using ${unreachable_env}" >&2
exit 44
