export const designTokenSource = {
  breakpoints: {
    desktop: 1200,
    mid: 930,
    tablet: 768,
    mobile: 390,
    narrow: 320,
  },
  spacing: {
    s1: 2,
    s2: 4,
    s3: 6,
    s4: 8,
    s5: 10,
    s6: 12,
    s8: 16,
    s10: 20,
    s12: 24,
    s16: 32,
  },
  radius: {
    xs: 2,
    sm: 3,
    md: 4,
    panel: 6,
    pill: 999,
  },
  duration: {
    legacy: 160,
    instant: 80,
    fast: 140,
    base: 200,
    slow: 320,
    skeleton: 1400,
  },
  zIndex: {
    base: 0,
    sticky: 10,
    topbar: 20,
    sidebar: 25,
    drawerBackdrop: 40,
    drawer: 41,
    contextMenu: 45,
    modal: 50,
    toast: 60,
    paletteBackdrop: 70,
    palette: 71,
  },
  focusRing: {
    width: 2,
    offset: 2,
  },
  minTouchTarget: 44,
  sidebarWidth: 248,
  topbarHeight: 52,
  typographyFloors: {
    body: 13,
    denseTable: 12,
    metadata: 12,
    code: 12,
    panelTitle: 13,
    pageTitleMin: 18,
    pageTitleMax: 22,
  },
  density: {
    compact: { body: 13, table: 12, meta: 12, code: 12 },
    comfortable: { body: 14, table: 13, meta: 12.5, code: 12.5 },
  },
  approvedDynamicInlineStyles: [
    "timeline playhead percentage",
    "graph coordinate CSS variable",
    "runtime measurement CSS variable",
    "virtualization spacer height",
    "container query inline-size measurement",
    "context menu viewport coordinates",
  ],
} as const;
