#!/usr/bin/env python3
"""Generate every language's reason codes from the one registry (HELM-747 s2).

protocols/json-schemas/reason-codes/reason-codes-v1.json is the only list of
reason codes (target architecture §11.1, R4). This script writes it out as
string constants for the kernel (Go) and the five SDKs. On the wire a reason
code is an open string: each language gets named constants and an
is-registered test, never a closed enum that turns an unknown code into
"unspecified" (audit C-02).

`--check` regenerates in memory and fails on drift. It also checks the proto
IDL: every value of the legacy closed `ReasonCode` enum must be a registry
code, and every message with such a field must carry the open-string
`reason_code_text` beside it.

Usage: gen_reason_codes.py [--check]
Stdlib only, like check_reason_codes.py, so the gate cannot no-op on a
missing package.
"""

from __future__ import annotations

import json
import re
import sys
import textwrap
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = "protocols/json-schemas/reason-codes/reason-codes-v1.json"
PROTO = "protocols/proto/helm/kernel/v1/helm.proto"
GO_CORE = "core/pkg/contracts/reason_codes_gen.go"
OUTPUTS = [
    GO_CORE,
    "sdk/go/reasoncodes/reasoncodes_gen.go",
    "sdk/ts/src/reason_codes.gen.ts",
    "sdk/python/helm_sdk/reason_codes.py",
    "sdk/rust/src/reason_codes.rs",
    "sdk/java/src/main/java/labs/mindburn/helm/ReasonCodes.java",
]
HEADER = f"Code generated by scripts/ci/gen_reason_codes.py from {REGISTRY}. DO NOT EDIT."
CODE_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
OPEN_STRING = (
    "A reason code is an open string on the wire. These constants name the registered "
    "codes; a code missing from this list is still a valid value, not an error."
)

Entry = dict[str, Any]


def load_registry(root: Path) -> list[Entry]:
    return json.loads((root / REGISTRY).read_text(encoding="utf-8"))["codes"]


def pascal(code: str) -> str:
    return "".join(word.capitalize() for word in code.split("_"))


def summary(entry: Entry) -> str:
    text = f"{'/'.join(entry['applies_to'])}: {entry['description']}"
    return text.replace("*/", "*\\/")


def wrap(text: str, prefix: str, width: int = 88) -> str:
    return "\n".join(textwrap.wrap(text, width=width, initial_indent=prefix, subsequent_indent=prefix))


def go_core(entries: list[Entry]) -> str:
    lines = "".join(f'\t"{e["code"]}",\n' for e in entries)
    return f"""// {HEADER}

package contracts

// registeredReasonCodes is the reason-code registry, in registry order. The
// Reason* constants in verdict.go name these values;
// TestReasonCodeDeclarations_MatchRegistry keeps the two sets equal.
var registeredReasonCodes = [...]ReasonCode{{
{lines}}}

// CoreReasonCodes returns the full normative core reason-code registry.
func CoreReasonCodes() []ReasonCode {{
	return append([]ReasonCode(nil), registeredReasonCodes[:]...)
}}
"""


def go_sdk(entries: list[Entry]) -> str:
    consts = "".join(
        f"{wrap(pascal(e['code']) + ' ' + summary(e), '// ', 80)}\nconst {pascal(e['code'])} = \"{e['code']}\"\n\n"
        for e in entries
    )
    names = "".join(f"\t{pascal(e['code'])},\n" for e in entries)
    return f"""// {HEADER}

// Package reasoncodes names the codes in the HELM reason-code registry.
//
{wrap(OPEN_STRING, "// ", 80)}
package reasoncodes

{consts}var all = [...]string{{
{names}}}

// All returns every registered reason code, in registry order.
func All() []string {{
	return append([]string(nil), all[:]...)
}}

// IsRegistered reports whether code is in the registry.
func IsRegistered(code string) bool {{
	for _, registered := range all {{
		if registered == code {{
			return true
		}}
	}}
	return false
}}
"""


def typescript(entries: list[Entry]) -> str:
    members = "".join(f"{wrap(summary(e), '  /** ', 100)} */\n  {e['code']}: \"{e['code']}\",\n" for e in entries)
    return f"""// {HEADER}

/**
{wrap(OPEN_STRING, " * ", 80)}
 */
export const ReasonCodes = {{
{members}}} as const;

export type RegisteredReasonCode = (typeof ReasonCodes)[keyof typeof ReasonCodes];

const registered: ReadonlySet<string> = new Set(Object.values(ReasonCodes));

/** Whether `code` is in the registry. */
export function isRegisteredReasonCode(code: string): code is RegisteredReasonCode {{
  return registered.has(code);
}}
"""


def python(entries: list[Entry]) -> str:
    consts = "".join(f"{e['code']} = \"{e['code']}\"\n{wrap(summary(e), '# ')}\n\n" for e in entries)
    names = "".join(f"        {e['code']},\n" for e in entries)
    return f'''# {HEADER}
# ruff: noqa: E501 (generated: constant names and the header exceed the line limit)
"""The codes in the HELM reason-code registry.

{textwrap.fill(OPEN_STRING, 88)}
"""

from __future__ import annotations

{consts}ALL: frozenset[str] = frozenset(
    {{
{names}    }}
)


def is_registered(code: str) -> bool:
    """Whether ``code`` is in the registry."""
    return code in ALL
'''


def rust(entries: list[Entry]) -> str:
    consts = "".join(
        f"{wrap(summary(e), '/// ', 100)}\npub const {e['code']}: &str = \"{e['code']}\";\n" for e in entries
    )
    names = "".join(f"    {e['code']},\n" for e in entries)
    return f"""// {HEADER}

//! The codes in the HELM reason-code registry.
//!
{wrap(OPEN_STRING, "//! ", 100)}

{consts}
/// Every registered reason code, in registry order.
pub const ALL: &[&str] = &[
{names}];

/// Whether `code` is in the registry.
pub fn is_registered(code: &str) -> bool {{
    ALL.contains(&code)
}}
"""


def java(entries: list[Entry]) -> str:
    consts = "".join(
        f"{wrap(summary(e), '    /** ', 100)} */\n    public static final String {e['code']} = \"{e['code']}\";\n\n"
        for e in entries
    )
    names = ",\n".join(f"            {e['code']}" for e in entries)
    return f"""// {HEADER}
package labs.mindburn.helm;

import java.util.Set;

/**
{wrap(OPEN_STRING, " * ", 100)}
 */
public final class ReasonCodes {{
    private ReasonCodes() {{}}

{consts}    /** Every registered reason code. */
    public static final Set<String> ALL = Set.of(
{names});

    /** Whether {{@code code}} is in the registry. */
    public static boolean isRegistered(String code) {{
        return ALL.contains(code);
    }}
}}
"""


RENDERERS = [go_core, go_sdk, typescript, python, rust, java]


def render(entries: list[Entry]) -> dict[str, str]:
    seen: set[str] = set()
    for entry in entries:
        code = entry["code"]
        if not CODE_RE.match(code):
            raise ValueError(f"registry code {code!r} does not match {CODE_RE.pattern}")
        if code in seen:
            raise ValueError(f"registry code {code!r} is duplicated")
        seen.add(code)
    return {path: renderer(entries) for path, renderer in zip(OUTPUTS, RENDERERS)}


def check_proto(root: Path, codes: set[str]) -> list[str]:
    text = (root / PROTO).read_text(encoding="utf-8")
    problems = []
    enum = re.search(r"^enum ReasonCode \{(.*?)^\}", text, re.S | re.M)
    if enum is None:
        return ["helm.proto: enum ReasonCode not found"]
    for value in re.findall(r"^\s*REASON_CODE_([A-Z0-9_]+)\s*=", enum.group(1), re.M):
        if value != "UNSPECIFIED" and value not in codes:
            problems.append(f"helm.proto: enum value REASON_CODE_{value} is not a registry code")
    for name, body in re.findall(r"^message (\w+) \{(.*?)^\}", text, re.S | re.M):
        if re.search(r"^\s*ReasonCode \w+ = \d+;", body, re.M) and not re.search(
            r"^\s*string reason_code_text = \d+;", body, re.M
        ):
            problems.append(f"helm.proto: message {name} has a ReasonCode enum field but no string reason_code_text")
    return problems


def check(root: Path) -> list[str]:
    entries = load_registry(root)
    problems = []
    for path, want in render(entries).items():
        target = root / path
        if not target.exists() or target.read_text(encoding="utf-8") != want:
            problems.append(f"{path}: out of date; run python3 scripts/ci/gen_reason_codes.py")
    return problems + check_proto(root, {e["code"] for e in entries})


def main(argv: list[str]) -> int:
    if argv == ["--check"]:
        problems = check(ROOT)
        for problem in problems:
            print(f"::error::{problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"reason codes: {len(load_registry(ROOT))} registry codes, in sync across {len(OUTPUTS)} outputs and the proto")
        return 0
    if argv:
        print(__doc__, file=sys.stderr)
        return 2
    for path, text in render(load_registry(ROOT)).items():
        target = ROOT / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
