import type { ActionRecord } from "../components/core";

export const actionRecords: readonly ActionRecord[] = [
  {
    id: "act-deny-1",
    timestamp: "19:15:50.089",
    agent: "agent.data.export",
    action: "export_dataset",
    target: "connector.s3",
    environment: "production",
    risk: "critical",
    policy: "data.export.sensitive.v1",
    verdict: "deny",
    receipt: "ep_9f82c31a",
    verification: "verified",
  },
  {
    id: "act-allow-1",
    timestamp: "19:15:46.088",
    agent: "agent.ops.release",
    action: "open_pull_request",
    target: "connector.github",
    environment: "dev",
    risk: "low",
    policy: "connector.github.write.v1",
    verdict: "allow",
    receipt: "ep_allow_8841",
    verification: "verified",
  },
  {
    id: "act-escalate-1",
    timestamp: "19:15:25.275",
    agent: "agent.ops.release",
    action: "deploy_production",
    target: "connector.cloudflare",
    environment: "production",
    risk: "critical",
    policy: "release.high_risk.v2",
    verdict: "escalate",
    receipt: "ep_a71c04dd",
    verification: "pending",
  },
  {
    id: "act-deny-2",
    timestamp: "19:15:21.075",
    agent: "agent.finance.reconcile",
    action: "wire_transfer",
    target: "connector.stripe",
    environment: "production",
    risk: "high",
    policy: "finance.transfer.threshold.v3",
    verdict: "deny",
    receipt: "ep_deny_2041",
    verification: "verified",
  },
];
