// Code generated by scripts/ci/gen_reason_codes.py from protocols/json-schemas/reason-codes/reason-codes-v1.json. DO NOT EDIT.

//! The codes in the HELM reason-code registry.
//!
//! A reason code is an open string on the wire. These constants name the registered codes; a code
//! missing from this list is still a valid value, not an error.

/// DENY: Effect violates an active policy rule
pub const POLICY_VIOLATION: &str = "POLICY_VIOLATION";
/// DENY: No policy covers this effect type
pub const NO_POLICY_DEFINED: &str = "NO_POLICY_DEFINED";
/// DENY: No verified EffectivePolicySnapshot is installed for the requested scope
pub const POLICY_NOT_READY: &str = "POLICY_NOT_READY";
/// DENY: Policy source bytes did not match the published canonical policy hash
pub const POLICY_HASH_MISMATCH: &str = "POLICY_HASH_MISMATCH";
/// DENY: Policy source signature or provenance verification failed
pub const POLICY_SIGNATURE_INVALID: &str = "POLICY_SIGNATURE_INVALID";
/// DENY: The active policy epoch changed before the effect could be issued
pub const POLICY_EPOCH_CHANGED: &str = "POLICY_EPOCH_CHANGED";
/// DENY: Policy Requirement Graph evaluation failed
pub const PRG_EVALUATION_ERROR: &str = "PRG_EVALUATION_ERROR";
/// DENY: Request does not conform to schema
pub const SCHEMA_VIOLATION: &str = "SCHEMA_VIOLATION";
/// DENY: External PDP returned deny
pub const PDP_DENY: &str = "PDP_DENY";
/// DENY: PDP unavailable or returned error (fail-closed)
pub const PDP_ERROR: &str = "PDP_ERROR";
/// DENY: Required precondition not satisfied
pub const MISSING_REQUIREMENT: &str = "MISSING_REQUIREMENT";
/// DENY: Operation exceeds allocated budget
pub const BUDGET_EXCEEDED: &str = "BUDGET_EXCEEDED";
/// DENY: Budget system unavailable (fail-closed)
pub const BUDGET_ERROR: &str = "BUDGET_ERROR";
/// ESCALATE: Time-based intervention triggered
pub const TEMPORAL_INTERVENTION: &str = "TEMPORAL_INTERVENTION";
/// ESCALATE: Rate limit or cooldown active
pub const TEMPORAL_THROTTLE: &str = "TEMPORAL_THROTTLE";
/// DENY: Session trajectory risk exceeded the deterministic authorization threshold
pub const SESSION_RISK_MEMORY_DENY: &str = "SESSION_RISK_MEMORY_DENY";
/// DENY: Effect envelope failed validation
pub const ENVELOPE_INVALID: &str = "ENVELOPE_INVALID";
/// DENY: Provenance chain broken or unverifiable
pub const PROVENANCE_FAILURE: &str = "PROVENANCE_FAILURE";
/// DENY: Cryptographic verification failed
pub const VERIFICATION_FAILURE: &str = "VERIFICATION_FAILURE";
/// DENY: Effect exceeds sandbox boundary
pub const SANDBOX_VIOLATION: &str = "SANDBOX_VIOLATION";
/// DENY: Cross-tenant access violation
pub const TENANT_ISOLATION: &str = "TENANT_ISOLATION";
/// DENY: Effect violates jurisdictional constraint
pub const JURISDICTION_VIOLATION: &str = "JURISDICTION_VIOLATION";
/// DENY: System is in global freeze state — all actions denied
pub const SYSTEM_FROZEN: &str = "SYSTEM_FROZEN";
/// DENY: A governed dispatch omitted the authoritative tenant/workspace scope required while
/// emergency-stop fencing is enabled
pub const EMERGENCY_STOP_SCOPE_REQUIRED: &str = "EMERGENCY_STOP_SCOPE_REQUIRED";
/// DENY: Emergency-stop fence status could not be verified, so the governed dispatch was denied
/// fail-closed
pub const EMERGENCY_STOP_UNVERIFIED: &str = "EMERGENCY_STOP_UNVERIFIED";
/// DENY: A durable tenant/workspace emergency-stop fence is active for newly governed dispatches
pub const EMERGENCY_STOP_FENCED: &str = "EMERGENCY_STOP_FENCED";
/// DENY: Environment fingerprint does not match boot-time snapshot
pub const CONTEXT_MISMATCH: &str = "CONTEXT_MISMATCH";
/// DENY: Data transmission to unauthorized external endpoint blocked
pub const DATA_EGRESS_BLOCKED: &str = "DATA_EGRESS_BLOCKED";
/// DENY: Host-observed egress has no corresponding HELM intent or authority receipt
pub const ERR_HOST_EGRESS_WITHOUT_INTENT: &str = "ERR_HOST_EGRESS_WITHOUT_INTENT";
/// DENY: Host-observed egress occurred after HELM denied the corresponding action
pub const ERR_HOST_EGRESS_AFTER_DENY: &str = "ERR_HOST_EGRESS_AFTER_DENY";
/// DENY: A HELM network-authority receipt has no matching host evidence receipt
pub const ERR_HOST_RECEIPT_MISSING: &str = "ERR_HOST_RECEIPT_MISSING";
/// DENY: Host-observed egress destination differs from HELM authority metadata
pub const ERR_HOST_DESTINATION_MISMATCH: &str = "ERR_HOST_DESTINATION_MISMATCH";
/// DENY: Host-observed egress byte volume exceeds the HELM authority ceiling
pub const ERR_HOST_VOLUME_EXCEEDED: &str = "ERR_HOST_VOLUME_EXCEEDED";
/// DENY: Host receipt process identity cannot be bound to a HELM workload identity
pub const ERR_HOST_PROCESS_UNBOUND: &str = "ERR_HOST_PROCESS_UNBOUND";
/// DENY: Host evidence contradicts a HELM policy denial for network egress
pub const ERR_POLICY_DENIED_BUT_HOST_OBSERVED_EGRESS: &str = "ERR_POLICY_DENIED_BUT_HOST_OBSERVED_EGRESS";
/// DENY: Agent credential reuse or impersonation detected
pub const IDENTITY_ISOLATION_VIOLATION: &str = "IDENTITY_ISOLATION_VIOLATION";
/// DENY: Agent privilege tier insufficient for requested effect type
pub const INSUFFICIENT_PRIVILEGE: &str = "INSUFFICIENT_PRIVILEGE";
/// ESCALATE: High-risk effect requires human approval before execution
pub const APPROVAL_REQUIRED: &str = "APPROVAL_REQUIRED";
/// DENY: Human approval not received within timeout — action denied
pub const APPROVAL_TIMEOUT: &str = "APPROVAL_TIMEOUT";
/// DENY: No pinned control-plane activation verification key is configured
pub const ACTIVATION_TRUST_UNAVAILABLE: &str = "ACTIVATION_TRUST_UNAVAILABLE";
/// DENY: The company activation record failed schema, integrity, signature, or lifetime validation
pub const ACTIVATION_RECORD_INVALID: &str = "ACTIVATION_RECORD_INVALID";
/// DENY: The company activation record does not match the authenticated tenant, company domain,
/// workspace, or configured environment
pub const ACTIVATION_BINDING_MISMATCH: &str = "ACTIVATION_BINDING_MISMATCH";
/// DENY: The signed or requested effect, autonomy, or exposure limit exceeds the current company
/// activation ceiling
pub const ACTIVATION_CEILING_EXCEEDED: &str = "ACTIVATION_CEILING_EXCEEDED";
/// DENY: Delegation session is invalid, expired, revoked, or has a binding mismatch
pub const DELEGATION_INVALID: &str = "DELEGATION_INVALID";
/// DENY: Delegate attempted an action outside the session's granted capabilities
pub const DELEGATION_SCOPE_VIOLATION: &str = "DELEGATION_SCOPE_VIOLATION";
/// DENY: Requesting principal does not match the delegation session's bound delegate principal
pub const DELEGATION_PRINCIPAL_MISMATCH: &str = "DELEGATION_PRINCIPAL_MISMATCH";
/// DENY: Agent has been terminated via per-agent kill switch
pub const AGENT_KILLED: &str = "AGENT_KILLED";
/// DENY: High-risk effect denied due to tainted/untrusted input source
pub const TAINTED_INPUT_HIGH_RISK_DENY: &str = "TAINTED_INPUT_HIGH_RISK_DENY";
/// DENY: Prompt injection pattern detected in untrusted input
pub const PROMPT_INJECTION_DETECTED: &str = "PROMPT_INJECTION_DETECTED";
/// DENY: Unicode obfuscation (zero-width chars, homoglyphs) detected
pub const UNICODE_OBFUSCATION_DETECTED: &str = "UNICODE_OBFUSCATION_DETECTED";
/// DENY: Credential or token access attempted from tainted source
pub const TAINTED_CREDENTIAL_ACCESS_DENY: &str = "TAINTED_CREDENTIAL_ACCESS_DENY";
/// DENY: Software publish or release attempted from tainted source
pub const TAINTED_SOFTWARE_PUBLISH_DENY: &str = "TAINTED_SOFTWARE_PUBLISH_DENY";
/// DENY: Privileged agent invocation attempted from tainted source
pub const TAINTED_PRIVILEGED_INVOKE_DENY: &str = "TAINTED_PRIVILEGED_INVOKE_DENY";
/// DENY: Data egress or exfiltration attempted from tainted source
pub const TAINTED_DATA_EGRESS_DENY: &str = "TAINTED_DATA_EGRESS_DENY";
/// ESCALATE: High-risk effect from tainted source requires human approval
pub const TAINTED_HIGH_RISK_ESCALATE: &str = "TAINTED_HIGH_RISK_ESCALATE";
/// ESCALATE: Configured deterministic semantic advisory requires human review
pub const SEMANTIC_THREAT_REVIEW_REQUIRED: &str = "SEMANTIC_THREAT_REVIEW_REQUIRED";
/// DENY: Requested Acton action is not one of the typed HELM TON Acton actions
pub const ERR_TON_ACTON_UNKNOWN_COMMAND: &str = "ERR_TON_ACTON_UNKNOWN_COMMAND";
/// DENY: Observed Acton version is outside the connector contract
pub const ERR_TON_ACTON_UNSUPPORTED_VERSION: &str = "ERR_TON_ACTON_UNSUPPORTED_VERSION";
/// DENY: A Tolk compiler version pin is required for bytecode-sensitive TON work
pub const ERR_TON_TOLK_COMPILER_UNPINNED: &str = "ERR_TON_TOLK_COMPILER_UNPINNED";
/// DENY: Observed Tolk compiler version does not match policy or connector contract
pub const ERR_TON_TOLK_COMPILER_MISMATCH: &str = "ERR_TON_TOLK_COMPILER_MISMATCH";
/// DENY: Acton argv failed typed connector validation
pub const ERR_TON_ACTON_ARGV_REJECTED: &str = "ERR_TON_ACTON_ARGV_REJECTED";
/// DENY: Raw shell or raw command execution was requested for Acton
pub const ERR_TON_ACTON_RAW_SHELL_FORBIDDEN: &str = "ERR_TON_ACTON_RAW_SHELL_FORBIDDEN";
/// DENY: Generic Acton mainnet script execution is denied by default
pub const ERR_TON_ACTON_GENERIC_MAINNET_SCRIPT_DENIED: &str = "ERR_TON_ACTON_GENERIC_MAINNET_SCRIPT_DENIED";
/// DENY: Networked Acton script is missing the required HELM sidecar manifest
pub const ERR_TON_SCRIPT_MANIFEST_REQUIRED: &str = "ERR_TON_SCRIPT_MANIFEST_REQUIRED";
/// DENY: Acton script hash does not match the HELM sidecar manifest
pub const ERR_TON_SCRIPT_MANIFEST_HASH_MISMATCH: &str = "ERR_TON_SCRIPT_MANIFEST_HASH_MISMATCH";
/// DENY/ESCALATE: Declared TON expected effects are missing or do not match the action envelope
pub const ERR_TON_EXPECTED_EFFECT_MISMATCH: &str = "ERR_TON_EXPECTED_EFFECT_MISMATCH";
/// DENY: TON spend exceeds action or daily policy ceilings
pub const ERR_TON_SPEND_CEILING_EXCEEDED: &str = "ERR_TON_SPEND_CEILING_EXCEEDED";
/// ESCALATE: TON mainnet action requires policy approval before dispatch
pub const ERR_TON_MAINNET_REQUIRES_APPROVAL: &str = "ERR_TON_MAINNET_REQUIRES_APPROVAL";
/// ESCALATE: TON T3 action requires approval ceremony evidence
pub const ERR_TON_APPROVAL_CEREMONY_REQUIRED: &str = "ERR_TON_APPROVAL_CEREMONY_REQUIRED";
/// DENY: TON action requires an opaque wallet reference
pub const ERR_TON_WALLET_REF_REQUIRED: &str = "ERR_TON_WALLET_REF_REQUIRED";
/// DENY: Plaintext wallet mnemonic or private key material is forbidden
pub const ERR_TON_PLAINTEXT_MNEMONIC_FORBIDDEN: &str = "ERR_TON_PLAINTEXT_MNEMONIC_FORBIDDEN";
/// DENY: TON networked action requires an explicit sandbox network grant
pub const ERR_TON_NETWORK_GRANT_REQUIRED: &str = "ERR_TON_NETWORK_GRANT_REQUIRED";
/// DENY: Acton execution requires a valid HELM sandbox grant
pub const ERR_TON_SANDBOX_GRANT_REQUIRED: &str = "ERR_TON_SANDBOX_GRANT_REQUIRED";
/// DENY: TON source verification evidence is required before the action can dispatch
pub const ERR_TON_SOURCE_VERIFICATION_REQUIRED: &str = "ERR_TON_SOURCE_VERIFICATION_REQUIRED";
/// DENY: TON verifier dry-run evidence is required before final verification or deployment
pub const ERR_TON_VERIFY_DRY_RUN_REQUIRED: &str = "ERR_TON_VERIFY_DRY_RUN_REQUIRED";
/// DENY: TON verifier bytecode comparison failed
pub const ERR_TON_VERIFY_BYTECODE_MISMATCH: &str = "ERR_TON_VERIFY_BYTECODE_MISMATCH";
/// DENY/ESCALATE: Acton coverage result is below policy threshold
pub const ERR_TON_COVERAGE_THRESHOLD_FAILED: &str = "ERR_TON_COVERAGE_THRESHOLD_FAILED";
/// DENY/ESCALATE: Acton mutation score is below policy threshold
pub const ERR_TON_MUTATION_THRESHOLD_FAILED: &str = "ERR_TON_MUTATION_THRESHOLD_FAILED";
/// ESCALATE: Mainnet TON library publish or top-up requires approval
pub const ERR_TON_LIBRARY_MAINNET_REQUIRES_APPROVAL: &str = "ERR_TON_LIBRARY_MAINNET_REQUIRES_APPROVAL";
/// DENY: TON library publish or top-up exceeds spend ceilings
pub const ERR_TON_LIBRARY_SPEND_CEILING_EXCEEDED: &str = "ERR_TON_LIBRARY_SPEND_CEILING_EXCEEDED";
/// DENY: Connector observed output shape drift and failed closed
pub const ERR_CONNECTOR_CONTRACT_DRIFT: &str = "ERR_CONNECTOR_CONTRACT_DRIFT";
/// DENY: Sandboxed execution exhausted configured compute or gas budget
pub const ERR_COMPUTE_GAS_EXHAUSTED: &str = "ERR_COMPUTE_GAS_EXHAUSTED";
/// DENY: Sandboxed execution exceeded the configured wall-clock time budget
pub const ERR_COMPUTE_TIME_EXHAUSTED: &str = "ERR_COMPUTE_TIME_EXHAUSTED";
/// DENY: Side-effectful execution is missing a hash-linked HarnessTrace
pub const ERR_HARNESS_TRACE_REQUIRED: &str = "ERR_HARNESS_TRACE_REQUIRED";
/// DENY: Multi-artifact or write-bearing execution is missing a PlanTransaction
pub const ERR_PLAN_TRANSACTION_REQUIRED: &str = "ERR_PLAN_TRANSACTION_REQUIRED";
/// DENY/ESCALATE: PlanTransaction read/write sets conflict with another open transaction
pub const ERR_PLAN_TRANSACTION_CONFLICT: &str = "ERR_PLAN_TRANSACTION_CONFLICT";
/// DENY/ESCALATE: A declared plan assumption or dependency is stale before side-effect dispatch
pub const ERR_ASSUMPTION_STALE: &str = "ERR_ASSUMPTION_STALE";
/// ESCALATE: Mutation of connector, tool, sandbox, policy, verifier, evidence, or routing state
/// requires explicit approval
pub const ERR_HARNESS_MUTATION_REQUIRES_APPROVAL: &str = "ERR_HARNESS_MUTATION_REQUIRES_APPROVAL";
/// DENY: Passing tests were submitted without a declared verification scope
pub const ERR_GREEN_TEST_SCOPE_MISSING: &str = "ERR_GREEN_TEST_SCOPE_MISSING";
/// DENY: GUI or computer-use action is missing grounded screenshot and DOM/accessibility evidence
pub const ERR_GROUNDED_ACTION_REF_REQUIRED: &str = "ERR_GROUNDED_ACTION_REF_REQUIRED";
/// DENY: GUI or computer-use action postcondition was not verified
pub const ERR_GUI_POSTCONDITION_UNVERIFIED: &str = "ERR_GUI_POSTCONDITION_UNVERIFIED";
/// DENY: Safe Deprecation classified the hazard as terminal freeze
pub const SAFEDEP_TERMINAL_FREEZE: &str = "SAFEDEP_TERMINAL_FREEZE";
/// ESCALATE: Safe Deprecation classified the hazard as recoverable degraded narrowing
pub const SAFEDEP_DEGRADED_NARROWING: &str = "SAFEDEP_DEGRADED_NARROWING";
/// DENY: Safe Deprecation classified the hazard as read-only deprecation
pub const SAFEDEP_DEPRECATED_READONLY: &str = "SAFEDEP_DEPRECATED_READONLY";
/// DENY: Safe Deprecation continuity checkpoint is stale, replayed, expired, or rollbacked
pub const ERR_CONTINUITY_STALE: &str = "ERR_CONTINUITY_STALE";
/// DENY: Emergency capsule failed binding, expiry, subset-proof, or delegation validation
pub const ERR_EMERGENCY_CAPSULE_INVALID: &str = "ERR_EMERGENCY_CAPSULE_INVALID";
/// DENY: Hardware-bound emergency quorum is missing, duplicated, unauthorized, or revoked
pub const ERR_HARDWARE_QUORUM_UNBOUND: &str = "ERR_HARDWARE_QUORUM_UNBOUND";
/// DENY: Signed verifier-issued attestation result is required for emergency authorization
pub const ERR_ATTESTATION_RESULT_REQUIRED: &str = "ERR_ATTESTATION_RESULT_REQUIRED";
/// DENY: Dev, audit, mock, software-key, env-fallback, or unsigned overlay path is enabled
pub const ERR_DEV_FALLBACK_PRESENT: &str = "ERR_DEV_FALLBACK_PRESENT";
/// ESCALATE: Dispatched capability_id is not registered and is quarantined for review
pub const CAPABILITY_UNKNOWN: &str = "CAPABILITY_UNKNOWN";
/// DENY: Caller-pinned capability manifest hash does not match the registry revision
pub const CAPABILITY_MANIFEST_DRIFT: &str = "CAPABILITY_MANIFEST_DRIFT";
/// DENY: Task capability token is malformed, expired, revoked, exhausted, out of scope, or fails
/// signature/binding verification
pub const CAPABILITY_TOKEN_INVALID: &str = "CAPABILITY_TOKEN_INVALID";
/// DENY: Reversible non-read-only capability lacks a loadable, matching, valid rollback plan
pub const CAPABILITY_ROLLBACK_PLAN_INVALID: &str = "CAPABILITY_ROLLBACK_PLAN_INVALID";
/// DENY: Irreversible effect class cannot dispatch without an authoritative approval integration
pub const CAPABILITY_IRREVERSIBLE: &str = "CAPABILITY_IRREVERSIBLE";
/// DENY: The requesting principal is unknown to the tenant or disabled
pub const PRINCIPAL_INACTIVE: &str = "PRINCIPAL_INACTIVE";
/// DENY: No active mandate held by the principal covers the effect, or a mandate of its chain is
/// revoked
pub const MANDATE_INACTIVE: &str = "MANDATE_INACTIVE";
/// DENY: A mandate of the chain is outside its validity window
pub const MANDATE_OUTSIDE_VALIDITY: &str = "MANDATE_OUTSIDE_VALIDITY";
/// DENY: A mandate of the chain does not cover the effect type or target, or the effect type has no
/// control row
pub const EFFECT_OUT_OF_SCOPE: &str = "EFFECT_OUT_OF_SCOPE";
/// DENY: The effect's amount exceeds a per-call limit of the mandate chain
pub const PER_CALL_LIMIT: &str = "PER_CALL_LIMIT";
/// DENY: An amount or counter total overflows a 64-bit integer
pub const ARITHMETIC_OVERFLOW: &str = "ARITHMETIC_OVERFLOW";
/// DENY: The idempotency key was already used with a different request
pub const IDEMPOTENCY_CONFLICT: &str = "IDEMPOTENCY_CONFLICT";
/// DENY: A precondition the effect type declares does not hold, so no attempt was created
pub const PRECONDITION_FAILED: &str = "PRECONDITION_FAILED";
/// DENY: The approver is the requester; an approval needs a distinct principal
pub const APPROVER_NOT_DISTINCT: &str = "APPROVER_NOT_DISTINCT";
/// DENY: A distinct human approver rejected the escalated effect
pub const APPROVAL_REJECTED: &str = "APPROVAL_REJECTED";
/// DENY: Approving a high-risk, irreversible or authority-widening effect needs a step-up assertion
/// the request did not carry
pub const STEP_UP_REQUIRED: &str = "STEP_UP_REQUIRED";

/// Every registered reason code, in registry order.
pub const ALL: &[&str] = &[
    POLICY_VIOLATION,
    NO_POLICY_DEFINED,
    POLICY_NOT_READY,
    POLICY_HASH_MISMATCH,
    POLICY_SIGNATURE_INVALID,
    POLICY_EPOCH_CHANGED,
    PRG_EVALUATION_ERROR,
    SCHEMA_VIOLATION,
    PDP_DENY,
    PDP_ERROR,
    MISSING_REQUIREMENT,
    BUDGET_EXCEEDED,
    BUDGET_ERROR,
    TEMPORAL_INTERVENTION,
    TEMPORAL_THROTTLE,
    SESSION_RISK_MEMORY_DENY,
    ENVELOPE_INVALID,
    PROVENANCE_FAILURE,
    VERIFICATION_FAILURE,
    SANDBOX_VIOLATION,
    TENANT_ISOLATION,
    JURISDICTION_VIOLATION,
    SYSTEM_FROZEN,
    EMERGENCY_STOP_SCOPE_REQUIRED,
    EMERGENCY_STOP_UNVERIFIED,
    EMERGENCY_STOP_FENCED,
    CONTEXT_MISMATCH,
    DATA_EGRESS_BLOCKED,
    ERR_HOST_EGRESS_WITHOUT_INTENT,
    ERR_HOST_EGRESS_AFTER_DENY,
    ERR_HOST_RECEIPT_MISSING,
    ERR_HOST_DESTINATION_MISMATCH,
    ERR_HOST_VOLUME_EXCEEDED,
    ERR_HOST_PROCESS_UNBOUND,
    ERR_POLICY_DENIED_BUT_HOST_OBSERVED_EGRESS,
    IDENTITY_ISOLATION_VIOLATION,
    INSUFFICIENT_PRIVILEGE,
    APPROVAL_REQUIRED,
    APPROVAL_TIMEOUT,
    ACTIVATION_TRUST_UNAVAILABLE,
    ACTIVATION_RECORD_INVALID,
    ACTIVATION_BINDING_MISMATCH,
    ACTIVATION_CEILING_EXCEEDED,
    DELEGATION_INVALID,
    DELEGATION_SCOPE_VIOLATION,
    DELEGATION_PRINCIPAL_MISMATCH,
    AGENT_KILLED,
    TAINTED_INPUT_HIGH_RISK_DENY,
    PROMPT_INJECTION_DETECTED,
    UNICODE_OBFUSCATION_DETECTED,
    TAINTED_CREDENTIAL_ACCESS_DENY,
    TAINTED_SOFTWARE_PUBLISH_DENY,
    TAINTED_PRIVILEGED_INVOKE_DENY,
    TAINTED_DATA_EGRESS_DENY,
    TAINTED_HIGH_RISK_ESCALATE,
    SEMANTIC_THREAT_REVIEW_REQUIRED,
    ERR_TON_ACTON_UNKNOWN_COMMAND,
    ERR_TON_ACTON_UNSUPPORTED_VERSION,
    ERR_TON_TOLK_COMPILER_UNPINNED,
    ERR_TON_TOLK_COMPILER_MISMATCH,
    ERR_TON_ACTON_ARGV_REJECTED,
    ERR_TON_ACTON_RAW_SHELL_FORBIDDEN,
    ERR_TON_ACTON_GENERIC_MAINNET_SCRIPT_DENIED,
    ERR_TON_SCRIPT_MANIFEST_REQUIRED,
    ERR_TON_SCRIPT_MANIFEST_HASH_MISMATCH,
    ERR_TON_EXPECTED_EFFECT_MISMATCH,
    ERR_TON_SPEND_CEILING_EXCEEDED,
    ERR_TON_MAINNET_REQUIRES_APPROVAL,
    ERR_TON_APPROVAL_CEREMONY_REQUIRED,
    ERR_TON_WALLET_REF_REQUIRED,
    ERR_TON_PLAINTEXT_MNEMONIC_FORBIDDEN,
    ERR_TON_NETWORK_GRANT_REQUIRED,
    ERR_TON_SANDBOX_GRANT_REQUIRED,
    ERR_TON_SOURCE_VERIFICATION_REQUIRED,
    ERR_TON_VERIFY_DRY_RUN_REQUIRED,
    ERR_TON_VERIFY_BYTECODE_MISMATCH,
    ERR_TON_COVERAGE_THRESHOLD_FAILED,
    ERR_TON_MUTATION_THRESHOLD_FAILED,
    ERR_TON_LIBRARY_MAINNET_REQUIRES_APPROVAL,
    ERR_TON_LIBRARY_SPEND_CEILING_EXCEEDED,
    ERR_CONNECTOR_CONTRACT_DRIFT,
    ERR_COMPUTE_GAS_EXHAUSTED,
    ERR_COMPUTE_TIME_EXHAUSTED,
    ERR_HARNESS_TRACE_REQUIRED,
    ERR_PLAN_TRANSACTION_REQUIRED,
    ERR_PLAN_TRANSACTION_CONFLICT,
    ERR_ASSUMPTION_STALE,
    ERR_HARNESS_MUTATION_REQUIRES_APPROVAL,
    ERR_GREEN_TEST_SCOPE_MISSING,
    ERR_GROUNDED_ACTION_REF_REQUIRED,
    ERR_GUI_POSTCONDITION_UNVERIFIED,
    SAFEDEP_TERMINAL_FREEZE,
    SAFEDEP_DEGRADED_NARROWING,
    SAFEDEP_DEPRECATED_READONLY,
    ERR_CONTINUITY_STALE,
    ERR_EMERGENCY_CAPSULE_INVALID,
    ERR_HARDWARE_QUORUM_UNBOUND,
    ERR_ATTESTATION_RESULT_REQUIRED,
    ERR_DEV_FALLBACK_PRESENT,
    CAPABILITY_UNKNOWN,
    CAPABILITY_MANIFEST_DRIFT,
    CAPABILITY_TOKEN_INVALID,
    CAPABILITY_ROLLBACK_PLAN_INVALID,
    CAPABILITY_IRREVERSIBLE,
    PRINCIPAL_INACTIVE,
    MANDATE_INACTIVE,
    MANDATE_OUTSIDE_VALIDITY,
    EFFECT_OUT_OF_SCOPE,
    PER_CALL_LIMIT,
    ARITHMETIC_OVERFLOW,
    IDEMPOTENCY_CONFLICT,
    PRECONDITION_FAILED,
    APPROVER_NOT_DISTINCT,
    APPROVAL_REJECTED,
    STEP_UP_REQUIRED,
];

/// Whether `code` is in the registry.
pub fn is_registered(code: &str) -> bool {
    ALL.contains(&code)
}
