// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/contracts/attestation.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attestation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PhenotypeHash   string                 `protobuf:"bytes,1,opt,name=phenotype_hash,json=phenotypeHash,proto3" json:"phenotype_hash,omitempty"`
	ToolFingerprint string                 `protobuf:"bytes,2,opt,name=tool_fingerprint,json=toolFingerprint,proto3" json:"tool_fingerprint,omitempty"`
	ActionClass     string                 `protobuf:"bytes,3,opt,name=action_class,json=actionClass,proto3" json:"action_class,omitempty"`
	EnvFingerprint  string                 `protobuf:"bytes,4,opt,name=env_fingerprint,json=envFingerprint,proto3" json:"env_fingerprint,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IssuerId        string                 `protobuf:"bytes,7,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Signature       []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Constraints     []string               `protobuf:"bytes,9,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_pkg_contracts_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetPhenotypeHash() string {
	if x != nil {
		return x.PhenotypeHash
	}
	return ""
}

func (x *Attestation) GetToolFingerprint() string {
	if x != nil {
		return x.ToolFingerprint
	}
	return ""
}

func (x *Attestation) GetActionClass() string {
	if x != nil {
		return x.ActionClass
	}
	return ""
}

func (x *Attestation) GetEnvFingerprint() string {
	if x != nil {
		return x.EnvFingerprint
	}
	return ""
}

func (x *Attestation) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Attestation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Attestation) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *Attestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Attestation) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

var File_pkg_contracts_attestation_proto protoreflect.FileDescriptor

const file_pkg_contracts_attestation_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/contracts/attestation.proto\x12\tcontracts\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x02\n" +
	"\vAttestation\x12%\n" +
	"\x0ephenotype_hash\x18\x01 \x01(\tR\rphenotypeHash\x12)\n" +
	"\x10tool_fingerprint\x18\x02 \x01(\tR\x0ftoolFingerprint\x12!\n" +
	"\faction_class\x18\x03 \x01(\tR\vactionClass\x12'\n" +
	"\x0fenv_fingerprint\x18\x04 \x01(\tR\x0eenvFingerprint\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tissuer_id\x18\a \x01(\tR\bissuerId\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x12 \n" +
	"\vconstraints\x18\t \x03(\tR\vconstraintsB\x15Z\x13./pkg/interlock/apib\x06proto3"

var (
	file_pkg_contracts_attestation_proto_rawDescOnce sync.Once
	file_pkg_contracts_attestation_proto_rawDescData []byte
)

func file_pkg_contracts_attestation_proto_rawDescGZIP() []byte {
	file_pkg_contracts_attestation_proto_rawDescOnce.Do(func() {
		file_pkg_contracts_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_contracts_attestation_proto_rawDesc), len(file_pkg_contracts_attestation_proto_rawDesc)))
	})
	return file_pkg_contracts_attestation_proto_rawDescData
}

var file_pkg_contracts_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_contracts_attestation_proto_goTypes = []any{
	(*Attestation)(nil),           // 0: contracts.Attestation
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pkg_contracts_attestation_proto_depIdxs = []int32{
	1, // 0: contracts.Attestation.issued_at:type_name -> google.protobuf.Timestamp
	1, // 1: contracts.Attestation.expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_contracts_attestation_proto_init() }
func file_pkg_contracts_attestation_proto_init() {
	if File_pkg_contracts_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_contracts_attestation_proto_rawDesc), len(file_pkg_contracts_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_contracts_attestation_proto_goTypes,
		DependencyIndexes: file_pkg_contracts_attestation_proto_depIdxs,
		MessageInfos:      file_pkg_contracts_attestation_proto_msgTypes,
	}.Build()
	File_pkg_contracts_attestation_proto = out.File
	file_pkg_contracts_attestation_proto_goTypes = nil
	file_pkg_contracts_attestation_proto_depIdxs = nil
}
