// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/contracts/decision.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_ALLOW       Verdict = 1
	Verdict_VERDICT_DENY        Verdict = 2
	Verdict_VERDICT_ESCALATE    Verdict = 3
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_ALLOW",
		2: "VERDICT_DENY",
		3: "VERDICT_ESCALATE",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_ALLOW":       1,
		"VERDICT_DENY":        2,
		"VERDICT_ESCALATE":    3,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_contracts_decision_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_pkg_contracts_decision_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_pkg_contracts_decision_proto_rawDescGZIP(), []int{0}
}

// DecisionInterventionMetadata carries the Temporal Guardian fields included
// in the v2 decision signing envelope. Durations are encoded as nanoseconds to
// preserve Go time.Duration exactly.
type DecisionInterventionMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ReasonCode        string                 `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	WaitDurationNanos int64                  `protobuf:"varint,3,opt,name=wait_duration_nanos,json=waitDurationNanos,proto3" json:"wait_duration_nanos,omitempty"`
	TokensSaved       int64                  `protobuf:"varint,4,opt,name=tokens_saved,json=tokensSaved,proto3" json:"tokens_saved,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DecisionInterventionMetadata) Reset() {
	*x = DecisionInterventionMetadata{}
	mi := &file_pkg_contracts_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionInterventionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionInterventionMetadata) ProtoMessage() {}

func (x *DecisionInterventionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionInterventionMetadata.ProtoReflect.Descriptor instead.
func (*DecisionInterventionMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_decision_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionInterventionMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DecisionInterventionMetadata) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *DecisionInterventionMetadata) GetWaitDurationNanos() int64 {
	if x != nil {
		return x.WaitDurationNanos
	}
	return 0
}

func (x *DecisionInterventionMetadata) GetTokensSaved() int64 {
	if x != nil {
		return x.TokensSaved
	}
	return 0
}

type DecisionRecord struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProposalId             string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	StepId                 string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	PhenotypeHash          string                 `protobuf:"bytes,3,opt,name=phenotype_hash,json=phenotypeHash,proto3" json:"phenotype_hash,omitempty"`
	StateCursor            string                 `protobuf:"bytes,4,opt,name=state_cursor,json=stateCursor,proto3" json:"state_cursor,omitempty"`
	EnvFingerprint         string                 `protobuf:"bytes,5,opt,name=env_fingerprint,json=envFingerprint,proto3" json:"env_fingerprint,omitempty"`
	Verdict                Verdict                `protobuf:"varint,6,opt,name=verdict,proto3,enum=contracts.Verdict" json:"verdict,omitempty"`
	Reason                 string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature              []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	DecisionHash           string                 `protobuf:"bytes,10,opt,name=decision_hash,json=decisionHash,proto3" json:"decision_hash,omitempty"` // Canonical hash of the fields (excluding signature/decision_hash)
	TrajectoryRiskScore    float64                `protobuf:"fixed64,11,opt,name=trajectory_risk_score,json=trajectoryRiskScore,proto3" json:"trajectory_risk_score,omitempty"`
	SessionCentroidHash    string                 `protobuf:"bytes,12,opt,name=session_centroid_hash,json=sessionCentroidHash,proto3" json:"session_centroid_hash,omitempty"`
	RiskAccumulationWindow int32                  `protobuf:"varint,13,opt,name=risk_accumulation_window,json=riskAccumulationWindow,proto3" json:"risk_accumulation_window,omitempty"`
	// Request tuple cryptographically bound by signature_schema v2.
	SubjectId string `protobuf:"bytes,14,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Action    string `protobuf:"bytes,15,opt,name=action,proto3" json:"action,omitempty"`
	Resource  string `protobuf:"bytes,16,opt,name=resource,proto3" json:"resource,omitempty"`
	// Empty denotes the legacy v1 decision preimage. v2 currently uses
	// "helm.decision.signature.v2" and also binds signature_type.
	SignatureSchema string `protobuf:"bytes,17,opt,name=signature_schema,json=signatureSchema,proto3" json:"signature_schema,omitempty"`
	SignatureType   string `protobuf:"bytes,18,opt,name=signature_type,json=signatureType,proto3" json:"signature_type,omitempty"`
	// Complete additive v2 signing envelope. Legacy fields above stay in place
	// for wire compatibility; v2 consumers must use these explicit fields.
	Id                 string                        `protobuf:"bytes,19,opt,name=id,proto3" json:"id,omitempty"`
	PolicyVersion      string                        `protobuf:"bytes,20,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	EffectDigest       string                        `protobuf:"bytes,21,opt,name=effect_digest,json=effectDigest,proto3" json:"effect_digest,omitempty"`
	PolicyBackend      string                        `protobuf:"bytes,22,opt,name=policy_backend,json=policyBackend,proto3" json:"policy_backend,omitempty"`
	PolicyContentHash  string                        `protobuf:"bytes,23,opt,name=policy_content_hash,json=policyContentHash,proto3" json:"policy_content_hash,omitempty"`
	PolicyEpoch        string                        `protobuf:"bytes,24,opt,name=policy_epoch,json=policyEpoch,proto3" json:"policy_epoch,omitempty"`
	PolicyDecisionHash string                        `protobuf:"bytes,25,opt,name=policy_decision_hash,json=policyDecisionHash,proto3" json:"policy_decision_hash,omitempty"`
	Snapshot           string                        `protobuf:"bytes,26,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	ReasonCode         string                        `protobuf:"bytes,27,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	RequirementSetHash string                        `protobuf:"bytes,28,opt,name=requirement_set_hash,json=requirementSetHash,proto3" json:"requirement_set_hash,omitempty"`
	Intervention       *DecisionInterventionMetadata `protobuf:"bytes,29,opt,name=intervention,proto3" json:"intervention,omitempty"`
	// Legacy signature is bytes. v2 preserves its canonical text form so a
	// decoded record can be verified without an implicit representation change.
	SignatureText string `protobuf:"bytes,30,opt,name=signature_text,json=signatureText,proto3" json:"signature_text,omitempty"`
	// Legacy Verdict predates ESCALATE; v2 uses this explicit canonical text.
	VerdictText string `protobuf:"bytes,31,opt,name=verdict_text,json=verdictText,proto3" json:"verdict_text,omitempty"`
	// InputContext is intentionally unsigned, but retaining it avoids a lossy
	// EffectInterlock DecisionRecord transport.
	InputContextJson []byte `protobuf:"bytes,32,opt,name=input_context_json,json=inputContextJson,proto3" json:"input_context_json,omitempty"`
	// Trusted scope is signed in the v2 decision envelope. It is populated by
	// authenticated adapters, never inferred from input_context_json.
	TenantId      string `protobuf:"bytes,33,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId   string `protobuf:"bytes,34,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SessionId     string `protobuf:"bytes,35,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRecord) Reset() {
	*x = DecisionRecord{}
	mi := &file_pkg_contracts_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRecord) ProtoMessage() {}

func (x *DecisionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRecord.ProtoReflect.Descriptor instead.
func (*DecisionRecord) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_decision_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionRecord) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *DecisionRecord) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *DecisionRecord) GetPhenotypeHash() string {
	if x != nil {
		return x.PhenotypeHash
	}
	return ""
}

func (x *DecisionRecord) GetStateCursor() string {
	if x != nil {
		return x.StateCursor
	}
	return ""
}

func (x *DecisionRecord) GetEnvFingerprint() string {
	if x != nil {
		return x.EnvFingerprint
	}
	return ""
}

func (x *DecisionRecord) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *DecisionRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DecisionRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DecisionRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DecisionRecord) GetDecisionHash() string {
	if x != nil {
		return x.DecisionHash
	}
	return ""
}

func (x *DecisionRecord) GetTrajectoryRiskScore() float64 {
	if x != nil {
		return x.TrajectoryRiskScore
	}
	return 0
}

func (x *DecisionRecord) GetSessionCentroidHash() string {
	if x != nil {
		return x.SessionCentroidHash
	}
	return ""
}

func (x *DecisionRecord) GetRiskAccumulationWindow() int32 {
	if x != nil {
		return x.RiskAccumulationWindow
	}
	return 0
}

func (x *DecisionRecord) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *DecisionRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DecisionRecord) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *DecisionRecord) GetSignatureSchema() string {
	if x != nil {
		return x.SignatureSchema
	}
	return ""
}

func (x *DecisionRecord) GetSignatureType() string {
	if x != nil {
		return x.SignatureType
	}
	return ""
}

func (x *DecisionRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecisionRecord) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *DecisionRecord) GetEffectDigest() string {
	if x != nil {
		return x.EffectDigest
	}
	return ""
}

func (x *DecisionRecord) GetPolicyBackend() string {
	if x != nil {
		return x.PolicyBackend
	}
	return ""
}

func (x *DecisionRecord) GetPolicyContentHash() string {
	if x != nil {
		return x.PolicyContentHash
	}
	return ""
}

func (x *DecisionRecord) GetPolicyEpoch() string {
	if x != nil {
		return x.PolicyEpoch
	}
	return ""
}

func (x *DecisionRecord) GetPolicyDecisionHash() string {
	if x != nil {
		return x.PolicyDecisionHash
	}
	return ""
}

func (x *DecisionRecord) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *DecisionRecord) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *DecisionRecord) GetRequirementSetHash() string {
	if x != nil {
		return x.RequirementSetHash
	}
	return ""
}

func (x *DecisionRecord) GetIntervention() *DecisionInterventionMetadata {
	if x != nil {
		return x.Intervention
	}
	return nil
}

func (x *DecisionRecord) GetSignatureText() string {
	if x != nil {
		return x.SignatureText
	}
	return ""
}

func (x *DecisionRecord) GetVerdictText() string {
	if x != nil {
		return x.VerdictText
	}
	return ""
}

func (x *DecisionRecord) GetInputContextJson() []byte {
	if x != nil {
		return x.InputContextJson
	}
	return nil
}

func (x *DecisionRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DecisionRecord) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DecisionRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_pkg_contracts_decision_proto protoreflect.FileDescriptor

const file_pkg_contracts_decision_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/contracts/decision.proto\x12\tcontracts\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\x1cDecisionInterventionMetadata\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vreason_code\x18\x02 \x01(\tR\n" +
	"reasonCode\x12.\n" +
	"\x13wait_duration_nanos\x18\x03 \x01(\x03R\x11waitDurationNanos\x12!\n" +
	"\ftokens_saved\x18\x04 \x01(\x03R\vtokensSaved\"\xe2\n" +
	"\n" +
	"\x0eDecisionRecord\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12%\n" +
	"\x0ephenotype_hash\x18\x03 \x01(\tR\rphenotypeHash\x12!\n" +
	"\fstate_cursor\x18\x04 \x01(\tR\vstateCursor\x12'\n" +
	"\x0fenv_fingerprint\x18\x05 \x01(\tR\x0eenvFingerprint\x12,\n" +
	"\averdict\x18\x06 \x01(\x0e2\x12.contracts.VerdictR\averdict\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12#\n" +
	"\rdecision_hash\x18\n" +
	" \x01(\tR\fdecisionHash\x122\n" +
	"\x15trajectory_risk_score\x18\v \x01(\x01R\x13trajectoryRiskScore\x122\n" +
	"\x15session_centroid_hash\x18\f \x01(\tR\x13sessionCentroidHash\x128\n" +
	"\x18risk_accumulation_window\x18\r \x01(\x05R\x16riskAccumulationWindow\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x0e \x01(\tR\tsubjectId\x12\x16\n" +
	"\x06action\x18\x0f \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x10 \x01(\tR\bresource\x12)\n" +
	"\x10signature_schema\x18\x11 \x01(\tR\x0fsignatureSchema\x12%\n" +
	"\x0esignature_type\x18\x12 \x01(\tR\rsignatureType\x12\x0e\n" +
	"\x02id\x18\x13 \x01(\tR\x02id\x12%\n" +
	"\x0epolicy_version\x18\x14 \x01(\tR\rpolicyVersion\x12#\n" +
	"\reffect_digest\x18\x15 \x01(\tR\feffectDigest\x12%\n" +
	"\x0epolicy_backend\x18\x16 \x01(\tR\rpolicyBackend\x12.\n" +
	"\x13policy_content_hash\x18\x17 \x01(\tR\x11policyContentHash\x12!\n" +
	"\fpolicy_epoch\x18\x18 \x01(\tR\vpolicyEpoch\x120\n" +
	"\x14policy_decision_hash\x18\x19 \x01(\tR\x12policyDecisionHash\x12\x1a\n" +
	"\bsnapshot\x18\x1a \x01(\tR\bsnapshot\x12\x1f\n" +
	"\vreason_code\x18\x1b \x01(\tR\n" +
	"reasonCode\x120\n" +
	"\x14requirement_set_hash\x18\x1c \x01(\tR\x12requirementSetHash\x12K\n" +
	"\fintervention\x18\x1d \x01(\v2'.contracts.DecisionInterventionMetadataR\fintervention\x12%\n" +
	"\x0esignature_text\x18\x1e \x01(\tR\rsignatureText\x12!\n" +
	"\fverdict_text\x18\x1f \x01(\tR\vverdictText\x12,\n" +
	"\x12input_context_json\x18  \x01(\fR\x10inputContextJson\x12\x1b\n" +
	"\ttenant_id\x18! \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\" \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"session_id\x18# \x01(\tR\tsessionId*]\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rVERDICT_ALLOW\x10\x01\x12\x10\n" +
	"\fVERDICT_DENY\x10\x02\x12\x14\n" +
	"\x10VERDICT_ESCALATE\x10\x03B\x15Z\x13./pkg/interlock/apib\x06proto3"

var (
	file_pkg_contracts_decision_proto_rawDescOnce sync.Once
	file_pkg_contracts_decision_proto_rawDescData []byte
)

func file_pkg_contracts_decision_proto_rawDescGZIP() []byte {
	file_pkg_contracts_decision_proto_rawDescOnce.Do(func() {
		file_pkg_contracts_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_contracts_decision_proto_rawDesc), len(file_pkg_contracts_decision_proto_rawDesc)))
	})
	return file_pkg_contracts_decision_proto_rawDescData
}

var file_pkg_contracts_decision_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_contracts_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_contracts_decision_proto_goTypes = []any{
	(Verdict)(0),                         // 0: contracts.Verdict
	(*DecisionInterventionMetadata)(nil), // 1: contracts.DecisionInterventionMetadata
	(*DecisionRecord)(nil),               // 2: contracts.DecisionRecord
	(*timestamppb.Timestamp)(nil),        // 3: google.protobuf.Timestamp
}
var file_pkg_contracts_decision_proto_depIdxs = []int32{
	0, // 0: contracts.DecisionRecord.verdict:type_name -> contracts.Verdict
	3, // 1: contracts.DecisionRecord.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: contracts.DecisionRecord.intervention:type_name -> contracts.DecisionInterventionMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_contracts_decision_proto_init() }
func file_pkg_contracts_decision_proto_init() {
	if File_pkg_contracts_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_contracts_decision_proto_rawDesc), len(file_pkg_contracts_decision_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_contracts_decision_proto_goTypes,
		DependencyIndexes: file_pkg_contracts_decision_proto_depIdxs,
		EnumInfos:         file_pkg_contracts_decision_proto_enumTypes,
		MessageInfos:      file_pkg_contracts_decision_proto_msgTypes,
	}.Build()
	File_pkg_contracts_decision_proto = out.File
	file_pkg_contracts_decision_proto_goTypes = nil
	file_pkg_contracts_decision_proto_depIdxs = nil
}
