// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/contracts/effect.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EffectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposalId      string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	StepId          string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	ActionClass     string                 `protobuf:"bytes,3,opt,name=action_class,json=actionClass,proto3" json:"action_class,omitempty"`
	ToolName        string                 `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ParamsJson      []byte                 `protobuf:"bytes,5,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // Canonical JSON bytes
	DecisionRecord  *DecisionRecord        `protobuf:"bytes,6,opt,name=decision_record,json=decisionRecord,proto3" json:"decision_record,omitempty"`
	Attestation     *Attestation           `protobuf:"bytes,7,opt,name=attestation,proto3" json:"attestation,omitempty"`
	ToolFingerprint string                 `protobuf:"bytes,8,opt,name=tool_fingerprint,json=toolFingerprint,proto3" json:"tool_fingerprint,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EffectRequest) Reset() {
	*x = EffectRequest{}
	mi := &file_pkg_contracts_effect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectRequest) ProtoMessage() {}

func (x *EffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_effect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectRequest.ProtoReflect.Descriptor instead.
func (*EffectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_effect_proto_rawDescGZIP(), []int{0}
}

func (x *EffectRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *EffectRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *EffectRequest) GetActionClass() string {
	if x != nil {
		return x.ActionClass
	}
	return ""
}

func (x *EffectRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *EffectRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *EffectRequest) GetDecisionRecord() *DecisionRecord {
	if x != nil {
		return x.DecisionRecord
	}
	return nil
}

func (x *EffectRequest) GetAttestation() *Attestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *EffectRequest) GetToolFingerprint() string {
	if x != nil {
		return x.ToolFingerprint
	}
	return ""
}

func (x *EffectRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type EffectResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Receipt              *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Artifacts            []*ArtifactRef         `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	NormalizedOutputJson []byte                 `protobuf:"bytes,3,opt,name=normalized_output_json,json=normalizedOutputJson,proto3" json:"normalized_output_json,omitempty"`
	ErrorClass           string                 `protobuf:"bytes,4,opt,name=error_class,json=errorClass,proto3" json:"error_class,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EffectResult) Reset() {
	*x = EffectResult{}
	mi := &file_pkg_contracts_effect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectResult) ProtoMessage() {}

func (x *EffectResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_effect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectResult.ProtoReflect.Descriptor instead.
func (*EffectResult) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_effect_proto_rawDescGZIP(), []int{1}
}

func (x *EffectResult) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *EffectResult) GetArtifacts() []*ArtifactRef {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *EffectResult) GetNormalizedOutputJson() []byte {
	if x != nil {
		return x.NormalizedOutputJson
	}
	return nil
}

func (x *EffectResult) GetErrorClass() string {
	if x != nil {
		return x.ErrorClass
	}
	return ""
}

type Receipt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToolFingerprint string                 `protobuf:"bytes,2,opt,name=tool_fingerprint,json=toolFingerprint,proto3" json:"tool_fingerprint,omitempty"`
	ExternalId      string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // e.g., Stripe ID
	EvidenceHash    string                 `protobuf:"bytes,4,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	OracleTick      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=oracle_tick,json=oracleTick,proto3" json:"oracle_tick,omitempty"`
	Meta            map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_pkg_contracts_effect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_effect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_effect_proto_rawDescGZIP(), []int{2}
}

func (x *Receipt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Receipt) GetToolFingerprint() string {
	if x != nil {
		return x.ToolFingerprint
	}
	return ""
}

func (x *Receipt) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Receipt) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *Receipt) GetOracleTick() *timestamppb.Timestamp {
	if x != nil {
		return x.OracleTick
	}
	return nil
}

func (x *Receipt) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Dataclass     string                 `protobuf:"bytes,3,opt,name=dataclass,proto3" json:"dataclass,omitempty"` // PUBLIC, INTERNAL, SENSITIVE
	ManifestHash  string                 `protobuf:"bytes,4,opt,name=manifest_hash,json=manifestHash,proto3" json:"manifest_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_pkg_contracts_effect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_effect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_effect_proto_rawDescGZIP(), []int{3}
}

func (x *ArtifactRef) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ArtifactRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArtifactRef) GetDataclass() string {
	if x != nil {
		return x.Dataclass
	}
	return ""
}

func (x *ArtifactRef) GetManifestHash() string {
	if x != nil {
		return x.ManifestHash
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_contracts_effect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_effect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_effect_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_contracts_effect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_contracts_effect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_contracts_effect_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pkg_contracts_effect_proto protoreflect.FileDescriptor

const file_pkg_contracts_effect_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/contracts/effect.proto\x12\tcontracts\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cpkg/contracts/decision.proto\x1a\x1fpkg/contracts/attestation.proto\"\xfc\x02\n" +
	"\rEffectRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12!\n" +
	"\faction_class\x18\x03 \x01(\tR\vactionClass\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12\x1f\n" +
	"\vparams_json\x18\x05 \x01(\fR\n" +
	"paramsJson\x12B\n" +
	"\x0fdecision_record\x18\x06 \x01(\v2\x19.contracts.DecisionRecordR\x0edecisionRecord\x128\n" +
	"\vattestation\x18\a \x01(\v2\x16.contracts.AttestationR\vattestation\x12)\n" +
	"\x10tool_fingerprint\x18\b \x01(\tR\x0ftoolFingerprint\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\"\xc9\x01\n" +
	"\fEffectResult\x12,\n" +
	"\areceipt\x18\x01 \x01(\v2\x12.contracts.ReceiptR\areceipt\x124\n" +
	"\tartifacts\x18\x02 \x03(\v2\x16.contracts.ArtifactRefR\tartifacts\x124\n" +
	"\x16normalized_output_json\x18\x03 \x01(\fR\x14normalizedOutputJson\x12\x1f\n" +
	"\verror_class\x18\x04 \x01(\tR\n" +
	"errorClass\"\xb2\x02\n" +
	"\aReceipt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10tool_fingerprint\x18\x02 \x01(\tR\x0ftoolFingerprint\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12#\n" +
	"\revidence_hash\x18\x04 \x01(\tR\fevidenceHash\x12;\n" +
	"\voracle_tick\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"oracleTick\x120\n" +
	"\x04meta\x18\x06 \x03(\v2\x1c.contracts.Receipt.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\vArtifactRef\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1c\n" +
	"\tdataclass\x18\x03 \x01(\tR\tdataclass\x12#\n" +
	"\rmanifest_hash\x18\x04 \x01(\tR\fmanifestHash\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x94\x01\n" +
	"\x0fEffectInterlock\x12B\n" +
	"\rExecuteEffect\x12\x18.contracts.EffectRequest\x1a\x17.contracts.EffectResult\x12=\n" +
	"\x06Health\x12\x18.contracts.HealthRequest\x1a\x19.contracts.HealthResponseB\x15Z\x13./pkg/interlock/apib\x06proto3"

var (
	file_pkg_contracts_effect_proto_rawDescOnce sync.Once
	file_pkg_contracts_effect_proto_rawDescData []byte
)

func file_pkg_contracts_effect_proto_rawDescGZIP() []byte {
	file_pkg_contracts_effect_proto_rawDescOnce.Do(func() {
		file_pkg_contracts_effect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_contracts_effect_proto_rawDesc), len(file_pkg_contracts_effect_proto_rawDesc)))
	})
	return file_pkg_contracts_effect_proto_rawDescData
}

var file_pkg_contracts_effect_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_contracts_effect_proto_goTypes = []any{
	(*EffectRequest)(nil),         // 0: contracts.EffectRequest
	(*EffectResult)(nil),          // 1: contracts.EffectResult
	(*Receipt)(nil),               // 2: contracts.Receipt
	(*ArtifactRef)(nil),           // 3: contracts.ArtifactRef
	(*HealthRequest)(nil),         // 4: contracts.HealthRequest
	(*HealthResponse)(nil),        // 5: contracts.HealthResponse
	nil,                           // 6: contracts.Receipt.MetaEntry
	(*DecisionRecord)(nil),        // 7: contracts.DecisionRecord
	(*Attestation)(nil),           // 8: contracts.Attestation
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_pkg_contracts_effect_proto_depIdxs = []int32{
	7, // 0: contracts.EffectRequest.decision_record:type_name -> contracts.DecisionRecord
	8, // 1: contracts.EffectRequest.attestation:type_name -> contracts.Attestation
	2, // 2: contracts.EffectResult.receipt:type_name -> contracts.Receipt
	3, // 3: contracts.EffectResult.artifacts:type_name -> contracts.ArtifactRef
	9, // 4: contracts.Receipt.oracle_tick:type_name -> google.protobuf.Timestamp
	6, // 5: contracts.Receipt.meta:type_name -> contracts.Receipt.MetaEntry
	0, // 6: contracts.EffectInterlock.ExecuteEffect:input_type -> contracts.EffectRequest
	4, // 7: contracts.EffectInterlock.Health:input_type -> contracts.HealthRequest
	1, // 8: contracts.EffectInterlock.ExecuteEffect:output_type -> contracts.EffectResult
	5, // 9: contracts.EffectInterlock.Health:output_type -> contracts.HealthResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_contracts_effect_proto_init() }
func file_pkg_contracts_effect_proto_init() {
	if File_pkg_contracts_effect_proto != nil {
		return
	}
	file_pkg_contracts_decision_proto_init()
	file_pkg_contracts_attestation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_contracts_effect_proto_rawDesc), len(file_pkg_contracts_effect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_contracts_effect_proto_goTypes,
		DependencyIndexes: file_pkg_contracts_effect_proto_depIdxs,
		MessageInfos:      file_pkg_contracts_effect_proto_msgTypes,
	}.Build()
	File_pkg_contracts_effect_proto = out.File
	file_pkg_contracts_effect_proto_goTypes = nil
	file_pkg_contracts_effect_proto_depIdxs = nil
}
