// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helm/errors/v1/errors.proto
// Protobuf Java Version: 4.34.1

package helm.errors.v1;

@com.google.protobuf.Generated
public final class Errors extends com.google.protobuf.GeneratedFile {
  private Errors() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Errors");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrorDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:helm.errors.v1.ErrorDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
     * an open string. Empty when the error carries no registered code.
     * </pre>
     *
     * <code>string reason_code = 1;</code>
     * @return The reasonCode.
     */
    java.lang.String getReasonCode();
    /**
     * <pre>
     * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
     * an open string. Empty when the error carries no registered code.
     * </pre>
     *
     * <code>string reason_code = 1;</code>
     * @return The bytes for reasonCode.
     */
    com.google.protobuf.ByteString
        getReasonCodeBytes();

    /**
     * <pre>
     * Whether repeating the same request can succeed.
     * </pre>
     *
     * <code>bool retryable = 2;</code>
     * @return The retryable.
     */
    boolean getRetryable();
  }
  /**
   * <pre>
   * ErrorDetail is the HELM detail of an API error.
   * </pre>
   *
   * Protobuf type {@code helm.errors.v1.ErrorDetail}
   */
  public static final class ErrorDetail extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:helm.errors.v1.ErrorDetail)
      ErrorDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "ErrorDetail");
    }
    // Use ErrorDetail.newBuilder() to construct.
    private ErrorDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ErrorDetail() {
      reasonCode_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return helm.errors.v1.Errors.internal_static_helm_errors_v1_ErrorDetail_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return helm.errors.v1.Errors.internal_static_helm_errors_v1_ErrorDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return helm.errors.v1.Errors.internal_static_helm_errors_v1_ErrorDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              helm.errors.v1.Errors.ErrorDetail.class, helm.errors.v1.Errors.ErrorDetail.Builder.class);
    }

    public static final int REASON_CODE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object reasonCode_ = "";
    /**
     * <pre>
     * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
     * an open string. Empty when the error carries no registered code.
     * </pre>
     *
     * <code>string reason_code = 1;</code>
     * @return The reasonCode.
     */
    @java.lang.Override
    public java.lang.String getReasonCode() {
      java.lang.Object ref = reasonCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reasonCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
     * an open string. Empty when the error carries no registered code.
     * </pre>
     *
     * <code>string reason_code = 1;</code>
     * @return The bytes for reasonCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonCodeBytes() {
      java.lang.Object ref = reasonCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reasonCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETRYABLE_FIELD_NUMBER = 2;
    private boolean retryable_ = false;
    /**
     * <pre>
     * Whether repeating the same request can succeed.
     * </pre>
     *
     * <code>bool retryable = 2;</code>
     * @return The retryable.
     */
    @java.lang.Override
    public boolean getRetryable() {
      return retryable_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reasonCode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, reasonCode_);
      }
      if (retryable_ != false) {
        output.writeBool(2, retryable_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reasonCode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, reasonCode_);
      }
      if (retryable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, retryable_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof helm.errors.v1.Errors.ErrorDetail)) {
        return super.equals(obj);
      }
      helm.errors.v1.Errors.ErrorDetail other = (helm.errors.v1.Errors.ErrorDetail) obj;

      if (!getReasonCode()
          .equals(other.getReasonCode())) return false;
      if (getRetryable()
          != other.getRetryable()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REASON_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getReasonCode().hashCode();
      hash = (37 * hash) + RETRYABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRetryable());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static helm.errors.v1.Errors.ErrorDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static helm.errors.v1.Errors.ErrorDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static helm.errors.v1.Errors.ErrorDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(helm.errors.v1.Errors.ErrorDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ErrorDetail is the HELM detail of an API error.
     * </pre>
     *
     * Protobuf type {@code helm.errors.v1.ErrorDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:helm.errors.v1.ErrorDetail)
        helm.errors.v1.Errors.ErrorDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return helm.errors.v1.Errors.internal_static_helm_errors_v1_ErrorDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return helm.errors.v1.Errors.internal_static_helm_errors_v1_ErrorDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                helm.errors.v1.Errors.ErrorDetail.class, helm.errors.v1.Errors.ErrorDetail.Builder.class);
      }

      // Construct using helm.errors.v1.Errors.ErrorDetail.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        reasonCode_ = "";
        retryable_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return helm.errors.v1.Errors.internal_static_helm_errors_v1_ErrorDetail_descriptor;
      }

      @java.lang.Override
      public helm.errors.v1.Errors.ErrorDetail getDefaultInstanceForType() {
        return helm.errors.v1.Errors.ErrorDetail.getDefaultInstance();
      }

      @java.lang.Override
      public helm.errors.v1.Errors.ErrorDetail build() {
        helm.errors.v1.Errors.ErrorDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public helm.errors.v1.Errors.ErrorDetail buildPartial() {
        helm.errors.v1.Errors.ErrorDetail result = new helm.errors.v1.Errors.ErrorDetail(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(helm.errors.v1.Errors.ErrorDetail result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.reasonCode_ = reasonCode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.retryable_ = retryable_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof helm.errors.v1.Errors.ErrorDetail) {
          return mergeFrom((helm.errors.v1.Errors.ErrorDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(helm.errors.v1.Errors.ErrorDetail other) {
        if (other == helm.errors.v1.Errors.ErrorDetail.getDefaultInstance()) return this;
        if (!other.getReasonCode().isEmpty()) {
          reasonCode_ = other.reasonCode_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getRetryable() != false) {
          setRetryable(other.getRetryable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                reasonCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                retryable_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object reasonCode_ = "";
      /**
       * <pre>
       * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
       * an open string. Empty when the error carries no registered code.
       * </pre>
       *
       * <code>string reason_code = 1;</code>
       * @return The reasonCode.
       */
      public java.lang.String getReasonCode() {
        java.lang.Object ref = reasonCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reasonCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
       * an open string. Empty when the error carries no registered code.
       * </pre>
       *
       * <code>string reason_code = 1;</code>
       * @return The bytes for reasonCode.
       */
      public com.google.protobuf.ByteString
          getReasonCodeBytes() {
        java.lang.Object ref = reasonCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reasonCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
       * an open string. Empty when the error carries no registered code.
       * </pre>
       *
       * <code>string reason_code = 1;</code>
       * @param value The reasonCode to set.
       * @return This builder for chaining.
       */
      public Builder setReasonCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        reasonCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
       * an open string. Empty when the error carries no registered code.
       * </pre>
       *
       * <code>string reason_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReasonCode() {
        reasonCode_ = getDefaultInstance().getReasonCode();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A code from protocols/json-schemas/reason-codes/reason-codes-v1.json, as
       * an open string. Empty when the error carries no registered code.
       * </pre>
       *
       * <code>string reason_code = 1;</code>
       * @param value The bytes for reasonCode to set.
       * @return This builder for chaining.
       */
      public Builder setReasonCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        reasonCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean retryable_ ;
      /**
       * <pre>
       * Whether repeating the same request can succeed.
       * </pre>
       *
       * <code>bool retryable = 2;</code>
       * @return The retryable.
       */
      @java.lang.Override
      public boolean getRetryable() {
        return retryable_;
      }
      /**
       * <pre>
       * Whether repeating the same request can succeed.
       * </pre>
       *
       * <code>bool retryable = 2;</code>
       * @param value The retryable to set.
       * @return This builder for chaining.
       */
      public Builder setRetryable(boolean value) {

        retryable_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether repeating the same request can succeed.
       * </pre>
       *
       * <code>bool retryable = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetryable() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retryable_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:helm.errors.v1.ErrorDetail)
    }

    // @@protoc_insertion_point(class_scope:helm.errors.v1.ErrorDetail)
    private static final helm.errors.v1.Errors.ErrorDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new helm.errors.v1.Errors.ErrorDetail();
    }

    public static helm.errors.v1.Errors.ErrorDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorDetail>
        PARSER = new com.google.protobuf.AbstractParser<ErrorDetail>() {
      @java.lang.Override
      public ErrorDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ErrorDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorDetail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public helm.errors.v1.Errors.ErrorDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helm_errors_v1_ErrorDetail_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_helm_errors_v1_ErrorDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033helm/errors/v1/errors.proto\022\016helm.erro" +
      "rs.v1\"5\n\013ErrorDetail\022\023\n\013reason_code\030\001 \001(" +
      "\t\022\021\n\tretryable\030\002 \001(\010B&Z$helm.mindburn.ru" +
      "n/errors/v1;errorsv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helm_errors_v1_ErrorDetail_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_helm_errors_v1_ErrorDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_helm_errors_v1_ErrorDetail_descriptor,
        new java.lang.String[] { "ReasonCode", "Retryable", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
