// Package channels provides the inbound channel gateway for multi-channel messaging.
//
// It is distinct from core/pkg/connectors/slack/ which is the outbound effect connector.
// This package handles inbound message normalization, envelope validation, session routing,
// and receipt generation for messages arriving from Slack, Telegram, Lark, WhatsApp, and Signal.
package channels

import (
	"errors"
	"fmt"
	"time"
)

// ChannelKind identifies the messaging platform a message arrived on.
type ChannelKind string

const (
	ChannelSlack    ChannelKind = "slack"
	ChannelTelegram ChannelKind = "telegram"
	ChannelLark     ChannelKind = "lark"
	ChannelWhatsApp ChannelKind = "whatsapp"
	ChannelSignal   ChannelKind = "signal"
)

// SenderTrustClass classifies the trust level assigned to a message sender.
type SenderTrustClass string

const (
	// SenderTrustVerified indicates the sender identity has been cryptographically verified.
	SenderTrustVerified SenderTrustClass = "verified"
	// SenderTrustKnownLow indicates the sender is known but has reduced trust.
	SenderTrustKnownLow SenderTrustClass = "known_low"
	// SenderTrustUnknown indicates the sender identity is unverified.
	SenderTrustUnknown SenderTrustClass = "unknown"
	// SenderTrustSuspicious indicates the sender exhibits suspicious behaviour.
	SenderTrustSuspicious SenderTrustClass = "suspicious"
)

// validChannelKinds is the set of accepted channel values.
var validChannelKinds = map[ChannelKind]struct{}{
	ChannelSlack:    {},
	ChannelTelegram: {},
	ChannelLark:     {},
	ChannelWhatsApp: {},
	ChannelSignal:   {},
}

// validSenderTrustClasses is the set of accepted trust class values.
var validSenderTrustClasses = map[SenderTrustClass]struct{}{
	SenderTrustVerified:   {},
	SenderTrustKnownLow:   {},
	SenderTrustUnknown:    {},
	SenderTrustSuspicious: {},
}

// ChannelAttachmentRef is a reference to an attachment artifact.
// The actual payload is stored in the artifact store; this struct is a content-addressed pointer.
type ChannelAttachmentRef struct {
	ArtifactID   string `json:"artifact_id"`
	MediaType    string `json:"media_type"`
	ContentHash  string `json:"content_hash"`
	PayloadClass string `json:"payload_class"`
}

// ChannelEnvelope is the normalised, channel-agnostic representation of an inbound message.
// All adapter implementations must map their raw wire format into this struct before passing
// the message further into the HELM pipeline.
type ChannelEnvelope struct {
	// EnvelopeID is a unique identifier generated by the receiving adapter.
	EnvelopeID string `json:"envelope_id"`
	// Channel identifies the platform this message arrived on.
	Channel ChannelKind `json:"channel"`
	// TenantID scopes the envelope to a specific HELM tenant.
	TenantID string `json:"tenant_id"`
	// SessionID is the HELM session this message belongs to.
	SessionID string `json:"session_id"`
	// MessageID is the platform-native message identifier.
	MessageID string `json:"message_id"`
	// ThreadID is the optional platform-native thread or conversation identifier.
	ThreadID string `json:"thread_id,omitempty"`
	// SenderID is the platform-native identifier of the sender.
	SenderID string `json:"sender_id"`
	// SenderHandle is the optional human-readable sender name or username.
	SenderHandle string `json:"sender_handle,omitempty"`
	// SenderTrust is the trust classification assigned to this sender.
	SenderTrust SenderTrustClass `json:"sender_trust"`
	// IdentityBindingRef links to the identity binding record in the identity store.
	IdentityBindingRef string `json:"identity_binding_ref,omitempty"`
	// ReceivedAtUnixMs is the UTC timestamp in milliseconds when the gateway received the message.
	ReceivedAtUnixMs int64 `json:"received_at_unix_ms"`
	// Text is the plain-text body of the message.
	Text string `json:"text,omitempty"`
	// Attachments holds references to attached artifacts.
	Attachments []ChannelAttachmentRef `json:"attachments,omitempty"`
	// Metadata carries channel-specific key/value pairs that do not fit the standard fields.
	Metadata map[string]string `json:"metadata,omitempty"`
	// SignatureRef links to the cryptographic signature of the original wire payload.
	SignatureRef string `json:"signature_ref,omitempty"`
}

// maxClockSkewMs is the maximum tolerated difference (in milliseconds) between the
// message timestamp and the current time. Messages outside this window are rejected
// to limit replay attacks.
const maxClockSkewMs = 5 * 60 * 1000 // 5 minutes

// ValidateEnvelope validates a ChannelEnvelope for structural correctness.
// It is fail-closed: any missing or implausible field returns an error.
func ValidateEnvelope(env ChannelEnvelope) error {
	var errs []error

	if env.EnvelopeID == "" {
		errs = append(errs, errors.New("envelope_id is required"))
	}
	if env.TenantID == "" {
		errs = append(errs, errors.New("tenant_id is required"))
	}
	if env.SessionID == "" {
		errs = append(errs, errors.New("session_id is required"))
	}
	if env.MessageID == "" {
		errs = append(errs, errors.New("message_id is required"))
	}
	if env.SenderID == "" {
		errs = append(errs, errors.New("sender_id is required"))
	}
	if !ValidChannelKind(env.Channel) {
		errs = append(errs, fmt.Errorf("channel %q is not a valid ChannelKind", env.Channel))
	}
	if _, ok := validSenderTrustClasses[env.SenderTrust]; !ok {
		errs = append(errs, fmt.Errorf("sender_trust %q is not a valid SenderTrustClass", env.SenderTrust))
	}
	if env.ReceivedAtUnixMs <= 0 {
		errs = append(errs, errors.New("received_at_unix_ms must be a positive Unix timestamp"))
	} else {
		nowMs := time.Now().UnixMilli()
		diff := nowMs - env.ReceivedAtUnixMs
		if diff < 0 {
			diff = -diff
		}
		if diff > maxClockSkewMs {
			errs = append(errs, fmt.Errorf(
				"received_at_unix_ms is outside acceptable clock skew window (%dms drift, max %dms)",
				diff, maxClockSkewMs,
			))
		}
	}

	if len(errs) == 0 {
		return nil
	}
	return errors.Join(errs...)
}

// ValidChannelKind returns true if kind is one of the recognised channel constants.
func ValidChannelKind(kind ChannelKind) bool {
	_, ok := validChannelKinds[kind]
	return ok
}
