name: SLSA L3 Provenance

on:
  release:
    types: [published]

permissions: read-all

jobs:
  build:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Build artifacts
        run: make build-release
      - name: Generate hashes
        id: hash
        run: |
          # sha256sum all artifacts and output for the provenance builder
          echo "hashes=$(sha256sum bin/* | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@68bad40844440577b33778c9f29077a3388838e9 # v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: true
